In [ ]:
# default_exp traceability.unsupervised.approach.d2v

# Experimenting Neural Unsupervised Approaches for Software Information Retrieval [d2v]

> This module is dedicated to evaluate doc2vec. Consider to Copy the entire notebook for a new and separeted empirical evaluation. 
> Implementing mutual information analysis
> Author: @danaderp April 2020
> Author: @danielrc Nov 2020

In [1]:
#!pip install gensim
#!pip install seaborn
#!pip install sklearn
!pip install -e .

Obtaining file:///Users/loganfecko/Desktop/Summer_Research/traceXplainer/notebooks
ERROR: file:///Users/loganfecko/Desktop/Summer_Research/traceXplainer/notebooks does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.

This copy is for Cisco purposes. It was adapted to process private github data from cisco.

In [2]:
import numpy as np
import gensim
import pandas as pd
from itertools import product 
from random import sample 
import functools 
import os
from enum import Enum, unique, auto

In [3]:
#export
from datetime import datetime
#import seaborn as sns

In [4]:
#export
import logging
logging.basicConfig(format='%(asctime)s : %(levelname)s : %(message)s', level=logging.INFO)

In [5]:
#export
from sklearn.metrics import precision_recall_curve
#from sklearn.metrics import plot_precision_recall_curve
from sklearn.metrics import auc
import matplotlib.pyplot as plt
from pandas.plotting import scatter_matrix
from pandas.plotting import lag_plot
import math as m
import random as r
import collections
from sklearn.metrics.pairwise import cosine_similarity

In [6]:
#export
from gensim.similarities import SparseTermSimilarityMatrix, WordEmbeddingSimilarityIndex
from gensim import corpora

In [7]:
#https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.cosine.html
#export
from scipy.spatial import distance
from scipy.stats import pearsonr

In [8]:
#export
from sklearn.metrics import average_precision_score
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score
from sklearn.metrics import confusion_matrix

In [9]:
from pathlib import Path

In [10]:
import sys, os

# point Python at the parent of ds4se/
sys.path.insert(0, os.path.abspath(os.path.join('..', 'main')))

In [11]:
import ds4se as ds

In [12]:
from ds4se.mgmnt.prep.conv import *

# Experients Set-up

In [13]:
class VectorizationType(Enum):
    word2vec = auto()
    doc2vec = auto()
    vsm2vec = auto()

In [14]:
VectorizationType.doc2vec

In [15]:
class LinkType(Enum):
    req2tc = auto()
    req2src = auto()
    issue2src = auto()
    pr2src = auto()

In [16]:
class DistanceMetric(Enum):
    WMD = auto()
    COS = auto()
    SCM = auto()
    EUC = auto()
    MAN = auto()

In [17]:
class SimilarityMetric(Enum):
    WMD_sim = auto()
    COS_sim = auto()
    SCM_sim = auto()
    EUC_sim = auto()
    MAN_sim = auto()
    Pearson = auto()

In [18]:
class EntropyMetric(Enum):
    MSI_I = auto() #Minimum shared information Entropy
    MSI_X = auto()

In [19]:
class Preprocessing(Enum):
    conv = auto()
    bpe = auto()

In [20]:
LinkType.req2src

In [21]:
Preprocessing.bpe

In [22]:
path_data = '../dvc-data/systems/dronology' #dataset path

In [23]:

path_to_trained_model = '../dvc-data/systems/dronology/2vec_models/bpe32k/doc2vec/[doc2vec-py-java-PVDBOW-500-20E-32k-c-1751384704.291919].model'

In [24]:
#CISCO GitHub Parameters
def sacp_params():
    return {
        "vectorizationType": VectorizationType.word2vec,
        "linkType": LinkType.issue2src,
        "system": 'sacp-python-common',
        "path_to_trained_model": path_data + 'models/wv/conv/[word2vec-Py-Java-Wiki-SK-500-20E[0]-1592979270.711115].model',
        "source_type": SoftwareArtifacts.PR,
        "target_type": SoftwareArtifacts.PY,
        "path_mappings": '/tf/data/cisco/sacp_data/sacp-pr-mappings.csv',
        "system_path_config": {
            "system_path": '/tf/data/cisco/sacp_data/[sacp-python-common-all-corpus-1596383717.992744].csv', #MUST have bpe8k <----
            "sep": '~',
            "names": ['ids','conv'],
            "prep": Preprocessing.conv
        },
        "saving_path":  path_data/'se-benchmarking/traceability/cisco/sacp',
        "names": ['Source','Target','Linked?']
    }

In [25]:
def sacp_params_bpe():
    return {
        "vectorizationType": VectorizationType.word2vec,
        "linkType": LinkType.issue2src,
        "system": 'sacp-python-common',
        "path_to_trained_model": path_to_trained_model,
        "source_type": SoftwareArtifacts.PR,
        "target_type": SoftwareArtifacts.PY,
        "path_mappings": '/tf/data/cisco/sacp_data/sacp-pr-mappings.csv',
        "system_path_config": {
            "system_path": '/tf/data/cisco/sacp_data/[sacp-python-common-all-corpus-1596383717.992744].csv',
            "sep": '~',
            "names": ['ids','bpe8k'],
            "prep": Preprocessing.bpe
        },
        "saving_path": path_data + 'se-benchmarking/traceability/cisco/sacp',
        "names": ['Source','Target','Linked?'],
        "model_prefix":path_data + 'models/bpe/sentencepiece/wiki_py_java_bpe_8k' #For BPE Analysis
    }

In [26]:
def dronology_params():
    return {
        "vectorizationType": VectorizationType.doc2vec,
        "linkType": LinkType.req2src,
        "system": 'dronology',
        "path_to_trained_model": path_to_trained_model,
        "source_type": 'req',
        "target_type": 'code',
        "path_mappings": '../dvc-data/systems/dronology/mappings/conventional.csv',
        "system_path_config":{
            "system_path": '../dvc-data/systems/dronology/corpus/dronology_conv_with_bpe_fixed.csv',
            "sep": '~',
            #"index_col": False,
            #"header": 0,
            "names": ['ids','bpe128k'],
            "prep": Preprocessing.bpe,
            "bpe_model_path": '../dvc-data/systems/dronology/bpe_models/java_py_bpe128k.model'
        },
        "saving_path": '../dvc-data/systems/dronology/experiment/4.1.5/results/',
        "names": ['Source','Target','Linked?']
    }

In [27]:

#parameters = sacp_params_bpe()
#parameters = sacp_params()
parameters = dronology_params()
parameters

{'vectorizationType': <VectorizationType.doc2vec: 2>,
 'linkType': <LinkType.req2src: 2>,
 'system': 'dronology',
 'path_to_trained_model': '../dvc-data/systems/dronology/2vec_models/bpe32k/doc2vec/[doc2vec-py-java-PVDBOW-500-20E-32k-c-1751384704.291919].model',
 'source_type': 'req',
 'target_type': 'code',
 'path_mappings': '../dvc-data/systems/dronology/mappings/conventional.csv',
 'system_path_config': {'system_path': '../dvc-data/systems/dronology/corpus/dronology_conv_with_bpe_fixed.csv',
  'sep': '~',
  'names': ['ids', 'bpe128k'],
  'prep': <Preprocessing.bpe: 2>,
  'bpe_model_path': '../dvc-data/systems/dronology/bpe_models/java_py_bpe128k.model'},
 'saving_path': '../dvc-data/systems/dronology/experiment/4.1.5/results/',
 'names': ['Source', 'Target', 'Linked?']}

### Testing experiments set-up

In [28]:
#tst
parameters['system_path_config']['system_path']

'../dvc-data/systems/dronology/corpus/dronology_conv_with_bpe_fixed.csv'

In [29]:
#tst
parameters['system_path_config']['names'][1]

'bpe128k'

In [30]:
parameters['system_path_config']['sep'] #tst

'~'

In [31]:
#tst
df_all_system = pd.read_csv(
            parameters['system_path_config']['system_path'], 
            #names = params['system_path_config']['names'], #include the names into the files!!!
            header = 0, 
            index_col = 0, 
            sep = "~"
    )

In [32]:
df_all_system.head(1)

,filenames,text,type,conv,bpe8k,bpe32k,bpe128k
ids,,,,,,,
/Users/loganfecko/Desktop/Summer_Research/traceXplainer/dvc-data/systems/dronology/corpus/req/RE-616.txt,RE-616.txt,[SUMMARY]\nLogging of GCS related events\n[DES...,req,summari log gcs relat event descript activ log...,▁sum m ari ▁log ▁g cs ▁rel at ▁event ▁descri p...,▁sum m ari ▁log ▁g cs ▁rel at ▁event ▁descri p...,▁summ ari ▁log ▁gcs ▁relat ▁event ▁descri pt ▁...

In [33]:
#tst
tag = parameters['system_path_config']['names'][1]
[doc.split() for doc in df_all_system[df_all_system[tag].notnull()][tag].values]

[['▁summ',
  'ari',
  '▁log',
  '▁gcs',
  '▁relat',
  '▁event',
  '▁descri',
  'pt',
  '▁activ',
  '▁logger',
  '▁shall',
  '▁log',
  '▁command',
  '▁sent',
  '▁mess',
  'ag',
  '▁rece',
  'iv',
  '▁cgs'],
 ['▁summ',
  'ari',
  '▁support',
  '▁gcs',
  '▁connect',
  '▁u',
  'av',
  '▁descri',
  'pt',
  '▁veh',
  'ic',
  'l',
  '▁core',
  '▁shall',
  '▁support',
  '▁u',
  'av',
  '▁connect',
  '▁via',
  '▁gcs'],
 ['▁summ',
  'ari',
  '▁manual',
  '▁flight',
  '▁plan',
  '▁assign',
  '▁descri',
  'pt',
  '▁rout',
  '▁contain',
  '▁spec',
  'if',
  '▁u',
  'av',
  '▁sing',
  'l',
  '▁u',
  'av',
  'flight',
  '▁plan',
  '▁sched',
  'ul',
  '▁shall',
  '▁assign',
  '▁rout',
  '▁given',
  '▁u',
  'av'],
 ['▁summ',
  'ari',
  '▁visit',
  '▁waypoint',
  '▁flight',
  '▁plan',
  '▁descri',
  'pt',
  '▁flight',
  '▁plan',
  '▁execut',
  '▁veh',
  'ic',
  'l',
  '▁core',
  '▁shall',
  '▁send',
  '▁next',
  '▁waypoint',
  '▁u',
  'av'],
 ['▁summ',
  'ari',
  '▁establish',
  '▁maximum',
  '▁number',
  '▁activ',
  '▁u',
  'av',
  '▁descri',
  'pt',
  '▁maximum',
  '▁number',
  '▁allow',
  '▁activ',
  '▁u',
  'av',
  '▁reach',
  '▁u',
  'av',
  'activ',
  '▁man',
  'ag',
  '▁shall',
  '▁reject',
  '▁activ',
  '▁request'],
 ['▁summ',
  'ari',
  '▁support',
  '▁intern',
  '▁simul',
  '▁u',
  'av',
  '▁descri',
  'pt',
  '▁veh',
  'ic',
  'l',
  '▁core',
  '▁shall',
  '▁support',
  '▁virtual',
  '▁u',
  'av'],
 ['▁summ',
  'ari',
  '▁middle',
  'war',
  '▁list',
  '▁save',
  '▁flight',
  '▁rout',
  '▁descri',
  'pt',
  '▁u',
  'im',
  'iddle',
  'war',
  '▁shall',
  '▁provid',
  '▁list',
  '▁exist',
  '▁rout'],
 ['▁summ',
  'ari',
  '▁mission',
  '▁plan',
  '▁descri',
  'pt',
  '▁mission',
  '▁planner',
  '▁shall',
  '▁execut',
  '▁flight',
  '▁plan',
  '▁multi',
  'pl',
  '▁u',
  'av',
  '▁conc',
  'ur',
  'r'],
 ['▁summ',
  'ari',
  '▁log',
  '▁flight',
  '▁plan',
  '▁relat',
  '▁event',
  '▁descri',
  'pt',
  '▁activ',
  '▁logger',
  '▁shall',
  '▁log',
  '▁flight',
  '▁plan',
  '▁relat',
  '▁event'],
 ['▁summ',
  'ari',
  '▁accept',
  '▁mission',
  '▁plan',
  '▁descri',
  'pt',
  '▁u',
  'im',
  'iddle',
  'war',
  '▁shall',
  '▁accept',
  '▁activ',
  '▁mission',
  '▁plan',
  '▁upon',
  '▁request'],
 ['▁summ',
  'ari',
  '▁multi',
  'pl',
  '▁map',
  '▁type',
  '▁descri',
  'pt',
  '▁map',
  '▁com',
  'pon',
  '▁shall',
  '▁support',
  '▁differ',
  '▁type',
  '▁map',
  '▁layer',
  '▁terrain',
  '▁sat',
  'ell',
  'it'],
 ['▁summ',
  'ari',
  '▁transmit',
  '▁rout',
  '▁assign',
  '▁middle',
  'war',
  '▁descri',
  'pt',
  '▁rout',
  '▁assign',
  '▁remov',
  '▁u',
  'av',
  '▁rout',
  '▁assign',
  '▁shall',
  '▁not',
  'ifi',
  '▁d',
  'ron',
  'olog'],
 ['▁summ',
  'ari',
  '▁monitor',
  '▁mess',
  'ag',
  '▁descri',
  'pt',
  '▁d',
  'ron',
  'olog',
  '▁run',
  'tim',
  '▁monitor',
  '▁shall',
  '▁provid',
  '▁function',
  '▁retriev',
  '▁monitor',
  '▁mess',
  'ag',
  '▁distrib',
  'ut',
  '▁client'],
 ['▁summ',
  'ari',
  '▁u',
  'av',
  '▁command',
  '▁descri',
  'pt',
  '▁gcs',
  'middle',
  'war',
  '▁shall',
  '▁forward',
  '▁command',
  '▁sent',
  '▁d',
  'ron',
  'olog',
  '▁gcs'],
 ['▁summ',
  'ari',
  '▁ground',
  'stat',
  '▁middle',
  'war',
  '▁commun',
  'ic',
  '▁protocol',
  '▁descri',
  'pt',
  '▁gcs',
  'middle',
  'war',
  '▁shall',
  '▁follow',
  '▁pre',
  'def',
  'in',
  '▁set',
  '▁step',
  '▁establish',
  '▁connect',
  '▁gcs',
  '▁d',
  'ron',
  'olog'],
 ['▁summ',
  'ari',
  '▁calc',
  'ul',
  '▁dist',
  'anc',
  '▁descri',
  'pt',
  '▁given',
  '▁two',
  '▁co',
  'ordin',
  '▁co',
  'ordin',
  '▁system',
  '▁shall',
  '▁comput',
  '▁dist',
  'anc'],
 ['▁summ',
  'ari',
  '▁one',
  '▁instanc',
  '▁reg',
  'ist',
  '▁drone',
  '▁may',
  '▁activ',
  '▁time',
  '▁descri',
  'pt',
  '▁u',
  'av',
  'activ',
  '▁man',
  'ag',
  '▁shall',
  '▁ens',
  'ur',
  '▁one',
  '▁instanc',
  '▁reg',
  'ist',
  '▁drone',
  '▁activ',
  '▁time'],
 ['▁summ',
  'ari',
  '▁display',
  '▁activ',
  '▁rout',
  '▁descri',
  'pt',
  '▁real',
  '▁time',
  '▁flight',
  '▁shall',
  '▁display',
  '▁current',
  '▁activ',
  '▁flight',
  '▁plan',
  '▁map'],
 ['▁summ',
  'ari',
  '▁flight',
  '▁rout',
  '▁def',
  'in',
  '▁waypoint',
  '▁descri',
  'pt',
  '▁flight',
  '▁rout',
  '▁man',
  'ag',
  '▁shall',
  '▁def',
  'in',
  '▁flight',
  '▁rout',
  '▁order',
  '▁sequ',
  'enc',
  '▁waypoint',
  '▁first',
  '▁waypoint',
  '▁rep',
  'res',
  '▁first',
  '▁target',
  '▁loc',
  'at',
  '▁final',
  '▁waypoint',
  '▁rep',
  'res',
  '▁final',
  '▁target',
  '▁loc',
  'at'],
 ['▁summ',
  'ari',
  '▁delet',
  '▁rout',
  '▁descri',
  'pt',
  '▁rout',
  '▁creation',
  '▁shall',
  '▁allow',
  '▁user',
  '▁delet',
  '▁rout'],
 ['▁summ',
  'ari',
  '▁assign',
  '▁new',
  '▁flight',
  '▁plan',
  '▁upon',
  '▁complet',
  '▁previous',
  '▁flight',
  '▁descri',
  'pt',
  '▁u',
  'av',
  '▁pend',
  '▁flight',
  '▁plan',
  '▁reach',
  '▁final',
  '▁waypoint',
  '▁current',
  '▁flight',
  '▁plan',
  '▁sing',
  'l',
  '▁u',
  'av',
  'flight',
  '▁plan',
  '▁sched',
  'ul',
  '▁shall',
  '▁execut',
  '▁next',
  '▁assign',
  '▁flight',
  '▁plan'],
 ['▁summ',
  'ari',
  '▁flight',
  '▁rout',
  '▁persist',
  '▁descri',
  'pt',
  '▁flight',
  '▁rout',
  '▁man',
  'ag',
  '▁shall',
  '▁persist',
  '▁flight',
  '▁rout'],
 ['▁summ',
  'ari',
  '▁u',
  'av',
  '▁ident',
  'if',
  '▁descri',
  'pt',
  '▁veh',
  'ic',
  'l',
  '▁core',
  '▁shall',
  '▁assign',
  '▁uniqu',
  '▁activ',
  '▁u',
  'av'],
 ['▁summ',
  'ari',
  '▁publish',
  '▁monitor',
  '▁mess',
  'ag',
  '▁descri',
  'pt',
  '▁d',
  'ron',
  'olog',
  '▁run',
  'tim',
  '▁monitor',
  '▁shall',
  '▁abl',
  '▁rece',
  'iv',
  '▁mess',
  'ag',
  '▁d',
  'ron',
  'olog',
  '▁com',
  'pon'],
 ['▁summ',
  'ari',
  '▁co',
  'ordin',
  '▁system',
  '▁convers',
  '▁descri',
  'pt',
  '▁request',
  '▁co',
  'ordin',
  '▁system',
  '▁shall',
  '▁transform',
  '▁co',
  'ordin',
  '▁altern',
  '▁format'],
 ['▁summ',
  'ari',
  '▁remov',
  '▁plan',
  '▁flight',
  '▁descri',
  'pt',
  '▁request',
  '▁sing',
  'l',
  '▁u',
  'av',
  'flight',
  '▁plan',
  '▁sched',
  'ul',
  '▁shall',
  '▁unassign',
  '▁flight',
  '▁plan',
  '▁assign',
  '▁u',
  'av',
  '▁await',
  '▁execut'],
 ['▁summ',
  'ari',
  '▁display',
  '▁map',
  '▁descri',
  'pt',
  '▁real',
  '▁time',
  '▁flight',
  '▁load',
  '▁map',
  '▁shall',
  '▁display'],
 ['▁summ',
  'ari',
  '▁rout',
  '▁creation',
  '▁mod',
  'if',
  '▁descri',
  'pt',
  '▁rout',
  '▁creation',
  '▁shall',
  '▁allow',
  '▁user',
  '▁cre',
  'at',
  '▁mod',
  'ifi',
  '▁rout'],
 ['▁summ',
  'ari',
  '▁remov',
  '▁pend',
  '▁plan',
  '▁return',
  '▁home',
  '▁descri',
  'pt',
  '▁u',
  'av',
  '▁current',
  '▁flight',
  '▁cancel',
  '▁sing',
  'l',
  '▁u',
  'av',
  'flight',
  '▁plan',
  '▁sched',
  'ul',
  '▁shall',
  '▁turn',
  '▁cancel',
  '▁sched',
  'ul',
  '▁flight',
  '▁plan',
  '▁u',
  'av'],
 ['▁summ',
  'ari',
  '▁connect',
  '▁gcs',
  '▁d',
  'ron',
  'olog',
  '▁via',
  '▁middle',
  'war',
  '▁descri',
  'pt',
  '▁gcs',
  'middle',
  'war',
  '▁shall',
  '▁hand',
  'l',
  '▁multi',
  'pl',
  '▁gcs'],
 ['▁summ',
  'ari',
  '▁load',
  '▁default',
  '▁co',
  'ordin',
  '▁descri',
  'pt',
  '▁load',
  '▁map',
  '▁view',
  '▁shall',
  '▁posit',
  '▁pre',
  '▁def',
  'in',
  '▁loc',
  'at'],
 ['▁summ',
  'ari',
  '▁u',
  'av',
  '▁mess',
  'ag',
  '▁descri',
  'pt',
  '▁gcs',
  'middle',
  'war',
  '▁shall',
  '▁hand',
  'l',
  '▁state',
  '▁mess',
  'ag',
  '▁monitor',
  '▁mess',
  'ag',
  '▁mode',
  '▁chang',
  '▁mess',
  'ag',
  '▁rece',
  'iv',
  '▁gcs'],
 ['▁summ',
  'ari',
  '▁spec',
  'ifi',
  '▁takeoff',
  '▁alt',
  'itud',
  '▁descri',
  'pt',
  '▁flight',
  '▁rout',
  '▁requ',
  'ir',
  '▁custom',
  '▁takeoff',
  '▁alt',
  'itud',
  '▁differ',
  '▁system',
  '▁default',
  '▁takeoff',
  '▁alt',
  'itud',
  '▁shall',
  '▁spec',
  'ifi',
  '▁flight',
  '▁rout'],
 ['▁summ',
  'ari',
  '▁u',
  'av',
  '▁flight',
  '▁plan',
  '▁execut',
  '▁descri',
  'pt',
  '▁sing',
  'l',
  '▁u',
  'av',
  'flight',
  '▁plan',
  '▁sched',
  'ul',
  '▁shall',
  '▁execut',
  '▁one',
  '▁flight',
  '▁plan',
  '▁time',
  '▁u',
  'av'],
 ['▁summ',
  'ari',
  '▁display',
  '▁activ',
  '▁u',
  'av',
  '▁descri',
  'pt',
  '▁real',
  '▁time',
  '▁flight',
  '▁shall',
  '▁display',
  '▁name',
  '▁status',
  '▁current',
  '▁activ',
  '▁u',
  'av'],
 ['▁summ',
  'ari',
  '▁follow',
  '▁u',
  'av',
  '▁descri',
  'pt',
  '▁real',
  '▁time',
  '▁flight',
  '▁shall',
  '▁allow',
  '▁user',
  '▁follow',
  '▁one',
  '▁multi',
  'pl',
  '▁u',
  'av',
  '▁map'],
 ['▁summ',
  'ari',
  '▁mod',
  'ifi',
  '▁assign',
  '▁rout',
  '▁descri',
  'pt',
  '▁user',
  '▁may',
  '▁reorder',
  '▁rout',
  '▁remov',
  '▁flight',
  '▁plan',
  '▁assign',
  '▁u',
  'av',
  '▁long',
  '▁flight',
  '▁start',
  '▁execut'],
 ['▁summ',
  'ari',
  '▁assign',
  '▁rout',
  '▁descri',
  'pt',
  '▁rout',
  '▁assign',
  '▁shall',
  '▁provid',
  '▁mean',
  '▁select',
  '▁exist',
  '▁rout',
  '▁assign',
  '▁u',
  'av'],
 ['▁summ',
  'ari',
  '▁u',
  'av',
  '▁oper',
  '▁descri',
  'pt',
  '▁real',
  '▁time',
  '▁flight',
  '▁shall',
  '▁allow',
  '▁user',
  '▁appl',
  'i',
  '▁flight',
  '▁oper',
  '▁one',
  '▁select',
  '▁u',
  'av'],
 ['▁summ',
  'ari',
  '▁display',
  '▁list',
  '▁exist',
  '▁rout',
  '▁descri',
  'pt',
  '▁rout',
  '▁creation',
  '▁load',
  '▁list',
  '▁exist',
  '▁rout',
  '▁shall',
  '▁display'],
 ['▁summ',
  'ari',
  '▁emer',
  'g',
  '▁oper',
  '▁descri',
  'pt',
  '▁real',
  '▁time',
  '▁flight',
  '▁shall',
  '▁allow',
  '▁user',
  '▁perform',
  '▁emer',
  'g',
  '▁oper',
  '▁hover',
  '▁multi',
  'pl',
  '▁u',
  'av',
  '▁send',
  '▁multi',
  'pl',
  '▁u',
  'av',
  '▁home',
  '▁group',
  '▁u',
  'av'],
 ['▁summ',
  'ari',
  '▁middle',
  'war',
  '▁support',
  '▁rout',
  '▁assign',
  '▁u',
  'av',
  '▁descri',
  'pt',
  '▁u',
  'im',
  'iddle',
  'war',
  '▁shall',
  '▁en',
  'abl',
  '▁exist',
  '▁rout',
  '▁assign',
  '▁activ',
  '▁u',
  'av'],
 ['▁summ',
  'ari',
  '▁hover',
  '▁complet',
  '▁flight',
  '▁descri',
  'pt',
  '▁u',
  'av',
  '▁pend',
  '▁flight',
  '▁plan',
  '▁reach',
  '▁final',
  '▁waypoint',
  '▁current',
  '▁flight',
  '▁plan',
  '▁sing',
  'l',
  '▁u',
  'av',
  'flight',
  '▁plan',
  '▁sched',
  'ul',
  '▁shall',
  '▁not',
  'ifi',
  '▁u',
  'av',
  '▁hover',
  '▁place'],
 ['▁summ',
  'ari',
  '▁pre',
  'def',
  'in',
  '▁flight',
  '▁pattern',
  '▁descri',
  'pt',
  '▁mission',
  '▁planner',
  '▁shall',
  '▁man',
  'ag',
  '▁pre',
  'def',
  'in',
  '▁flight',
  '▁pattern'],
 ['▁summ',
  'ari',
  '▁simul',
  '▁land',
  '▁descri',
  'pt',
  '▁given',
  '▁land',
  '▁command',
  '▁intern',
  '▁simul',
  '▁shall',
  '▁move',
  '▁u',
  'av',
  '▁ground',
  '▁alt',
  'itud',
  '▁correspond',
  '▁current',
  '▁long',
  'itud',
  '▁lat',
  'itud'],
 ['▁summ',
  'ari',
  '▁u',
  'av',
  '▁state',
  '▁transit',
  '▁descri',
  'pt',
  '▁request',
  '▁veh',
  'ic',
  'l',
  '▁core',
  '▁shall',
  '▁shall',
  '▁transit',
  '▁u',
  'av',
  '▁state',
  '▁accord',
  '▁allow',
  '▁state',
  '▁transit',
  '▁depict',
  '▁u',
  'av',
  '▁state',
  '▁transit',
  '▁diagram'],
 ['▁summ',
  'ari',
  '▁simul',
  '▁batter',
  'i',
  '▁descri',
  'pt',
  '▁intern',
  '▁simul',
  '▁shall',
  '▁approxim',
  '▁state',
  '▁batter',
  'i'],
 ['▁summ',
  'ari',
  '▁middle',
  'war',
  '▁provid',
  '▁support',
  '▁mod',
  'ifi',
  '▁flight',
  '▁rout',
  '▁descri',
  'pt',
  '▁u',
  'im',
  'iddle',
  'war',
  '▁shall',
  '▁en',
  'abl',
  '▁creation',
  '▁mod',
  'if',
  '▁flight',
  '▁rout'],
 ['▁summ',
  'ari',
  '▁simul',
  '▁goto',
  '▁descri',
  'pt',
  '▁given',
  '▁goto',
  '▁command',
  '▁intern',
  '▁simul',
  '▁shall',
  '▁up',
  'dat',
  '▁loc',
  'at',
  '▁u',
  'av',
  '▁increment',
  '▁simul',
  '▁step',
  '▁size',
  '▁meter',
  '▁move',
  '▁toward',
  '▁target',
  '▁dest',
  'in',
  '▁dest',
  'in',
  '▁reach'],
 ['▁summ',
  'ari',
  '▁simul',
  '▁takeoff',
  '▁descri',
  'pt',
  '▁given',
  '▁takeoff',
  '▁command',
  '▁intern',
  '▁simul',
  '▁shall',
  '▁move',
  '▁u',
  'av',
  '▁takeoff',
  '▁alt',
  'itud',
  '▁correspond',
  '▁current',
  '▁long',
  'itud',
  '▁lat',
  'itud'],
 ['▁summ',
  'ari',
  '▁waypoint',
  '▁definit',
  '▁descri',
  'pt',
  '▁waypoint',
  '▁shall',
  '▁spec',
  'ifi',
  '▁use',
  '▁co',
  'ordin',
  '▁includ',
  '▁long',
  'itud',
  '▁lat',
  'itud',
  '▁alt',
  'itud'],
 ['▁summ',
  'ari',
  '▁flight',
  '▁plan',
  '▁sched',
  'ul',
  '▁descri',
  'pt',
  '▁request',
  '▁sing',
  'l',
  '▁u',
  'av',
  'flight',
  '▁plan',
  '▁sched',
  'ul',
  '▁shall',
  '▁sched',
  'ul',
  '▁rout',
  '▁execut'],
 ['▁summ',
  'ari',
  '▁middle',
  'war',
  '▁forward',
  '▁command',
  '▁client',
  '▁d',
  'ron',
  'olog',
  '▁descri',
  'pt',
  '▁u',
  'im',
  'iddle',
  'war',
  '▁accept',
  '▁command',
  '▁forward',
  '▁d',
  'ron',
  'olog'],
 ['▁summ',
  'ari',
  '▁middle',
  'war',
  '▁list',
  '▁current',
  '▁activ',
  '▁u',
  'av',
  '▁descri',
  'pt',
  '▁u',
  'im',
  'iddle',
  'war',
  '▁shall',
  '▁provid',
  '▁list',
  '▁activ',
  '▁u',
  'av'],
 ['▁summ',
  'ari',
  '▁return',
  '▁home',
  '▁without',
  '▁detour',
  '▁descri',
  'pt',
  '▁return',
  '▁home',
  '▁command',
  '▁iss',
  'u',
  '▁flight',
  '▁man',
  'ag',
  '▁shall',
  '▁return',
  '▁u',
  'av',
  '▁origin',
  '▁launch',
  '▁loc',
  'at',
  '▁without',
  '▁iss',
  'u',
  '▁add',
  'it',
  '▁waypoint',
  '▁rout',
  '▁command'],
 ['▁summ',
  'ari',
  '▁de',
  'activ',
  '▁physic',
  '▁u',
  'av',
  '▁descri',
  'pt',
  '▁u',
  'av',
  '▁de',
  'activ',
  '▁u',
  'av',
  'activ',
  '▁man',
  'ag',
  '▁shall',
  '▁cancel',
  '▁current',
  '▁sched',
  'ul',
  '▁flight',
  '▁plan'],
 ['▁summ',
  'ari',
  '▁cancel',
  '▁mission',
  '▁descri',
  'pt',
  '▁request',
  '▁mission',
  '▁current',
  '▁activ',
  '▁mission',
  '▁planner',
  '▁shall',
  '▁cancel',
  '▁activ',
  '▁mission'],
 ['▁summ',
  'ari',
  '▁autom',
  'at',
  '▁flight',
  '▁plan',
  '▁assign',
  '▁descri',
  'pt',
  '▁sched',
  'ul',
  '▁flight',
  '▁manual',
  '▁assign',
  '▁u',
  'av',
  '▁sing',
  'l',
  '▁u',
  'av',
  'flight',
  '▁plan',
  '▁sched',
  'ul',
  '▁shall',
  '▁assign',
  '▁rout',
  '▁autom',
  'at',
  '▁u',
  'av'],
 ['▁packag',
  '▁edu',
  '▁d',
  'ron',
  'olog',
  '▁servic',
  '▁ext',
  'ens',
  '▁mission',
  'plan',
  '▁import',
  '▁java',
  '▁io',
  'except',
  '▁import',
  '▁java',
  '▁util',
  '▁hash',
  '▁map',
  '▁import',
  '▁java',
  '▁util',
  '▁map',
  '▁import',
  '▁java',
  '▁util',
  '▁map',
  '▁ent',
  'ri',
  '▁import',
  '▁org',
  '▁json',
  '▁json',
  'except',
  '▁import',
  '▁edu',
  '▁d',
  'ron',
  'olog',
  '▁core',
  '▁d',
  'ron',
  'olog',
  '▁constant',
  '▁import',
  '▁edu',
  '▁d',
  'ron',
  'olog',
  '▁core',
  '▁co',
  'ordin',
  '▁l',
  'la',
  '▁co',
  'ordin',
  '▁import',
  '▁edu',
  '▁d',
  'ron',
  'olog',
  '▁core',
  '▁veh',
  'ic',
  'l',
  '▁iu',
  'av',
  'pro',
  'xi',
  '▁import',
  '▁edu',
  '▁d',
  'ron',
  'olog',
  '▁servic',
  '▁core',
  '▁util',
  '▁d',
  'ron',
  'olog',
  '▁servic',
  '▁except',
  '▁import',
  '▁edu',
  '▁d',
  'ron',
  'olog',
  '▁servic',
  '▁ext',
  'ens',
  '▁mission',
  'plan',
  '▁mission',
  '▁execut',
  '▁except',
  '▁import',
  '▁edu',
  '▁d',
  'ron',
  'olog',
  '▁servic',
  '▁ext',
  'ens',
  '▁mission',
  'plan',
  '▁plan',
  '▁i',
  'execut',
  '▁mission',
  '▁plan',
  '▁import',
  '▁edu',
  '▁d',
  'ron',
  'olog',
  '▁servic',
  '▁ext',
  'ens',
  '▁mission',
  'plan',
  '▁plan',
  '▁mission',
  '▁util',
  '▁import',
  '▁edu',
  '▁d',
  'ron',
  'olog',
  '▁servic',
  '▁ext',
  'ens',
  '▁mission',
  'plan',
  '▁plan',
  '▁u',
  'av',
  'miss',
  '▁plan',
  '▁import',
  '▁edu',
  '▁d',
  'ron',
  'olog',
  '▁servic',
  '▁ext',
  'ens',
  '▁mission',
  'plan',
  '▁sync',
  '▁synchron',
  '▁man',
  'ag',
  '▁import',
  '▁edu',
  '▁d',
  'ron',
  'olog',
  '▁servic',
  '▁ext',
  'ens',
  '▁mission',
  'plan',
  '▁task',
  '▁task',
  '▁factor',
  'i',
  '▁import',
  '▁edu',
  '▁d',
  'ron',
  'olog',
  '▁servic',
  '▁instanc',
  '▁drones',
  'et',
  'up',
  '▁drone',
  '▁setup',
  '▁servic',
  '▁import',
  '▁net',
  '▁log',
  '▁i',
  'logg',
  '▁import',
  '▁net',
  '▁log',
  '▁logger',
  '▁provid',
  '▁man',
  'ag',
  '▁mission',
  '▁plan',
  '▁mission',
  '▁plan',
  '▁one',
  '▁code',
  '▁full',
  '▁mission',
  '▁plan',
  '▁code',
  '▁instanc',
  '▁one',
  '▁code',
  '▁u',
  'av',
  'miss',
  '▁plan',
  '▁code',
  '▁instanc',
  '▁u',
  'av',
  '▁mission',
  '▁plan',
  '▁u',
  'av',
  '▁individ',
  'u',
  '▁mission',
  '▁plan',
  '▁compos',
  '▁mission',
  '▁task',
  '▁ent',
  'ir',
  '▁mission',
  '▁plan',
  '▁load',
  '▁thread',
  '▁cre',
  'at',
  '▁check',
  '▁individ',
  'u',
  '▁u',
  'av',
  'miss',
  '▁plan',
  '▁determin',
  '▁start',
  '▁next',
  '▁task',
  '▁author',
  '▁j',
  'ane',
  '▁cl',
  'eland',
  '▁hu',
  'ang',
  '▁deprec',
  '▁public',
  '▁class',
  '▁full',
  '▁mission',
  '▁plan',
  '▁implement',
  '▁i',
  'execut',
  '▁mission',
  '▁plan',
  '▁privat',
  '▁static',
  '▁final',
  '▁i',
  'logg',
  '▁logger',
  '▁logger',
  '▁provid',
  '▁get',
  '▁logger',
  '▁full',
  '▁mission',
  '▁plan',
  '▁class',
  '▁privat',
  '▁map',
  '▁string',
  '▁u',
  'av',
  'miss',
  '▁plan',
  '▁u',
  'av',
  '▁mission',
  '▁plan',
  '▁privat',
  '▁synchron',
  '▁man',
  'ag',
  '▁synch',
  '▁point',
  '▁mgr',
  '▁privat',
  '▁string',
  '▁mission',
  '▁construct',
  '▁co',
  'ordin',
  '▁mission',
  '▁instanc',
  '▁mission',
  '▁consist',
  '▁one',
  '▁u',
  'av',
  '▁set',
  '▁assign',
  '▁task',
  '▁synchron',
  '▁point',
  '▁param',
  '▁mission',
  '▁public',
  '▁full',
  '▁mission',
  '▁plan',
  '▁string',
  '▁mission',
  '▁mission',
  '▁mission',
  '▁u',
  'av',
  '▁mission',
  '▁plan',
  '▁new',
  '▁hash',
  '▁map',
  '▁synch',
  '▁point',
  '▁mgr',
  '▁synchron',
  '▁man',
  'ag',
  '▁get',
  '▁instanc',
  '▁load',
  '▁mission',
  '▁json',
  '▁file',
  '▁current',
  '▁hard',
  '▁code',
  '▁param',
  '▁mission',
  '▁throw',
  '▁mission',
  '▁execut',
  '▁except',
  '▁privat',
  '▁void',
  '▁load',
  '▁mission',
  '▁string',
  '▁mission',
  '▁throw',
  '▁mission',
  '▁execut',
  '▁except',
  '▁json',
  'miss',
  '▁plan',
  '▁reader',
  '▁json',
  '▁reader',
  '▁new',
  '▁json',
  'miss',
  '▁plan',
  '▁reader',
  '▁tri',
  '▁json',
  '▁reader',
  '▁pars',
  '▁mission',
  '▁mission',
  '▁catch',
  '▁io',
  'except',
  '▁json',
  'except',
  '▁throw',
  '▁new',
  '▁mission',
  '▁execut',
  '▁except',
  '▁get',
  '▁mess',
  'ag',
  '▁add',
  '▁add',
  'it',
  '▁u',
  'av',
  '▁mission',
  '▁plan',
  '▁cre',
  'at',
  '▁code',
  '▁u',
  'av',
  'miss',
  '▁task',
  '▁code',
  '▁instanc',
  '▁pass',
  '▁refer',
  '▁code',
  '▁synch',
  '▁point',
  '▁mgr',
  '▁code',
  '▁param',
  '▁u',
  'av',
  '▁u',
  'av',
  '▁throw',
  '▁mission',
  '▁execut',
  '▁except',
  '▁public',
  '▁void',
  '▁add',
  '▁u',
  'av',
  '▁string',
  '▁u',
  'av',
  '▁throw',
  '▁mission',
  '▁execut',
  '▁except',
  '▁u',
  'av',
  'miss',
  '▁plan',
  '▁plan',
  '▁new',
  '▁u',
  'av',
  'miss',
  '▁plan',
  '▁u',
  'av',
  '▁synch',
  '▁point',
  '▁mgr',
  '▁u',
  'av',
  '▁mission',
  '▁plan',
  '▁contain',
  '▁key',
  '▁u',
  'av',
  '▁throw',
  '▁new',
  '▁mission',
  '▁execut',
  '▁except',
  '▁mission',
  '▁plan',
  '▁u',
  'av',
  '▁u',
  'av',
  '▁al',
  'read',
  'i',
  '▁def',
  'in',
  '▁");',
  '▁u',
  'av',
  '▁mission',
  '▁plan',
  '▁put',
  '▁u',
  'av',
  '▁plan',
  '▁public',
  '▁void',
  '▁remov',
  '▁u',
  'av',
  '▁string',
  '▁u',
  'av',
  '▁u',
  'av',
  '▁mission',
  '▁plan',
  '▁remov',
  '▁u',
  'av',
  '▁/**',
  '▁assign',
  '▁task',
  '▁spec',
  'if',
  '▁u',
  'av',
  '▁param',
  '▁u',
  'av',
  '▁u',
  'av',
  '▁ident',
  'ifi',
  '▁param',
  '▁task',
  '▁task',
  '▁perform',
  '▁rout',
  '▁waypoint',
  '▁synchron',
  '▁flight',
  '▁pattern',
  '▁param',
  '▁task',
  '▁task',
  '▁spec',
  'if',
  '▁spec',
  'if',
  '▁waypoint',
  '▁rout',
  '▁name',
  '▁etc',
  '▁throw',
  '▁mission',
  '▁execut',
  '▁except',
  '▁public',

In [34]:
len(df_all_system[tag].values) #tst

242

In [35]:
#tst
len(df_all_system[df_all_system[tag].notnull()]) #some files are _init_ thefore are empty

242

In [36]:
#tst
df_all_system[df_all_system[tag].notnull()][tag].values

array(['▁summ ari ▁log ▁gcs ▁relat ▁event ▁descri pt ▁activ ▁logger ▁shall ▁log ▁command ▁sent ▁mess ag ▁rece iv ▁cgs',
       '▁summ ari ▁support ▁gcs ▁connect ▁u av ▁descri pt ▁veh ic l ▁core ▁shall ▁support ▁u av ▁connect ▁via ▁gcs',
       '▁summ ari ▁manual ▁flight ▁plan ▁assign ▁descri pt ▁rout ▁contain ▁spec if ▁u av ▁sing l ▁u av flight ▁plan ▁sched ul ▁shall ▁assign ▁rout ▁given ▁u av',
       '▁summ ari ▁visit ▁waypoint ▁flight ▁plan ▁descri pt ▁flight ▁plan ▁execut ▁veh ic l ▁core ▁shall ▁send ▁next ▁waypoint ▁u av',
       '▁summ ari ▁establish ▁maximum ▁number ▁activ ▁u av ▁descri pt ▁maximum ▁number ▁allow ▁activ ▁u av ▁reach ▁u av activ ▁man ag ▁shall ▁reject ▁activ ▁request',
       '▁summ ari ▁support ▁intern ▁simul ▁u av ▁descri pt ▁veh ic l ▁core ▁shall ▁support ▁virtual ▁u av',
       '▁summ ari ▁middle war ▁list ▁save ▁flight ▁rout ▁descri pt ▁u im iddle war ▁shall ▁provid ▁list ▁exist ▁rout',
       '▁summ ari ▁mission ▁plan ▁descri pt ▁mission ▁planner ▁shall ▁execut ▁flight ▁plan ▁multi pl ▁u av ▁conc ur r',
       '▁summ ari ▁log ▁flight ▁plan ▁relat ▁event ▁descri pt ▁activ ▁logger ▁shall ▁log ▁flight ▁plan ▁relat ▁event',
       '▁summ ari ▁accept ▁mission ▁plan ▁descri pt ▁u im iddle war ▁shall ▁accept ▁activ ▁mission ▁plan ▁upon ▁request',
       '▁summ ari ▁multi pl ▁map ▁type ▁descri pt ▁map ▁com pon ▁shall ▁support ▁differ ▁type ▁map ▁layer ▁terrain ▁sat ell it',
       '▁summ ari ▁transmit ▁rout ▁assign ▁middle war ▁descri pt ▁rout ▁assign ▁remov ▁u av ▁rout ▁assign ▁shall ▁not ifi ▁d ron olog',
       '▁summ ari ▁monitor ▁mess ag ▁descri pt ▁d ron olog ▁run tim ▁monitor ▁shall ▁provid ▁function ▁retriev ▁monitor ▁mess ag ▁distrib ut ▁client',
       '▁summ ari ▁u av ▁command ▁descri pt ▁gcs middle war ▁shall ▁forward ▁command ▁sent ▁d ron olog ▁gcs',
       '▁summ ari ▁ground stat ▁middle war ▁commun ic ▁protocol ▁descri pt ▁gcs middle war ▁shall ▁follow ▁pre def in ▁set ▁step ▁establish ▁connect ▁gcs ▁d ron olog',
       '▁summ ari ▁calc ul ▁dist anc ▁descri pt ▁given ▁two ▁co ordin ▁co ordin ▁system ▁shall ▁comput ▁dist anc',
       '▁summ ari ▁one ▁instanc ▁reg ist ▁drone ▁may ▁activ ▁time ▁descri pt ▁u av activ ▁man ag ▁shall ▁ens ur ▁one ▁instanc ▁reg ist ▁drone ▁activ ▁time',
       '▁summ ari ▁display ▁activ ▁rout ▁descri pt ▁real ▁time ▁flight ▁shall ▁display ▁current ▁activ ▁flight ▁plan ▁map',
       '▁summ ari ▁flight ▁rout ▁def in ▁waypoint ▁descri pt ▁flight ▁rout ▁man ag ▁shall ▁def in ▁flight ▁rout ▁order ▁sequ enc ▁waypoint ▁first ▁waypoint ▁rep res ▁first ▁target ▁loc at ▁final ▁waypoint ▁rep res ▁final ▁target ▁loc at',
       '▁summ ari ▁delet ▁rout ▁descri pt ▁rout ▁creation ▁shall ▁allow ▁user ▁delet ▁rout',
       '▁summ ari ▁assign ▁new ▁flight ▁plan ▁upon ▁complet ▁previous ▁flight ▁descri pt ▁u av ▁pend ▁flight ▁plan ▁reach ▁final ▁waypoint ▁current ▁flight ▁plan ▁sing l ▁u av flight ▁plan ▁sched ul ▁shall ▁execut ▁next ▁assign ▁flight ▁plan',
       '▁summ ari ▁flight ▁rout ▁persist ▁descri pt ▁flight ▁rout ▁man ag ▁shall ▁persist ▁flight ▁rout',
       '▁summ ari ▁u av ▁ident if ▁descri pt ▁veh ic l ▁core ▁shall ▁assign ▁uniqu ▁activ ▁u av',
       '▁summ ari ▁publish ▁monitor ▁mess ag ▁descri pt ▁d ron olog ▁run tim ▁monitor ▁shall ▁abl ▁rece iv ▁mess ag ▁d ron olog ▁com pon',
       '▁summ ari ▁co ordin ▁system ▁convers ▁descri pt ▁request ▁co ordin ▁system ▁shall ▁transform ▁co ordin ▁altern ▁format',
       '▁summ ari ▁remov ▁plan ▁flight ▁descri pt ▁request ▁sing l ▁u av flight ▁plan ▁sched ul ▁shall ▁unassign ▁flight ▁plan ▁assign ▁u av ▁await ▁execut',
       '▁summ ari ▁display ▁map ▁descri pt ▁real ▁time ▁flight ▁load ▁map ▁shall ▁display',
       '▁summ ari ▁rout ▁creation ▁mod if ▁descri pt ▁rout ▁creation ▁shall ▁allow ▁user ▁cre at ▁mod ifi ▁rout',
       '▁summ ari ▁remov ▁pend ▁plan ▁return ▁home ▁descri pt ▁u av ▁current ▁flight ▁cancel ▁sing l ▁u av flight ▁plan ▁sched ul ▁shall ▁turn ▁cancel ▁sched ul ▁flight ▁plan ▁u av',
       '▁summ ari ▁connect ▁gcs ▁d ron olog ▁via ▁middle war ▁descri pt ▁gcs middle war ▁shall ▁hand l ▁multi pl ▁gcs',
       '▁summ ari ▁load ▁default ▁co ordin ▁descri pt ▁load ▁map ▁view ▁shall ▁posit ▁pre ▁def in ▁loc at',
       '▁summ ari ▁u av ▁mess ag ▁descri pt ▁gcs middle war ▁shall ▁hand l ▁state ▁mess ag ▁monitor ▁mess ag ▁mode ▁chang ▁mess ag ▁rece iv ▁gcs',
       '▁summ ari ▁spec ifi ▁takeoff ▁alt itud ▁descri pt ▁flight ▁rout ▁requ ir ▁custom ▁takeoff ▁alt itud ▁differ ▁system ▁default ▁takeoff ▁alt itud ▁shall ▁spec ifi ▁flight ▁rout',
       '▁summ ari ▁u av ▁flight ▁plan ▁execut ▁descri pt ▁sing l ▁u av flight ▁plan ▁sched ul ▁shall ▁execut ▁one ▁flight ▁plan ▁time ▁u av',
       '▁summ ari ▁display ▁activ ▁u av ▁descri pt ▁real ▁time ▁flight ▁shall ▁display ▁name ▁status ▁current ▁activ ▁u av',
       '▁summ ari ▁follow ▁u av ▁descri pt ▁real ▁time ▁flight ▁shall ▁allow ▁user ▁follow ▁one ▁multi pl ▁u av ▁map',
       '▁summ ari ▁mod ifi ▁assign ▁rout ▁descri pt ▁user ▁may ▁reorder ▁rout ▁remov ▁flight ▁plan ▁assign ▁u av ▁long ▁flight ▁start ▁execut',
       '▁summ ari ▁assign ▁rout ▁descri pt ▁rout ▁assign ▁shall ▁provid ▁mean ▁select ▁exist ▁rout ▁assign ▁u av',
       '▁summ ari ▁u av ▁oper ▁descri pt ▁real ▁time ▁flight ▁shall ▁allow ▁user ▁appl i ▁flight ▁oper ▁one ▁select ▁u av',
       '▁summ ari ▁display ▁list ▁exist ▁rout ▁descri pt ▁rout ▁creation ▁load ▁list ▁exist ▁rout ▁shall ▁display',
       '▁summ ari ▁emer g ▁oper ▁descri pt ▁real ▁time ▁flight ▁shall ▁allow ▁user ▁perform ▁emer g ▁oper ▁hover ▁multi pl ▁u av ▁send ▁multi pl ▁u av ▁home ▁group ▁u av',
       '▁summ ari ▁middle war ▁support ▁rout ▁assign ▁u av ▁descri pt ▁u im iddle war ▁shall ▁en abl ▁exist ▁rout ▁assign ▁activ ▁u av',
       '▁summ ari ▁hover ▁complet ▁flight ▁descri pt ▁u av ▁pend ▁flight ▁plan ▁reach ▁final ▁waypoint ▁current ▁flight ▁plan ▁sing l ▁u av flight ▁plan ▁sched ul ▁shall ▁not ifi ▁u av ▁hover ▁place',
       '▁summ ari ▁pre def in ▁flight ▁pattern ▁descri pt ▁mission ▁planner ▁shall ▁man ag ▁pre def in ▁flight ▁pattern',
       '▁summ ari ▁simul ▁land ▁descri pt ▁given ▁land ▁command ▁intern ▁simul ▁shall ▁move ▁u av ▁ground ▁alt itud ▁correspond ▁current ▁long itud ▁lat itud',
       '▁summ ari ▁u av ▁state ▁transit ▁descri pt ▁request ▁veh ic l ▁core ▁shall ▁shall ▁transit ▁u av ▁state ▁accord ▁allow ▁state ▁transit ▁depict ▁u av ▁state ▁transit ▁diagram',
       '▁summ ari ▁simul ▁batter i ▁descri pt ▁intern ▁simul ▁shall ▁approxim ▁state ▁batter i',
       '▁summ ari ▁middle war ▁provid ▁support ▁mod ifi ▁flight ▁rout ▁descri pt ▁u im iddle war ▁shall ▁en abl ▁creation ▁mod if ▁flight ▁rout',
       '▁summ ari ▁simul ▁goto ▁descri pt ▁given ▁goto ▁command ▁intern ▁simul ▁shall ▁up dat ▁loc at ▁u av ▁increment ▁simul ▁step ▁size ▁meter ▁move ▁toward ▁target ▁dest in ▁dest in ▁reach',
       '▁summ ari ▁simul ▁takeoff ▁descri pt ▁given ▁takeoff ▁command ▁intern ▁simul ▁shall ▁move ▁u av ▁takeoff ▁alt itud ▁correspond ▁current ▁long itud ▁lat itud',
       '▁summ ari ▁waypoint ▁definit ▁descri pt ▁waypoint ▁shall ▁spec ifi ▁use ▁co ordin ▁includ ▁long itud ▁lat itud ▁alt itud',
       '▁summ ari ▁flight ▁plan ▁sched ul ▁descri pt ▁request ▁sing l ▁u av flight ▁plan ▁sched ul ▁shall ▁sched ul ▁rout ▁execut',
       '▁summ ari ▁middle war ▁forward ▁command ▁client ▁d ron olog ▁descri pt ▁u im iddle war ▁accept ▁command ▁forward ▁d ron olog',
       '▁summ ari ▁middle war ▁list ▁current ▁activ ▁u av ▁descri pt ▁u im iddle war ▁shall ▁provid ▁list ▁activ ▁u av',
       '▁summ ari ▁return ▁home ▁without ▁detour ▁descri pt ▁return ▁home ▁command ▁iss u ▁flight ▁man ag ▁shall ▁return ▁u av ▁origin ▁launch ▁loc at ▁without ▁iss u ▁add it ▁waypoint ▁rout ▁command',
       '▁summ ari ▁de activ ▁physic ▁u av ▁descri pt ▁u av ▁de activ ▁u av activ ▁man ag ▁shall ▁cancel ▁current ▁sched ul ▁flight ▁plan',
       '▁summ ari ▁cancel ▁mission ▁descri pt ▁request ▁mission ▁current ▁activ ▁mission ▁planner ▁shall ▁cancel ▁activ ▁mission',
       '▁summ ari ▁autom at ▁flight ▁plan ▁assign ▁descri pt ▁sched ul ▁flight ▁manual ▁assign ▁u av ▁sing l ▁u av flight ▁plan ▁sched ul ▁shall ▁assign ▁rout ▁autom at ▁u av',
       '▁packag ▁edu ▁d ron olog ▁servic ▁ext ens ▁mission plan ▁import ▁java ▁io except ▁import ▁java ▁util ▁hash ▁map ▁import ▁java ▁util ▁map ▁import ▁java ▁util ▁map ▁ent ri ▁import ▁org ▁json ▁json except ▁import ▁edu ▁d ron olog ▁core ▁d ron olog ▁constant ▁import ▁edu ▁d ron olog ▁core ▁co ordin ▁l la ▁co ordin ▁import ▁edu ▁d ron olog ▁core ▁veh ic l ▁iu av pro xi ▁import ▁edu ▁d ron olog ▁servic ▁core ▁util ▁d ron olog ▁servic ▁except ▁import ▁edu ▁d ron olog ▁servic ▁ext ens ▁mission plan ▁mission ▁execut ▁except ▁import ▁edu ▁d ron olog ▁servic ▁ext ens ▁mission plan ▁plan ▁i execut ▁mission ▁plan ▁import ▁edu ▁d ron olog ▁servic ▁ext ens ▁mission plan ▁plan ▁mission ▁util ▁import ▁edu ▁d ron olog ▁servic ▁ext ens ▁mission plan ▁plan ▁u av miss ▁plan ▁import ▁edu ▁d ron olog ▁servic ▁ext ens ▁mission plan ▁sync ▁synchron ▁man ag ▁import ▁edu ▁d ron olog ▁servic ▁ext ens ▁mission plan ▁task ▁task ▁factor i ▁import ▁edu ▁d ron olog ▁servic ▁instanc ▁drones et up ▁drone ▁setup ▁servic ▁import ▁net ▁log ▁i logg ▁import ▁net ▁log ▁logger ▁provid ▁man ag ▁mission ▁plan ▁mission ▁plan ▁one ▁code ▁full ▁mission ▁plan ▁code ▁instanc ▁one ▁code ▁u av miss ▁plan ▁code ▁instanc ▁u av ▁mission ▁plan ▁u av ▁individ u ▁mission ▁plan ▁compos ▁mission ▁task ▁ent ir ▁mission ▁plan ▁load ▁thread ▁cre at ▁check ▁individ u ▁u av miss ▁plan ▁determin ▁start ▁next ▁task ▁author ▁j ane ▁cl eland ▁hu ang ▁deprec ▁public ▁class ▁full ▁mission ▁plan ▁implement ▁i execut ▁mission ▁plan ▁privat ▁static ▁final ▁i logg ▁logger ▁logger ▁provid ▁get ▁logger ▁full ▁mission ▁plan ▁class ▁privat ▁map ▁string ▁u av miss ▁plan ▁u av ▁mission ▁plan ▁privat ▁synchron ▁man ag ▁synch ▁point ▁mgr ▁privat ▁string ▁mission ▁construct ▁co ordin ▁mission ▁instanc ▁mission ▁consist ▁one ▁u av ▁set ▁assign ▁task ▁synchron ▁point ▁param ▁mission ▁public ▁full ▁mission ▁plan ▁string ▁mission ▁mission ▁mission ▁u av ▁mission ▁plan ▁new ▁hash ▁map ▁synch ▁point ▁mgr ▁synchron ▁man ag ▁get ▁instanc ▁load ▁mission ▁json ▁file ▁current ▁hard ▁code ▁param ▁mission ▁throw ▁mission ▁execut ▁except ▁privat ▁void ▁load ▁mission ▁string ▁mission ▁throw ▁mission ▁execut ▁except ▁json miss ▁plan ▁reader ▁json ▁reader ▁new ▁json miss ▁plan ▁reader ▁tri ▁json ▁reader ▁pars ▁mission ▁mission ▁catch ▁io except ▁json except ▁throw ▁new ▁mission ▁execut ▁except ▁get ▁mess ag ▁add ▁add it ▁u av ▁mission ▁plan ▁cre at ▁code ▁u av miss ▁task ▁code ▁instanc ▁pass ▁refer ▁code ▁synch ▁point ▁mgr ▁code ▁param ▁u av ▁u av ▁throw ▁mission ▁execut ▁except ▁public ▁void ▁add ▁u av ▁string ▁u av ▁throw ▁mission ▁execut ▁except ▁u av miss ▁plan ▁plan ▁new ▁u av miss ▁plan ▁u av ▁synch ▁point ▁mgr ▁u av ▁mission ▁plan ▁contain ▁key ▁u av ▁throw ▁new ▁mission ▁execut ▁except ▁mission ▁plan ▁u av ▁u av ▁al read i ▁def in ▁"); ▁u av ▁mission ▁plan ▁put ▁u av ▁plan ▁public ▁void ▁remov ▁u av ▁string ▁u av ▁u av ▁mission ▁plan ▁remov ▁u av ▁/** ▁assign ▁task ▁spec if ▁u av ▁param ▁u av ▁u av ▁ident ifi ▁param ▁task ▁task ▁perform ▁rout ▁waypoint ▁synchron ▁flight ▁pattern ▁param ▁task ▁task ▁spec if ▁spec if ▁waypoint ▁rout ▁name ▁etc ▁throw ▁mission ▁execut ▁except ▁public ▁void ▁add ▁task ▁string ▁u av ▁string ▁task ▁string ▁task ▁object ▁... ▁param ▁throw ▁mission ▁execut ▁except ▁u av miss ▁plan ▁plan ▁u av ▁mission ▁plan ▁valu ▁( )) ▁plan ▁get ▁u av ▁( ). ▁equal ▁u av ▁plan ▁add ▁task ▁task ▁factor i ▁get ▁task ▁task ▁u av ▁task ▁param ▁synch ▁point ▁mgr ▁return ▁throw ▁new ▁mission ▁execut ▁except ▁u av miss ▁plan ▁u av ▁avail ▁! "); ▁overrid ▁public ▁boolean ▁mission ▁activ ▁u av miss ▁plan ▁plan ▁u av ▁mission ▁plan ▁valu ▁( )) ▁plan ▁task ▁( )) ▁return ▁true ▁return ▁fals ▁/** ▁build ▁synch ▁point ▁privat ▁void ▁build ▁synch ▁point ▁u av ▁mission ▁plan ▁u av ▁plan ▁plan ▁build ▁synch ▁point ▁( ); ▁}); ▁/** ▁activ ▁next ▁task ▁u av ▁mission ▁un finish ▁activ ▁task ▁throw ▁mission ▁execut ▁except ▁overrid ▁public ▁void ▁check ▁activ ▁task ▁throw ▁mission ▁execut ▁except ▁u av miss ▁plan ▁plan ▁u av ▁mission ▁plan ▁valu ▁( )) ▁plan ▁activ ▁task ▁( )) ▁plan ▁activ ▁next ▁task ▁( ); ▁/** ▁expand ▁flight ▁pattern ▁task ▁co ordin ▁take ▁co ordin ▁land ▁throw ▁mission ▁execut ▁except ▁privat ▁void ▁expand ▁task ▁throw ▁mission ▁execut ▁except ▁u av miss ▁plan ▁plan ▁u av ▁mission ▁plan ▁valu ▁( )) ▁plan ▁expand ▁task ▁list ▁( ); ▁public ▁void ▁build ▁throw ▁mission ▁execut ▁except ▁load ▁mission ▁mission ▁expand ▁task ▁( ); ▁build ▁synch ▁point ▁( ); ▁synch ▁point ▁mgr ▁activ ▁synch ▁point ▁( ); ▁run ▁pre ▁check ▁( ); ▁privat ▁void ▁run ▁pre ▁check ▁throw ▁mission ▁execut ▁except ▁ent ri ▁string ▁u av miss ▁plan ▁u av ▁mission ▁plan ▁ent ri ▁set ▁( )) ▁check ▁dist anc ▁get ▁key ▁( ), ▁get ▁valu ▁( )); ▁privat ▁void ▁check ▁dist anc ▁string ▁u av id ▁u av miss ▁plan ▁plan ▁throw ▁mission ▁execut ▁except ▁l la ▁co ordin ▁co ordin ▁plan ▁get ▁start ▁rout ▁waypoint ▁( ); ▁iu av pro xi ▁u av ▁null ▁co ordin ▁null ▁throw ▁new ▁mission ▁execut ▁except ▁error ▁retriev ▁first ▁waypoint ▁u av ▁u av id ▁"\'" ); ▁tri ▁u av ▁drone ▁setup ▁servic ▁get ▁instanc ▁( ). ▁get ▁activ ▁u av ▁u av id ▁catch ▁d ron olog ▁servic ▁except ▁throw ▁new ▁mission ▁execut ▁except ▁get ▁mess ag ▁( )); ▁doub l ▁dist anc ▁first ▁waypoint ▁u av ▁get ▁co ordin ▁( ). ▁dist anc ▁co ordin ▁dist anc ▁first ▁waypoint ▁d ron olog ▁constant ▁throw ▁new ▁mission ▁execut ▁except ▁dist anc ▁first ▁waypoint ▁exceed ▁maximum ▁saf eti ▁dist anc ▁dist anc ▁first ▁waypoint ▁"); ▁logger ▁info ▁pre check ▁pass ▁dist anc ▁first ▁waypoint ▁dist anc ▁first ▁waypoint ▁overrid ▁public ▁void ▁cancel ▁mission ▁logger ▁mission ▁error ▁mission ▁cancel ▁! "); ▁u av miss ▁plan ▁plan ▁u av ▁mission ▁plan ▁valu ▁( )) ▁string ▁u av id ▁plan ▁get ▁u av ▁( ); ▁mission ▁util ▁stop ▁u av ▁u av id',
       '▁packag ▁edu ▁d ron olog ▁servic ▁ext ens ▁mission plan ▁import ▁java ▁file ▁found ▁except ▁import ▁java ▁io except ▁import ▁java ▁util ▁list ▁import ▁java ▁util ▁map ▁import ▁org ▁json ▁json except ▁import ▁com ▁goog l ▁gson ▁gson ▁import ▁edu ▁d ron olog ▁servic ▁ext ens ▁mission plan ▁mission ▁execut ▁except ▁simpl ▁json ▁reader ▁convert ▁json ▁string ▁link ▁full ▁mission ▁plan ▁object ▁author ▁j ane ▁cl eland ▁hu ang ▁suppress ▁warn ▁raw typ ▁public ▁class ▁json miss ▁plan ▁reader ▁full ▁mission ▁plan ▁co ordin ▁mission ▁string ▁file ▁name ▁public ▁json miss ▁plan ▁reader ▁full ▁mission ▁plan ▁co ordin ▁mission ▁co ordin ▁mission ▁co ordin ▁mission ▁public ▁void ▁pars ▁mission ▁string ▁content ▁throw ▁file ▁found ▁except ▁io except ▁json except ▁mission ▁execut ▁except ▁pars ▁input ▁file ▁object ▁obj ▁new ▁json pars ▁pars ▁content ▁map ▁valu ▁map ▁new ▁gson ▁json ▁content ▁map ▁class ▁list ▁plan ▁list ▁valu ▁map ▁get ▁plan ▁object ▁object ▁plan ▁map ▁map ▁object ▁string ▁u av id ▁string ▁get ▁co ordin ▁mission ▁add ▁u av ▁u av id ▁list ▁task ▁list ▁get ▁task ▁object ▁task ▁task ▁pars ▁task ▁task ▁u av id ▁privat ▁void ▁pars ▁task ▁object ▁item ▁string ▁u av id ▁throw ▁mission ▁execut ▁except ▁map ▁jsn ▁object ▁map ▁item ▁string ▁task ▁string ▁jsn ▁object ▁get ▁task ▁string ▁task ▁task ▁string ▁jsn ▁object ▁get ▁name ▁string ▁dur at ▁string ▁jsn ▁object ▁get ▁dur at ▁dur at ▁null ▁co ordin ▁mission ▁add ▁task ▁u av id ▁task ▁task ▁dur at ▁els ▁co ordin ▁mission ▁add ▁task ▁u av id ▁task ▁task',
       '▁packag ▁edu ▁d ron olog ▁servic ▁core ▁util ▁author ▁m ichael ▁v ier haus ▁public ▁class ▁servic ▁public ▁static ▁final ▁string ▁servic ▁fl igh rout ▁route plan ▁public ▁static ▁final ▁string ▁servic ▁simul ▁simul ▁public ▁static ▁final ▁string ▁servic ▁remot ▁remot ▁public ▁static ▁final ▁string ▁servic ▁flight man ag ▁flight man ag ▁public ▁static ▁final ▁string ▁servic ▁drones et up ▁drones et up ▁public ▁static ▁final ▁string ▁servic ▁registr ▁d ron ere g istr ▁public ▁static ▁final ▁string ▁servic ▁equip ▁type ▁registr ▁equip dron ere g istr ▁public ▁static ▁final ▁string ▁servic ▁typ ere g istr ▁d ron et yp ere g istr ▁public ▁static ▁final ▁string ▁servic ▁mission plan ▁mission plan ▁public ▁static ▁final ▁string ▁servic ▁are am ap ▁are am ap',
       '▁packag ▁edu ▁d ron olog ▁core ▁veh ic l ▁intern ▁import ▁com ▁goog l ▁common ▁util ▁conc ur r ▁rate ▁limit ▁import ▁edu ▁d ron olog ▁core ▁collision avoid ▁drone ▁snapshot ▁intern ▁import ▁edu ▁d ron olog ▁core ▁co ordin ▁l la ▁co ordin ▁import ▁edu ▁d ron olog ▁core ▁except ▁drone ▁except ▁import ▁edu ▁d ron olog ▁core ▁except ▁flight ▁zone ▁except ▁import ▁edu ▁d ron olog ▁core ▁simul ▁if light ▁simul ▁import ▁edu ▁d ron olog ▁core ▁simul ▁simul ▁factor i ▁import ▁edu ▁d ron olog ▁core ▁veh ic l ▁abstract ▁drone ▁import ▁edu ▁d ron olog ▁core ▁veh ic l ▁id ron ▁import ▁edu ▁d ron olog ▁core ▁veh ic l ▁command ▁abstract ▁drone ▁command ▁import ▁edu ▁d ron olog ▁util ▁null ▁util ▁import ▁net ▁log ▁i logg ▁import ▁net ▁log ▁logger ▁provid ▁import ▁org ▁ap ach ▁common ▁math ▁geomet ri ▁euclidean ▁thre ed ▁vector ▁represent ▁virtual ▁u av ▁control ▁intern ▁simul ▁author ▁j ane ▁cl eland ▁hu ang ▁public ▁class ▁virtual ▁drone ▁extend ▁abstract ▁drone ▁implement ▁id ron ▁privat ▁static ▁final ▁i logg ▁logger ▁logger ▁provid ▁get ▁logger ▁virtual ▁drone ▁class ▁if light ▁simul ▁simul ▁construct ▁drone ▁without ▁spec ifi ▁current ▁posit ▁use ▁physic ▁drone ▁later ▁posit ▁status ▁acqu ir ▁drone ▁param ▁dr n ▁name ▁public ▁virtual ▁drone ▁string ▁dr n ▁name ▁super ▁dr n ▁name ▁simul ▁simul ▁factor i ▁get ▁simul ▁overrid ▁public ▁void ▁take ▁doub l ▁target ▁alt itud ▁throw ▁flight ▁zone ▁except ▁simul ▁start ▁batter i ▁drain ▁drone ▁status ▁up dat ▁batter i ▁level ▁simul ▁get ▁vol tag ▁need ▁super ▁set ▁co ordin ▁drone ▁status ▁get ▁lat itud ▁drone ▁status ▁get ▁long itud ▁target ▁alt itud ▁tri ▁thread ▁sleep ▁new ▁doub l ▁target ▁alt itud ▁int ▁valu ▁simul ▁catch ▁interrupt ▁except ▁logger ▁error ▁overrid ▁public ▁void ▁fl i ▁l la ▁co ordin ▁target ▁co ordin ▁doub l ▁speed ▁null ▁util ▁check ▁null ▁target ▁co ordin ▁logger ▁info ▁fl i ▁target ▁co ordin ▁string ▁simul ▁set ▁flight ▁path ▁current ▁posit ▁target ▁co ordin ▁overrid ▁public ▁void ▁land ▁throw ▁flight ▁zone ▁except ▁tri ▁thread ▁sleep ▁simul ▁check ▁point ▁simul ▁stop ▁batter i ▁drain ▁catch ▁throw abl ▁logger ▁error ▁overrid ▁public ▁doub l ▁get ▁batter i ▁status ▁drone ▁status ▁up dat ▁batter i ▁level ▁simul ▁get ▁vol tag ▁return ▁simul ▁get ▁vol tag ▁( ); ▁rate ▁limit ▁limit ▁rate ▁limit ▁cre at ▁overrid ▁public ▁boolean ▁move ▁doub l ▁also ▁need ▁think ▁non ▁virtual ▁get ▁batter i ▁status ▁( ); ▁limit ▁acqu ir ▁( ); ▁boolean ▁move ▁status ▁simul ▁move ▁drone ▁status ▁up dat ▁co ordin ▁get ▁lat itud ▁( ), ▁get ▁long itud ▁( ), ▁get ▁alt itud ▁( )); ▁drone ▁collect ▁status ▁get ▁instanc ▁( ). ▁test ▁status ▁( ); ▁return ▁move ▁status ▁overrid ▁public ▁void ▁set ▁vol tag ▁check ▁point ▁simul ▁check ▁point ▁( ); ▁overrid ▁public ▁boolean ▁dest in ▁reach ▁int ▁dist anc ▁move ▁per ▁time ▁step ▁return ▁simul ▁dest in ▁reach ▁dist anc ▁move ▁per ▁time ▁step ▁overrid ▁public ▁void ▁set ▁ground ▁speed ▁doub l ▁speed ▁todo ▁auto ▁gener at ▁method ▁stub ▁overrid ▁public ▁void ▁set ▁vel oc ▁doub l ▁doub l ▁doub l ▁todo ▁auto ▁gener at ▁method ▁stub ▁overrid ▁public ▁void ▁send ▁command ▁abstract ▁drone ▁command ▁command ▁throw ▁drone ▁except ▁todo ▁auto ▁gener at ▁method ▁stub ▁overrid ▁public ▁void ▁resend ▁command ▁todo ▁auto ▁gener at ▁method ▁stub ▁overrid ▁public ▁drone ▁snapshot ▁intern ▁get ▁latest ▁drone ▁snapshot ▁todo ▁get ▁vel oc ▁att itud ▁valu ▁vector 3 d ▁vel oc ▁new ▁vector 3 d ▁vector 3 d ▁att itud ▁new ▁vector 3 d ▁return ▁new ▁drone ▁snapshot ▁intern ▁drone ▁name ▁drone ▁status ▁get ▁co ordin ▁( ), ▁vel oc ▁att itud',

In [37]:
df_all_system.reset_index(inplace=True)

In [38]:
#tst
df_all_system.loc[df_all_system['type'] == parameters['source_type']][parameters['system_path_config']['names']]

,ids,bpe128k
0,/Users/loganfecko/Desktop/Summer_Research/trac...,▁summ ari ▁log ▁gcs ▁relat ▁event ▁descri pt ▁...
1,/Users/loganfecko/Desktop/Summer_Research/trac...,▁summ ari ▁support ▁gcs ▁connect ▁u av ▁descri...
2,/Users/loganfecko/Desktop/Summer_Research/trac...,▁summ ari ▁manual ▁flight ▁plan ▁assign ▁descr...
3,/Users/loganfecko/Desktop/Summer_Research/trac...,▁summ ari ▁visit ▁waypoint ▁flight ▁plan ▁desc...
4,/Users/loganfecko/Desktop/Summer_Research/trac...,▁summ ari ▁establish ▁maximum ▁number ▁activ ▁...
5,/Users/loganfecko/Desktop/Summer_Research/trac...,▁summ ari ▁support ▁intern ▁simul ▁u av ▁descr...
6,/Users/loganfecko/Desktop/Summer_Research/trac...,▁summ ari ▁middle war ▁list ▁save ▁flight ▁rou...
7,/Users/loganfecko/Desktop/Summer_Research/trac...,▁summ ari ▁mission ▁plan ▁descri pt ▁mission ▁...
8,/Users/loganfecko/Desktop/Summer_Research/trac...,▁summ ari ▁log ▁flight ▁plan ▁relat ▁event ▁de...
9,/Users/loganfecko/Desktop/Summer_Research/trac...,▁summ ari ▁accept ▁mission ▁plan ▁descri pt ▁u...
10,/Users/loganfecko/Desktop/Summer_Research/trac...,▁summ ari ▁multi pl ▁map ▁type ▁descri pt ▁map...
11,/Users/loganfecko/Desktop/Summer_Research/trac...,▁summ ari ▁transmit ▁rout ▁assign ▁middle war ...
12,/Users/loganfecko/Desktop/Summer_Research/trac...,▁summ ari ▁monitor ▁mess ag ▁descri pt ▁d ron ...
13,/Users/loganfecko/Desktop/Summer_Research/trac...,▁summ ari ▁u av ▁command ▁descri pt ▁gcs middl...
14,/Users/loganfecko/Desktop/Summer_Research/trac...,▁summ ari ▁ground stat ▁middle war ▁commun ic ...
15,/Users/loganfecko/Desktop/Summer_Research/trac...,▁summ ari ▁calc ul ▁dist anc ▁descri pt ▁given...
16,/Users/loganfecko/Desktop/Summer_Research/trac...,▁summ ari ▁one ▁instanc ▁reg ist ▁drone ▁may ▁...
17,/Users/loganfecko/Desktop/Summer_Research/trac...,▁summ ari ▁display ▁activ ▁rout ▁descri pt ▁re...
18,/Users/loganfecko/Desktop/Summer_Research/trac...,▁summ ari ▁flight ▁rout ▁def in ▁waypoint ▁des...
19,/Users/loganfecko/Desktop/Summer_Research/trac...,▁summ ari ▁delet ▁rout ▁descri pt ▁rout ▁creat...
20,/Users/loganfecko/Desktop/Summer_Research/trac...,▁summ ari ▁assign ▁new ▁flight ▁plan ▁upon ▁co...
21,/Users/loganfecko/Desktop/Summer_Research/trac...,▁summ ari ▁flight ▁rout ▁persist ▁descri pt ▁f...
22,/Users/loganfecko/Desktop/Summer_Research/trac...,▁summ ari ▁u av ▁ident if ▁descri pt ▁veh ic l...
23,/Users/loganfecko/Desktop/Summer_Research/trac...,▁summ ari ▁publish ▁monitor ▁mess ag ▁descri p...
24,/Users/loganfecko/Desktop/Summer_Research/trac...,▁summ ari ▁co ordin ▁system ▁convers ▁descri p...
25,/Users/loganfecko/Desktop/Summer_Research/trac...,▁summ ari ▁remov ▁plan ▁flight ▁descri pt ▁req...
26,/Users/loganfecko/Desktop/Summer_Research/trac...,▁summ ari ▁display ▁map ▁descri pt ▁real ▁time...
27,/Users/loganfecko/Desktop/Summer_Research/trac...,▁summ ari ▁rout ▁creation ▁mod if ▁descri pt ▁...
28,/Users/loganfecko/Desktop/Summer_Research/trac...,▁summ ari ▁remov ▁pend ▁plan ▁return ▁home ▁de...
29,/Users/loganfecko/Desktop/Summer_Research/trac...,▁summ ari ▁connect ▁gcs ▁d ron olog ▁via ▁midd...
30,/Users/loganfecko/Desktop/Summer_Research/trac...,▁summ ari ▁load ▁default ▁co ordin ▁descri pt ...
31,/Users/loganfecko/Desktop/Summer_Research/trac...,▁summ ari ▁u av ▁mess ag ▁descri pt ▁gcs middl...
32,/Users/loganfecko/Desktop/Summer_Research/trac...,▁summ ari ▁spec ifi ▁takeoff ▁alt itud ▁descri...
33,/Users/loganfecko/Desktop/Summer_Research/trac...,▁summ ari ▁u av ▁flight ▁plan ▁execut ▁descri ...
34,/Users/loganfecko/Desktop/Summer_Research/trac...,▁summ ari ▁display ▁activ ▁u av ▁descri pt ▁re...
35,/Users/loganfecko/Desktop/Summer_Research/trac...,▁summ ari ▁follow ▁u av ▁descri pt ▁real ▁time...
36,/Users/loganfecko/Desktop/Summer_Research/trac...,▁summ ari ▁mod ifi ▁assign ▁rout ▁descri pt ▁u...
37,/Users/loganfecko/Desktop/Summer_Research/trac...,▁summ ari ▁assign ▁rout ▁descri pt ▁rout ▁assi...
38,/Users/loganfecko/Desktop/Summer_Research/trac...,▁summ ari ▁u av ▁oper ▁descri pt ▁real ▁time ▁...
39,/Users/loganfecko/Desktop/Summer_Research/trac...,▁summ ari ▁display ▁list ▁exist ▁rout ▁descri ...
40,/Users/loganfecko/Desktop/Summer_Research/trac...,▁summ ari ▁emer g ▁oper ▁descri pt ▁real ▁time...
41,/Users/loganfecko/Desktop/Summer_Research/trac...,▁summ ari ▁middle war ▁support ▁rout ▁assign ▁...
42,/Users/loganfecko/Desktop/Summer_Research/trac...,▁summ ari ▁hover ▁complet ▁flight ▁descri pt ▁...
43,/Users/loganfecko/Desktop/Summer_Research/trac...,▁summ ari ▁pre def in ▁flight ▁pattern ▁descri...
44,/Users/loganfecko/Desktop/Summer_Research/trac...,▁summ ari ▁simul ▁land ▁descri pt ▁given ▁land...
45,/Users/loganfecko/Desktop/Summer_Research/trac...,▁summ ari ▁u av ▁state ▁transit ▁descri pt ▁re...
46,/Users/loganfecko/Desktop/Summer_Research/trac...,▁summ ari ▁simul ▁batter i ▁descri pt ▁intern ...
47,/Users/loganfecko/Desktop/Summer_Research/trac...,▁summ ari ▁middle war ▁provid ▁support ▁mod if...
48,/Users/loganfecko/Desktop/Summer_Research/trac...,▁summ ari ▁simul ▁goto ▁descri pt ▁given ▁goto...
49,/Users/loganfecko/Desktop/Summer_Research/trac...,▁summ ari ▁simul ▁takeoff ▁descri pt ▁given ▁t...
50,/Users/loganfecko/Desktop/Summer_Research/trac...,▁summ ari ▁waypoint ▁definit ▁descri pt ▁waypo...
51,/Users/loganfecko/Desktop/Summer_Research/trac...,▁summ ari ▁flight ▁plan ▁sched ul ▁descri pt ▁...
52,/Users/loganfecko/Desktop/Summer_Research/trac...,▁summ ari ▁middle war ▁forward ▁command ▁clien...
53,/Users/loganfecko/Desktop/Summer_Research/trac...,▁summ ari ▁middle war ▁list ▁current ▁activ ▁u...
54,/Users/loganfecko/Desktop/Summer_Research/trac...,▁summ ari ▁return ▁home ▁without ▁detour ▁desc...
55,/Users/loganfecko/Desktop/Summer_Research/trac...,▁summ ari ▁de activ ▁physic ▁u av ▁descri pt ▁...
56,/Users/loganfecko/Desktop/Summer_Research/trac...,▁summ ari ▁cancel ▁mission ▁descri pt ▁request...
57,/Users/loganfecko/Desktop/Summer_Research/trac...,▁summ ari ▁autom at ▁flight ▁plan ▁assign ▁des...

In [39]:
df_all_system.loc[df_all_system['type'] == parameters['target_type']][parameters['system_path_config']['names']]

,ids,bpe128k
58,/Users/loganfecko/Desktop/Summer_Research/trac...,▁packag ▁edu ▁d ron olog ▁servic ▁ext ens ▁mis...
59,/Users/loganfecko/Desktop/Summer_Research/trac...,▁packag ▁edu ▁d ron olog ▁servic ▁ext ens ▁mis...
60,/Users/loganfecko/Desktop/Summer_Research/trac...,▁packag ▁edu ▁d ron olog ▁servic ▁core ▁util ▁...
61,/Users/loganfecko/Desktop/Summer_Research/trac...,▁packag ▁edu ▁d ron olog ▁core ▁veh ic l ▁inte...
62,/Users/loganfecko/Desktop/Summer_Research/trac...,▁packag ▁edu ▁d ron olog ▁servic ▁ext ens ▁mis...
...,...,...
237,/Users/loganfecko/Desktop/Summer_Research/trac...,▁packag ▁edu ▁d ron olog ▁core ▁veh ic l ▁comm...
238,/Users/loganfecko/Desktop/Summer_Research/trac...,▁packag ▁edu ▁d ron olog ▁va adin ▁active flig...
239,/Users/loganfecko/Desktop/Summer_Research/trac...,▁packag ▁edu ▁d ron olog ▁va adin ▁active flig...
240,/Users/loganfecko/Desktop/Summer_Research/trac...,▁packag ▁edu ▁d ron olog ▁servic ▁ext ens ▁mis...
241,/Users/loganfecko/Desktop/Summer_Research/trac...,▁packag ▁edu ▁d ron olog ▁core ▁veh ic l ▁inte...

### Defining BasicSequenceVectorization

In [40]:
#tst
print(list(VectorizationType), list(DistanceMetric), list(SimilarityMetric), list(LinkType))

[<VectorizationType.word2vec: 1>, <VectorizationType.doc2vec: 2>, <VectorizationType.vsm2vec: 3>] [<DistanceMetric.WMD: 1>, <DistanceMetric.COS: 2>, <DistanceMetric.SCM: 3>, <DistanceMetric.EUC: 4>, <DistanceMetric.MAN: 5>] [<SimilarityMetric.WMD_sim: 1>, <SimilarityMetric.COS_sim: 2>, <SimilarityMetric.SCM_sim: 3>, <SimilarityMetric.EUC_sim: 4>, <SimilarityMetric.MAN_sim: 5>, <SimilarityMetric.Pearson: 6>] [<LinkType.req2tc: 1>, <LinkType.req2src: 2>, <LinkType.issue2src: 3>, <LinkType.pr2src: 4>]

In [41]:
#export
class BasicSequenceVectorization():
    '''Implementation of the class sequence-vanilla-vectorization other classes can inheritance this one'''
    def __init__(self, params):
                
        self.params = params
        self.df_nonground_link = None
        self.df_ground_link = None
        self.prep = ConventionalPreprocessing(params, bpe = False)
        
        self.df_all_system = pd.read_csv(
            params['system_path_config']['system_path'], 
            #names = params['system_path_config']['names'], #include the names into the files!!!
            header = 0, 
            #index_col = 0, 
            sep = params['system_path_config']['sep'] 
        )
        
        #self.df_source = pd.read_csv(params['source_path'], names=['ids', 'text'], header=None, sep=' ')
        #self.df_target = pd.read_csv(params['target_path'], names=['ids', 'text'], header=None, sep=' ')
        self.df_source = self.df_all_system.loc[self.df_all_system['type'] == params['source_type']][params['system_path_config']['names']]
        self.df_target = self.df_all_system.loc[self.df_all_system['type'] == params['target_type']][params['system_path_config']['names']]
        
        #NA verification
        tag = parameters['system_path_config']['names'][1]
        self.df_source[tag] = self.df_source[tag].fillna("")
        self.df_target[tag] = self.df_target[tag].fillna("")
        
        if params['system_path_config']['prep'] == Preprocessing.conv: #if conventional preprocessing
            self.documents = [doc.split() for doc in self.df_all_system[self.df_all_system[tag].notnull()][tag].values] #Preparing Corpus
            self.dictionary = corpora.Dictionary( self.documents ) #Preparing Dictionary
            logging.info("conventional preprocessing documents and dictionary")
            self.vocab = self.dictionary.token2id
        elif params['system_path_config']['prep'] == Preprocessing.bpe:
            from sentencepiece import SentencePieceProcessor
            sp = SentencePieceProcessor()
            sp.load(params['system_path_config']['bpe_model_path'])
            self.prep.sp_bpe = sp
            
            
            self.documents = [doc.split() for doc in self.df_all_system[tag].values]            
            self.dictionary = corpora.Dictionary( self.documents ) #Preparing Dictionary
            logging.info("bpe preprocessing documents and dictionary")
                
            ####INFO science params
            abstracted_vocab = [ set(doc) for doc in self.df_all_system[ 'bpe8k' ].values] #creation of sets
            abstracted_vocab = functools.reduce( lambda a,b : a.union(b), abstracted_vocab ) #union of sets
            self.vocab = {self.prep.sp_bpe.id_to_piece(id): 0 for id in range(self.prep.sp_bpe.get_piece_size())}
            dict_abs_vocab = { elem : 0 for elem in abstracted_vocab - set(self.vocab.keys()) } #Ignored vocab by BPE
            self.vocab.update(dict_abs_vocab) #Updating
        
        
        #This can be extended for future metrics <---------------------
        #TODO include mutual and join information
        self.dict_labels = {
            DistanceMetric.COS:[DistanceMetric.COS, SimilarityMetric.COS_sim],
            SimilarityMetric.Pearson:[SimilarityMetric.Pearson],
            DistanceMetric.EUC:[DistanceMetric.EUC, SimilarityMetric.EUC_sim],
            DistanceMetric.WMD:[DistanceMetric.WMD, SimilarityMetric.WMD_sim],
            DistanceMetric.SCM:[DistanceMetric.SCM, SimilarityMetric.SCM_sim],
            DistanceMetric.MAN:[DistanceMetric.MAN, SimilarityMetric.MAN_sim],
            EntropyMetric.MSI_I:[EntropyMetric.MSI_I, EntropyMetric.MSI_X],
            #EntropyMetric.MI:[EntropyMetric.JI, EntropyMetric.MI]
        }

        
    def ground_truth_processing(self, path_to_ground_truth = '', from_mappings = False):
        'Optional class when corpus has ground truth. This function create tuples of links'
        
        if from_mappings:
            df_mapping = pd.read_csv(self.params['path_mappings'], header = 0, sep = ',')
            ground_links = list(zip(df_mapping['id_pr'].astype(str), df_mapping['doc_id']))
        else:
            ground_truth = open(path_to_ground_truth,'r')
            #Organizing The Ground Truth under the given format
            ground_links = [ [(line.strip().split()[0], elem) for elem in line.strip().split()[1:]] for line in ground_truth]
            ground_links = functools.reduce(lambda a,b : a+b,ground_links) #reducing into one list
            assert len(ground_links) ==  len(set(ground_links)) #To Verify Redundancies in the file
        return ground_links
    
    def samplingLinks(self, sampling = False, samples = 10, basename = False):
        
        if basename:
            source = [os.path.basename(elem) for elem in self.df_source['ids'].values ] 
            target = [os.path.basename(elem) for elem in self.df_target['ids'].values ]
        else:
            source = self.df_source['ids'].values
            target = self.df_target['ids'].values

        if sampling:
            links = sample( list( product( source , target ) ), samples)
        else:
            links = list( product( source , target ))

        return links
    
    def cos_scipy(self, vector_v, vector_w):
        cos =  distance.cosine( vector_v, vector_w )
        return [cos, 1.-cos]
    
    def euclidean_scipy(self, vector_v, vector_w):
        dst = distance.euclidean(vector_v,vector_w)
        return [dst, 1./(1.+dst)] #Computing the inverse for similarity
    
    def manhattan_scipy(self, vector_v, vector_w):
        dst = distance.cityblock(vector_v,vector_w)
        n = len(vector_v)
        return [dst, 1./(1.+dst)] #Computing the inverse for similarity
    
    def pearson_abs_scipy(self, vector_v, vector_w):
        '''We are not sure that pearson correlation works well on doc2vec inference vectors'''
        #vector_v =  np.asarray(vector_v, dtype=np.float32)
        #vector_w =  np.asarray(vector_w, dtype=np.float32)
        logging.info("pearson_abs_scipy" + str(vector_v) + "__" + str(vector_w))
        corr, _ = pearsonr(vector_v, vector_w)
        return [abs(corr)] #Absolute value of the correlation
    

    def computeDistanceMetric(self, links, metric_list):
        '''Metric List Iteration''' 
        
        metric_labels = [ self.dict_labels[metric] for metric in metric_list] #tracking of the labels
        distSim = [[link[0], link[1], self.distance( metric_list, link )] for link in links] #Return the link with metrics
        distSim = [[elem[0], elem[1]] + elem[2] for elem in distSim] #Return the link with metrics
        
        return distSim, functools.reduce(lambda a,b : a+b, metric_labels)
    
    def ComputeDistanceArtifacts(self, metric_list, sampling = False , samples = 10, basename = False):
        '''Activates Distance and Similarity Computations
        @metric_list if [] then Computes All metrics
        @sampling is False by the default
        @samples is the number of samples (or links) to be generated'''
        links_ = self.samplingLinks( sampling, samples, basename )
        
        docs, metric_labels = self.computeDistanceMetric( metric_list=metric_list, links=links_) #checkpoints
        self.df_nonground_link = pd.DataFrame(docs, columns =[self.params['names'][0], self.params['names'][1]]+ metric_labels) #Transforming into a Pandas
        logging.info("Non-groundtruth links computed")
        pass 
    
    
    def SaveLinks(self, grtruth=False, sep=' ', mode='a'):
        timestamp = datetime.timestamp(datetime.now())
        path_to_link = self.params['saving_path'] + '['+ self.params['system'] + '-' + str(self.params['vectorizationType']) + '-' + str(self.params['linkType']) + '-' + str(grtruth) + '-{}].csv'.format(timestamp)
        
        if grtruth:
            self.df_ground_link.to_csv(path_to_link, header=True, index=True, sep=sep, mode=mode)
        else:
            self.df_nonground_link.to_csv(path_to_link, header=True, index=True, sep=sep, mode=mode)
        
        logging.info('Saving in...' + path_to_link)
        pass
    
    def findDistInDF(self, g_tuple, from_mappings=False, semeru_format=False):
        '''Return the index values of the matched mappings
        .eq is used for Source since it must match the exact code to avoid number substrings
        for the target, the substring might works fine'''

        if from_mappings:
            dist = self.df_ground_link.loc[(self.df_ground_link["Source"].eq(g_tuple[0]) ) & 
                 (self.df_ground_link["Target"].str.contains(g_tuple[1], regex=False))]
            logging.info('findDistInDF: from_mappings')
        elif semeru_format:
            dist = self.df_ground_link.loc[(self.df_ground_link["Source"].str.contains(g_tuple[0], regex=False) ) & 
                 (self.df_ground_link["Target"].str.contains(g_tuple[1], regex=False))]
            logging.info('findDistInDF: semeru_format')
        else:
            dist = self.df_ground_link[self.df_ground_link[self.params['names'][0]].str.contains( g_tuple[0][:g_tuple[0].find('.')] + '-' ) 
                     & self.df_ground_link[self.params['names'][1]].str.contains(g_tuple[1][:g_tuple[1].find('.')]) ]
            logging.info('findDistInDF: default')
        return dist.index.values
    
        
    def MatchWithGroundTruth(self, path_to_ground_truth='', from_mappings=False, semeru_format=False ):
        self.df_ground_link = self.df_nonground_link.copy()
        self.df_ground_link[self.params['names'][2]] = 0
        
        matchGT = [ self.findDistInDF( g , from_mappings=from_mappings, semeru_format=semeru_format ) for g in self.ground_truth_processing(path_to_ground_truth,from_mappings)]
        matchGT = functools.reduce(lambda a,b : np.concatenate([a,b]), matchGT) #Concatenate indexes
        new_column = pd.Series(np.full([len(matchGT)], 1 ), name=self.params['names'][2], index = matchGT)
        
        self.df_ground_link.update(new_column)
        logging.info("Groundtruth links computed")
        pass

### Testing BasicSequenceVectorization

In [42]:
general2vec =  BasicSequenceVectorization(params = parameters)

2025-07-06 11:27:07,253 : INFO : adding document #0 to Dictionary<0 unique tokens: []>
2025-07-06 11:27:07,271 : INFO : built Dictionary<1652 unique tokens: ['ag', 'ari', 'iv', 'pt', '▁activ']...> from 242 documents (total 78439 corpus positions)
2025-07-06 11:27:07,271 : INFO : Dictionary lifecycle event {'msg': "built Dictionary<1652 unique tokens: ['ag', 'ari', 'iv', 'pt', '▁activ']...> from 242 documents (total 78439 corpus positions)", 'datetime': '2025-07-06T11:27:07.271744', 'gensim': '4.3.3', 'python': '3.9.23 | packaged by conda-forge | (main, Jun  4 2025, 18:02:02) \n[Clang 18.1.8 ]', 'platform': 'macOS-15.5-arm64-arm-64bit', 'event': 'created'}
2025-07-06 11:27:07,272 : INFO : bpe preprocessing documents and dictionary

In [43]:
general2vec.vocab

{'<pad>': 0,
 '<unk>': 0,
 '<s>': 0,
 '</s>': 0,
 '▁t': 0,
 'in': 0,
 'er': 0,
 '▁a': 0,
 '▁.': 0,
 'on': 0,
 '▁(': 0,
 '▁)': 0,
 '▁,': 0,
 'he': 0,
 're': 0,
 '▁s': 0,
 'at': 0,
 'en': 0,
 'or': 0,
 '▁the': 0,
 '▁c': 0,
 '▁=': 0,
 'es': 0,
 '▁f': 0,
 'ed': 0,
 'al': 0,
 'is': 0,
 '▁p': 0,
 'an': 0,
 'it': 0,
 'ar': 0,
 '▁w': 0,
 '▁o': 0,
 '▁in': 0,
 'el': 0,
 'et': 0,
 'ing': 0,
 'ion': 0,
 '▁b': 0,
 '▁d': 0,
 '▁re': 0,
 'as': 0,
 'ro': 0,
 '▁n': 0,
 'nd': 0,
 'ic': 0,
 'le': 0,
 '▁m': 0,
 '▁;': 0,
 'ur': 0,
 '▁of': 0,
 'am': 0,
 '▁to': 0,
 '▁"': 0,
 '▁and': 0,
 'ent': 0,
 '▁:': 0,
 '▁l': 0,
 '▁g': 0,
 '▁h': 0,
 '▁i': 0,
 '▁S': 0,
 'ct': 0,
 "▁'": 0,
 'ut': 0,
 'st': 0,
 'ce': 0,
 'il': 0,
 '▁T': 0,
 '▁th': 0,
 'ul': 0,
 '▁e': 0,
 'id': 0,
 'ad': 0,
 '▁{': 0,
 '▁1': 0,
 'om': 0,
 'se': 0,
 '▁}': 0,
 'tr': 0,
 '▁C': 0,
 '▁A': 0,
 'ot': 0,
 'ol': 0,
 '▁for': 0,
 '▁if': 0,
 'un': 0,
 '▁[': 0,
 'ig': 0,
 '▁]': 0,
 'od': 0,
 'elf': 0,
 '▁v': 0,
 'im': 0,
 '▁self': 0,
 'ch': 0,
 'pt': 0,
 '▁get': 0,
 '▁I': 0,
 '▁@': 0,
 '▁M': 0,
 'ame': 0,
 'urn': 0,
 'ter': 0,
 'ra': 0,
 '▁de': 0,
 'ation': 0,
 '▁ret': 0,
 '▁is': 0,
 'ate': 0,
 'pe': 0,
 '▁st': 0,
 'ag': 0,
 'us': 0,
 'iv': 0,
 '▁return': 0,
 '▁B': 0,
 '▁N': 0,
 'um': 0,
 '▁con': 0,
 'ir': 0,
 '▁on': 0,
 'ck': 0,
 '▁was': 0,
 'ue': 0,
 'ew': 0,
 'em': 0,
 'ers': 0,
 'ow': 0,
 'ist': 0,
 'ly': 0,
 'th': 0,
 'ub': 0,
 '▁P': 0,
 '▁be': 0,
 'ith': 0,
 '▁as': 0,
 'ab': 0,
 '▁The': 0,
 'est': 0,
 '▁F': 0,
 '▁R': 0,
 'ay': 0,
 'ect': 0,
 'ver': 0,
 '▁H': 0,
 '▁D': 0,
 '▁2': 0,
 'ex': 0,
 'qu': 0,
 'up': 0,
 '-@': 0,
 '▁@-@': 0,
 '▁L': 0,
 'and': 0,
 '▁ex': 0,
 '▁with': 0,
 '▁wh': 0,
 'end': 0,
 '▁pro': 0,
 'ess': 0,
 '▁E': 0,
 '▁k': 0,
 '▁al': 0,
 '▁it': 0,
 '▁0': 0,
 '▁O': 0,
 '▁new': 0,
 '▁_': 0,
 'if': 0,
 'res': 0,
 '▁that': 0,
 'tring': 0,
 '▁r': 0,
 '▁by': 0,
 '▁+': 0,
 'lo': 0,
 '▁W': 0,
 '▁at': 0,
 'ption': 0,
 'ain': 0,
 '▁G': 0,
 'ile': 0,
 'pp': 0,
 'all': 0,
 '▁an': 0,
 'rom': 0,
 '▁def': 0,
 '▁<': 0,
 'art': 0,
 '▁el': 0,
 '▁not': 0,
 'ere': 0,
 'av': 0,
 '▁he': 0,
 'ass': 0,
 '▁com': 0,
 '▁res': 0,
 'ath': 0,
 'os': 0,
 'ype': 0,
 'ort': 0,
 'lic': 0,
 'ull': 0,
 'ug': 0,
 'ult': 0,
 '▁J': 0,
 '▁>': 0,
 'age': 0,
 'one': 0,
 '▁/': 0,
 'ri': 0,
 '▁#': 0,
 'und': 0,
 'ey': 0,
 '▁se': 0,
 'oc': 0,
 'our': 0,
 'ment': 0,
 '▁int': 0,
 'ore': 0,
 'op': 0,
 'pl': 0,
 '▁from': 0,
 'iz': 0,
 '▁ch': 0,
 '▁String': 0,
 'ap': 0,
 '▁19': 0,
 'ord': 0,
 'ies': 0,
 'ata': 0,
 'alue': 0,
 'ode': 0,
 '00': 0,
 'igh': 0,
 'og': 0,
 'ack': 0,
 '▁In': 0,
 'ity': 0,
 '▁tr': 0,
 '▁ad': 0,
 '▁fin': 0,
 '▁pub': 0,
 'able': 0,
 'ception': 0,
 'ak': 0,
 'ext': 0,
 '▁ar': 0,
 '▁*': 0,
 'ber': 0,
 'Ex': 0,
 'ill': 0,
 'out': 0,
 'ime': 0,
 'ac': 0,
 '▁null': 0,
 'ip': 0,
 'ction': 0,
 'ure': 0,
 'row': 0,
 '▁public': 0,
 '▁sh': 0,
 'ong': 0,
 'ine': 0,
 'per': 0,
 '▁j': 0,
 '▁==': 0,
 '▁his': 0,
 'ud': 0,
 '▁or': 0,
 'ant': 0,
 'ge': 0,
 'ard': 0,
 'ive': 0,
 '▁this': 0,
 '▁U': 0,
 'oun': 0,
 '▁//': 0,
 'rit': 0,
 'ance': 0,
 '▁cl': 0,
 '▁set': 0,
 'int': 0,
 'ject': 0,
 'ial': 0,
 'ff': 0,
 'cl': 0,
 '▁None': 0,
 'ated': 0,
 '▁y': 0,
 'ast': 0,
 'ib': 0,
 'ars': 0,
 '▁cont': 0,
 'nt': 0,
 'ire': 0,
 'ov': 0,
 'orm': 0,
 '▁pl': 0,
 'ust': 0,
 '▁else': 0,
 'ase': 0,
 'ost': 0,
 'ich': 0,
 '▁-': 0,
 '▁K': 0,
 'arg': 0,
 'ror': 0,
 '▁were': 0,
 'are': 0,
 'ight': 0,
 '▁V': 0,
 'act': 0,
 'con': 0,
 'ition': 0,
 'ans': 0,
 '▁final': 0,
 'Exception': 0,
 'ild': 0,
 '▁add': 0,
 'erv': 0,
 'ice': 0,
 '▁app': 0,
 'ok': 0,
 'Con': 0,
 '▁!': 0,
 '▁un': 0,
 'Name': 0,
 'cc': 0,
 'pon': 0,
 'ary': 0,
 'port': 0,
 '▁le': 0,
 'In': 0,
 'put': 0,
 'ugh': 0,
 '▁St': 0,
 '▁out': 0,
 '▁are': 0,
 'name': 0,
 'ide': 0,
 'quest': 0,
 'ory': 0,
 '▁3': 0,
 'iel': 0,
 'atch': 0,
 '▁en': 0,
 'St': 0,
 'ec': 0,
 'ave': 0,
 '▁had': 0,
 'ign': 0,
 'ace': 0,
 '▁which': 0,
 'ell': 0,
 'ress': 0,
 'ize': 0,
 '▁form': 0,
 '▁name': 0,
 '▁sc': 0,
 '▁ro': 0,
 '▁ra': 0,
 'ield': 0,
 'aram': 0,
 'ork': 0,
 'bject': 0,
 '▁len': 0,
 'oul': 0,
 'irst': 0,
 '▁pr': 0,
 'use': 0,
 'ia': 0,
 'ict': 0,
 '▁str': 0,
 '▁value': 0,
 'ical': 0,
 'ould': 0,
 '▁has': 0,
 'ail': 0,
 'ount': 0,
 'ind': 0,
 'ev': 0,
 'ther': 0,
 '▁throw': 0,
 'ence': 0,
 '▁up': 0,
 'ep': 0,
 '▁%': 0,
 'ef': 0,
 '▁pre': 0,
 '▁Ch': 0,
 'ound': 0,
 '▁us': 0,
 'fig': 0,
 'ry': 0,
 '▁key': 0,
 'eg': 0,
 '▁stat': 0,
 '▁im': 0,
 'ource': 0,
 'low': 0,
 '▁Th': 0,
 'Type': 0,
 '▁data': 0,
 'hed': 0,
 '▁fil': 0,
 'eth': 0,
 '▁we': 0,
 '▁first': 0,
 '▁result': 0,
 'ish': 0,
 'fter': 0,
 '▁but': 0,
 '▁col': 0,
 'ens': 0,
 'ise': 0,
 'ld': 0,
 'ous': 0,
 '▁x': 0,
 'ian': 0,
 '▁ind': 0,
 'ree': 0,
 'ax': 0,
 'ph': 0,
 '▁!=': 0,
 'so': 0,
 '▁bu': 0,
 '▁200': 0,
 '▁cre': 0,
 'str': 0,
 '▁ab': 0,
 'ix': 0,
 'own': 0,
 'ang': 0,
 '▁4': 0,
 'ator': 0,
 'vent': 0,
 '▁log': 0,
 'ert': 0,
 '▁time': 0,
 '▁rec': 0,
 '▁dis': 0,
 '▁bo': 0,
 'rror': 0,
 'form': 0,
 'stance': 0,
 'ations': 0,
 '▁do': 0,
 'alse': 0,
 'ray': 0,
 '▁per': 0,
 '▁20': 0,
 'roup': 0,
 'Id': 0,
 'tern': 0,
 'te': 0,
 'll': 0,
 'ome': 0,
 '▁comp': 0,
 'ions': 0,
 'gth': 0,
 'Error': 0,
 'du': 0,
 'ater': 0,
 'oid': 0,
 '▁path': 0,
 '▁arg': 0,
 '▁try': 0,
 '▁part': 0,
 'wo': 0,
 'ery': 0,
 'ponse': 0,
 '▁sub': 0,
 '▁have': 0,
 'hen': 0,
 '▁its': 0,
 'oint': 0,
 'ach': 0,
 'ear': 0,
 'lass': 0,
 'esc': 0,
 '▁comm': 0,
 '▁append': 0,
 'ames': 0,
 'fo': 0,
 '▁her': 0,
 'ient': 0,
 '▁5': 0,
 '▁one': 0,
 '--': 0,
 '▁off': 0,
 '▁su': 0,
 'ob': 0,
 'Res': 0,
 '▁num': 0,
 '▁their': 0,
 '▁rem': 0,
 'ute': 0,
 'ener': 0,
 'als': 0,
 'ces': 0,
 '▁–': 0,
 'clud': 0,
 '▁also': 0,
 '▁Tr': 0,
 'ings': 0,
 'son': 0,
 'ark': 0,
 '▁writ': 0,
 'amp': 0,
 '▁who': 0,
 '▁He': 0,
 'oth': 0,
 'ann': 0,
 'ty': 0,
 'urre': 0,
 'IN': 0,
 'List': 0,
 'Re': 0,
 '▁end': 0,
 '▁start': 0,
 'pec': 0,
 '▁ent': 0,
 '▁all': 0,
 'erm': 0,
 '▁ag': 0,
 '▁id': 0,
 'Pro': 0,
 '▁&': 0,
 '▁list': 0,
 'ual': 0,
 '▁void': 0,
 '▁format': 0,
 '▁val': 0,
 '▁over': 0,
 '▁co': 0,
 'ER': 0,
 'set': 0,
 'ik': 0,
 'ents': 0,
 'essage': 0,
 'val': 0,
 'old': 0,
 '▁bec': 0,
 '▁been': 0,
 '▁two': 0,
 '▁qu': 0,
 '▁18': 0,
 'ite': 0,
 'ethod': 0,
 'ervice': 0,
 '▁sy': 0,
 'les': 0,
 'fer': 0,
 'type': 0,
 'ange': 0,
 'vel': 0,
 'En': 0,
 'ied': 0,
 '.@': 0,
 '▁@.@': 0,
 'ader': 0,
 '▁mod': 0,
 '▁tra': 0,
 'uring': 0,
 'ick': 0,
 'ues': 0,
 'ON': 0,
 'ole': 0,
 '▁Ar': 0,
 'ade': 0,
 '▁It': 0,
 'che': 0,
 'trib': 0,
 'file': 0,
 '▁sp': 0,
 'args': 0,
 'cept': 0,
 'ely': 0,
 '▁class': 0,
 '▁after': 0,
 'ream': 0,
 '▁other': 0,
 '▁Con': 0,
 '▁lo': 0,
 '▁er': 0,
 'iew': 0,
 'ates': 0,
 '▁201': 0,
 'ection': 0,
 'ms': 0,
 '▁pos': 0,
 'iss': 0,
 'try': 0,
 ',@': 0,
 '▁@,@': 0,
 '▁includ': 0,
 '▁request': 0,
 'mer': 0,
 '▁sup': 0,
 'ake': 0,
 'ough': 0,
 'ced': 0,
 '▁type': 0,
 'Value': 0,
 'eat': 0,
 '▁go': 0,
 'ft': 0,
 '▁Y': 0,
 '▁loc': 0,
 '▁man': 0,
 '▁Un': 0,
 '▁play': 0,
 '▁6': 0,
 '▁work': 0,
 'ss': 0,
 'we': 0,
 'ove': 0,
 'ari': 0,
 '▁static': 0,
 '▁they': 0,
 '▁reg': 0,
 '▁length': 0,
 '▁while': 0,
 '▁call': 0,
 '▁raise': 0,
 'ger': 0,
 'land': 0,
 'Cont': 0,
 'ault': 0,
 '▁inter': 0,
 'path': 0,
 'ward': 0,
 'led': 0,
 '▁into': 0,
 '▁att': 0,
 'ors': 0,
 '▁file': 0,
 'ask': 0,
 'ered': 0,
 'cond': 0,
 'til': 0,
 'urrent': 0,
 'ument': 0,
 '▁param': 0,
 '▁would': 0,
 'aw': 0,
 'cess': 0,
 '▁so': 0,
 '▁ass': 0,
 'ie': 0,
 'ersion': 0,
 'Ar': 0,
 'ember': 0,
 'ific': 0,
 '▁On': 0,
 'ased': 0,
 '▁she': 0,
 '▁char': 0,
 'escri': 0,
 'ccess': 0,
 'url': 0,
 'ric': 0,
 'ron': 0,
 'arn': 0,
 '▁ser': 0,
 'pro': 0,
 '▁True': 0,
 'ited': 0,
 '▁Ex': 0,
 'String': 0,
 '▁op': 0,
 '▁can': 0,
 '▁min': 0,
 'heck': 0,
 'oin': 0,
 'pr': 0,
 '▁False': 0,
 'ool': 0,
 'tt': 0,
 'ever': 0,
 '▁Com': 0,
 'lement': 0,
 '▁more': 0,
 '▁him': 0,
 '▁ob': 0,
 '▁long': 0,
 'way': 0,
 'rough': 0,
 'ink': 0,
 'ason': 0,
 '▁7': 0,
 '▁8': 0,
 '▁only': 0,
 'wargs': 0,
 'Class': 0,
 'stem': 0,
 'read': 0,
 'date': 0,
 '▁prot': 0,
 'ule': 0,
 'com': 0,
 'irect': 0,
 '▁field': 0,
 '▁when': 0,
 'cre': 0,
 '..': 0,
 '▁index': 0,
 'Bu': 0,
 '▁bet': 0,
 '▁act': 0,
 '▁create': 0,
 'att': 0,
 'ash': 0,
 '▁te': 0,
 '▁line': 0,
 'ier': 0,
 'its': 0,
 '▁?': 0,
 'olean': 0,
 'arsh': 0,
 '▁state': 0,
 '▁ap': 0,
 'inal': 0,
 '▁En': 0,
 '▁read': 0,
 'round': 0,
 'app': 0,
 'AT': 0,
 'lock': 0,
 '▁del': 0,
 'sh': 0,
 '▁trans': 0,
 'ren': 0,
 'arch': 0,
 'eb': 0,
 '▁&&': 0,
 '▁Al': 0,
 '▁exp': 0,
 'ale': 0,
 'outh': 0,
 '▁me': 0,
 '▁ext': 0,
 'ose': 0,
 '▁spec': 0,
 '▁args': 0,
 '▁config': 0,
 '▁cons': 0,
 '▁record': 0,
 '▁event': 0,
 '▁rel': 0,
 '▁group': 0,
 'get': 0,
 'ank': 0,
 'arget': 0,
 '▁np': 0,
 '▁An': 0,
 '▁kwargs': 0,
 'pect': 0,
 '▁throws': 0,
 '▁no': 0,
 'Key': 0,
 'ement': 0,
 '▁size': 0,
 'umn': 0,
 '▁build': 0,
 'ession': 0,
 'fore': 0,
 '▁9': 0,
 'ollow': 0,
 'ected': 0,
 'wn': 0,
 '▁und': 0,
 'uth': 0,
 '▁pass': 0,
 '▁item': 0,
 '▁current': 0,
 '▁error': 0,
 '▁met': 0,
 '▁em': 0,
 '▁than': 0,
 '▁Object': 0,
 'gan': 0,
 '▁run': 0,
 '▁next': 0,
 'data': 0,
 '▁fl': 0,
 '▁deb': 0,
 '▁List': 0,
 'ized': 0,
 '▁produ': 0,
 'ween': 0,
 '▁cent': 0,
 'arshall': 0,
 '▁response': 0,
 'red': 0,
 'to': 0,
 'ines': 0,
 '▁again': 0,
 'Com': 0,
 '▁kn': 0,
 'Set': 0,
 'ler': 0,
 '▁during': 0,
 '▁case': 0,
 'Request': 0,
 '▁dec': 0,
 '▁catch': 0,
 'uble': 0,
 'key': 0,
 'ired': 0,
 'co': 0,
 '▁max': 0,
 '▁most': 0,
 'arent': 0,
 'ru': 0,
 'orth': 0,
 '▁clo': 0,
 'ational': 0,
 '▁rele': 0,
 '▁bre': 0,
 '▁ca': 0,
 'ution': 0,
 'ious': 0,
 '▁des': 0,
 'ision': 0,
 '▁second': 0,
 'ower': 0,
 'ivate': 0,
 'eter': 0,
 '▁print': 0,
 '▁found': 0,
 '▁game': 0,
 '▁contin': 0,
 '▁Pro': 0,
 '▁number': 0,
 '▁par': 0,
 '▁equ': 0,
 'ating': 0,
 'yn': 0,
 '▁Over': 0,
 'ache': 0,
 'uct': 0,
 'Ch': 0,
 'ape': 0,
 'To': 0,
 '▁10': 0,
 '▁about': 0,
 'io': 0,
 '▁199': 0,
 '▁between': 0,
 '▁where': 0,
 'ID': 0,
 'pos': 0,
 '▁day': 0,
 '▁Se': 0,
 '▁z': 0,
 'list': 0,
 'ride': 0,
 '▁them': 0,
 '▁before': 0,
 'orn': 0,
 '▁Col': 0,
 '▁except': 0,
 '▁New': 0,
 'ics': 0,
 'ern': 0,
 'RE': 0,
 '▁am': 0,
 'ins': 0,
 '▁later': 0,
 'Data': 0,
 '▁through': 0,
 'abel': 0,
 '__': 0,
 '▁node': 0,
 '▁os': 0,
 'perty': 0,
 'ock': 0,
 '▁boolean': 0,
 'air': 0,
 '▁join': 0,
 'ST': 0,
 '▁film': 0,
 'ike': 0,
 '▁song': 0,
 'ete': 0,
 '▁|': 0,
 '▁__': 0,
 '▁ac': 0,
 'arly': 0,
 '▁acc': 0,
 'ative': 0,
 '▁pe': 0,
 '▁write': 0,
 'ps': 0,
 '▁At': 0,
 '▁back': 0,
 '▁elif': 0,
 '▁ne': 0,
 'ived': 0,
 'back': 0,
 'orld': 0,
 '▁X': 0,
 'az': 0,
 'File': 0,
 '▁there': 0,
 'ou': 0,
 '▁check': 0,
 '▁This': 0,
 '▁three': 0,
 've': 0,
 'ffer': 0,
 'Path': 0,
 'raph': 0,
 '▁pol': 0,
 'ody': 0,
 '▁last': 0,
 '▁high': 0,
 '▁Sh': 0,
 'ven': 0,
 '▁match': 0,
 '▁open': 0,
 '▁put': 0,
 'ures': 0,
 'ton': 0,
 'vid': 0,
 '▁true': 0,
 'man': 0,
 '▁+=': 0,
 '▁under': 0,
 '▁private': 0,
 'instance': 0,
 '▁conn': 0,
 'ek': 0,
 'ndex': 0,
 'time': 0,
 '▁find': 0,
 'rid': 0,
 'sc': 0,
 '▁pop': 0,
 'ished': 0,
 '▁some': 0,
 '▁hand': 0,
 '▁Q': 0,
 '▁follow': 0,
 '▁user': 0,
 '▁method': 0,
 '▁season': 0,
 '▁orig': 0,
 '▁use': 0,
 'meric': 0,
 '▁ep': 0,
 '▁feat': 0,
 '▁then': 0,
 'ram': 0,
 'At': 0,
 'press': 0,
 'ond': 0,
 'ME': 0,
 'LE': 0,
 'ages': 0,
 'ml': 0,
 '▁Override': 0,
 '▁used': 0,
 '▁Americ': 0,
 'yp': 0,
 'ral': 0,
 '▁contain': 0,
 'By': 0,
 'ists': 0,
 'ally': 0,
 '▁year': 0,
 '▁text': 0,
 '▁gener': 0,
 '▁ord': 0,
 'ears': 0,
 'reat': 0,
 'hip': 0,
 '▁sign': 0,
 '▁show': 0,
 'dict': 0,
 'unction': 0,
 'Param': 0,
 '▁Jo': 0,
 'cy': 0,
 '▁u': 0,
 'ared': 0,
 '▁instance': 0,
 'Map': 0,
 '▁break': 0,
 'aid': 0,
 '."': 0,
 'plit': 0,
 'iver': 0,
 '▁made': 0,
 '▁inv': 0,
 '▁false': 0,
 '▁any': 0,
 ...}

In [44]:
general2vec.documents

[['▁summ',
  'ari',
  '▁log',
  '▁gcs',
  '▁relat',
  '▁event',
  '▁descri',
  'pt',
  '▁activ',
  '▁logger',
  '▁shall',
  '▁log',
  '▁command',
  '▁sent',
  '▁mess',
  'ag',
  '▁rece',
  'iv',
  '▁cgs'],
 ['▁summ',
  'ari',
  '▁support',
  '▁gcs',
  '▁connect',
  '▁u',
  'av',
  '▁descri',
  'pt',
  '▁veh',
  'ic',
  'l',
  '▁core',
  '▁shall',
  '▁support',
  '▁u',
  'av',
  '▁connect',
  '▁via',
  '▁gcs'],
 ['▁summ',
  'ari',
  '▁manual',
  '▁flight',
  '▁plan',
  '▁assign',
  '▁descri',
  'pt',
  '▁rout',
  '▁contain',
  '▁spec',
  'if',
  '▁u',
  'av',
  '▁sing',
  'l',
  '▁u',
  'av',
  'flight',
  '▁plan',
  '▁sched',
  'ul',
  '▁shall',
  '▁assign',
  '▁rout',
  '▁given',
  '▁u',
  'av'],
 ['▁summ',
  'ari',
  '▁visit',
  '▁waypoint',
  '▁flight',
  '▁plan',
  '▁descri',
  'pt',
  '▁flight',
  '▁plan',
  '▁execut',
  '▁veh',
  'ic',
  'l',
  '▁core',
  '▁shall',
  '▁send',
  '▁next',
  '▁waypoint',
  '▁u',
  'av'],
 ['▁summ',
  'ari',
  '▁establish',
  '▁maximum',
  '▁number',
  '▁activ',
  '▁u',
  'av',
  '▁descri',
  'pt',
  '▁maximum',
  '▁number',
  '▁allow',
  '▁activ',
  '▁u',
  'av',
  '▁reach',
  '▁u',
  'av',
  'activ',
  '▁man',
  'ag',
  '▁shall',
  '▁reject',
  '▁activ',
  '▁request'],
 ['▁summ',
  'ari',
  '▁support',
  '▁intern',
  '▁simul',
  '▁u',
  'av',
  '▁descri',
  'pt',
  '▁veh',
  'ic',
  'l',
  '▁core',
  '▁shall',
  '▁support',
  '▁virtual',
  '▁u',
  'av'],
 ['▁summ',
  'ari',
  '▁middle',
  'war',
  '▁list',
  '▁save',
  '▁flight',
  '▁rout',
  '▁descri',
  'pt',
  '▁u',
  'im',
  'iddle',
  'war',
  '▁shall',
  '▁provid',
  '▁list',
  '▁exist',
  '▁rout'],
 ['▁summ',
  'ari',
  '▁mission',
  '▁plan',
  '▁descri',
  'pt',
  '▁mission',
  '▁planner',
  '▁shall',
  '▁execut',
  '▁flight',
  '▁plan',
  '▁multi',
  'pl',
  '▁u',
  'av',
  '▁conc',
  'ur',
  'r'],
 ['▁summ',
  'ari',
  '▁log',
  '▁flight',
  '▁plan',
  '▁relat',
  '▁event',
  '▁descri',
  'pt',
  '▁activ',
  '▁logger',
  '▁shall',
  '▁log',
  '▁flight',
  '▁plan',
  '▁relat',
  '▁event'],
 ['▁summ',
  'ari',
  '▁accept',
  '▁mission',
  '▁plan',
  '▁descri',
  'pt',
  '▁u',
  'im',
  'iddle',
  'war',
  '▁shall',
  '▁accept',
  '▁activ',
  '▁mission',
  '▁plan',
  '▁upon',
  '▁request'],
 ['▁summ',
  'ari',
  '▁multi',
  'pl',
  '▁map',
  '▁type',
  '▁descri',
  'pt',
  '▁map',
  '▁com',
  'pon',
  '▁shall',
  '▁support',
  '▁differ',
  '▁type',
  '▁map',
  '▁layer',
  '▁terrain',
  '▁sat',
  'ell',
  'it'],
 ['▁summ',
  'ari',
  '▁transmit',
  '▁rout',
  '▁assign',
  '▁middle',
  'war',
  '▁descri',
  'pt',
  '▁rout',
  '▁assign',
  '▁remov',
  '▁u',
  'av',
  '▁rout',
  '▁assign',
  '▁shall',
  '▁not',
  'ifi',
  '▁d',
  'ron',
  'olog'],
 ['▁summ',
  'ari',
  '▁monitor',
  '▁mess',
  'ag',
  '▁descri',
  'pt',
  '▁d',
  'ron',
  'olog',
  '▁run',
  'tim',
  '▁monitor',
  '▁shall',
  '▁provid',
  '▁function',
  '▁retriev',
  '▁monitor',
  '▁mess',
  'ag',
  '▁distrib',
  'ut',
  '▁client'],
 ['▁summ',
  'ari',
  '▁u',
  'av',
  '▁command',
  '▁descri',
  'pt',
  '▁gcs',
  'middle',
  'war',
  '▁shall',
  '▁forward',
  '▁command',
  '▁sent',
  '▁d',
  'ron',
  'olog',
  '▁gcs'],
 ['▁summ',
  'ari',
  '▁ground',
  'stat',
  '▁middle',
  'war',
  '▁commun',
  'ic',
  '▁protocol',
  '▁descri',
  'pt',
  '▁gcs',
  'middle',
  'war',
  '▁shall',
  '▁follow',
  '▁pre',
  'def',
  'in',
  '▁set',
  '▁step',
  '▁establish',
  '▁connect',
  '▁gcs',
  '▁d',
  'ron',
  'olog'],
 ['▁summ',
  'ari',
  '▁calc',
  'ul',
  '▁dist',
  'anc',
  '▁descri',
  'pt',
  '▁given',
  '▁two',
  '▁co',
  'ordin',
  '▁co',
  'ordin',
  '▁system',
  '▁shall',
  '▁comput',
  '▁dist',
  'anc'],
 ['▁summ',
  'ari',
  '▁one',
  '▁instanc',
  '▁reg',
  'ist',
  '▁drone',
  '▁may',
  '▁activ',
  '▁time',
  '▁descri',
  'pt',
  '▁u',
  'av',
  'activ',
  '▁man',
  'ag',
  '▁shall',
  '▁ens',
  'ur',
  '▁one',
  '▁instanc',
  '▁reg',
  'ist',
  '▁drone',
  '▁activ',
  '▁time'],
 ['▁summ',
  'ari',
  '▁display',
  '▁activ',
  '▁rout',
  '▁descri',
  'pt',
  '▁real',
  '▁time',
  '▁flight',
  '▁shall',
  '▁display',
  '▁current',
  '▁activ',
  '▁flight',
  '▁plan',
  '▁map'],
 ['▁summ',
  'ari',
  '▁flight',
  '▁rout',
  '▁def',
  'in',
  '▁waypoint',
  '▁descri',
  'pt',
  '▁flight',
  '▁rout',
  '▁man',
  'ag',
  '▁shall',
  '▁def',
  'in',
  '▁flight',
  '▁rout',
  '▁order',
  '▁sequ',
  'enc',
  '▁waypoint',
  '▁first',
  '▁waypoint',
  '▁rep',
  'res',
  '▁first',
  '▁target',
  '▁loc',
  'at',
  '▁final',
  '▁waypoint',
  '▁rep',
  'res',
  '▁final',
  '▁target',
  '▁loc',
  'at'],
 ['▁summ',
  'ari',
  '▁delet',
  '▁rout',
  '▁descri',
  'pt',
  '▁rout',
  '▁creation',
  '▁shall',
  '▁allow',
  '▁user',
  '▁delet',
  '▁rout'],
 ['▁summ',
  'ari',
  '▁assign',
  '▁new',
  '▁flight',
  '▁plan',
  '▁upon',
  '▁complet',
  '▁previous',
  '▁flight',
  '▁descri',
  'pt',
  '▁u',
  'av',
  '▁pend',
  '▁flight',
  '▁plan',
  '▁reach',
  '▁final',
  '▁waypoint',
  '▁current',
  '▁flight',
  '▁plan',
  '▁sing',
  'l',
  '▁u',
  'av',
  'flight',
  '▁plan',
  '▁sched',
  'ul',
  '▁shall',
  '▁execut',
  '▁next',
  '▁assign',
  '▁flight',
  '▁plan'],
 ['▁summ',
  'ari',
  '▁flight',
  '▁rout',
  '▁persist',
  '▁descri',
  'pt',
  '▁flight',
  '▁rout',
  '▁man',
  'ag',
  '▁shall',
  '▁persist',
  '▁flight',
  '▁rout'],
 ['▁summ',
  'ari',
  '▁u',
  'av',
  '▁ident',
  'if',
  '▁descri',
  'pt',
  '▁veh',
  'ic',
  'l',
  '▁core',
  '▁shall',
  '▁assign',
  '▁uniqu',
  '▁activ',
  '▁u',
  'av'],
 ['▁summ',
  'ari',
  '▁publish',
  '▁monitor',
  '▁mess',
  'ag',
  '▁descri',
  'pt',
  '▁d',
  'ron',
  'olog',
  '▁run',
  'tim',
  '▁monitor',
  '▁shall',
  '▁abl',
  '▁rece',
  'iv',
  '▁mess',
  'ag',
  '▁d',
  'ron',
  'olog',
  '▁com',
  'pon'],
 ['▁summ',
  'ari',
  '▁co',
  'ordin',
  '▁system',
  '▁convers',
  '▁descri',
  'pt',
  '▁request',
  '▁co',
  'ordin',
  '▁system',
  '▁shall',
  '▁transform',
  '▁co',
  'ordin',
  '▁altern',
  '▁format'],
 ['▁summ',
  'ari',
  '▁remov',
  '▁plan',
  '▁flight',
  '▁descri',
  'pt',
  '▁request',
  '▁sing',
  'l',
  '▁u',
  'av',
  'flight',
  '▁plan',
  '▁sched',
  'ul',
  '▁shall',
  '▁unassign',
  '▁flight',
  '▁plan',
  '▁assign',
  '▁u',
  'av',
  '▁await',
  '▁execut'],
 ['▁summ',
  'ari',
  '▁display',
  '▁map',
  '▁descri',
  'pt',
  '▁real',
  '▁time',
  '▁flight',
  '▁load',
  '▁map',
  '▁shall',
  '▁display'],
 ['▁summ',
  'ari',
  '▁rout',
  '▁creation',
  '▁mod',
  'if',
  '▁descri',
  'pt',
  '▁rout',
  '▁creation',
  '▁shall',
  '▁allow',
  '▁user',
  '▁cre',
  'at',
  '▁mod',
  'ifi',
  '▁rout'],
 ['▁summ',
  'ari',
  '▁remov',
  '▁pend',
  '▁plan',
  '▁return',
  '▁home',
  '▁descri',
  'pt',
  '▁u',
  'av',
  '▁current',
  '▁flight',
  '▁cancel',
  '▁sing',
  'l',
  '▁u',
  'av',
  'flight',
  '▁plan',
  '▁sched',
  'ul',
  '▁shall',
  '▁turn',
  '▁cancel',
  '▁sched',
  'ul',
  '▁flight',
  '▁plan',
  '▁u',
  'av'],
 ['▁summ',
  'ari',
  '▁connect',
  '▁gcs',
  '▁d',
  'ron',
  'olog',
  '▁via',
  '▁middle',
  'war',
  '▁descri',
  'pt',
  '▁gcs',
  'middle',
  'war',
  '▁shall',
  '▁hand',
  'l',
  '▁multi',
  'pl',
  '▁gcs'],
 ['▁summ',
  'ari',
  '▁load',
  '▁default',
  '▁co',
  'ordin',
  '▁descri',
  'pt',
  '▁load',
  '▁map',
  '▁view',
  '▁shall',
  '▁posit',
  '▁pre',
  '▁def',
  'in',
  '▁loc',
  'at'],
 ['▁summ',
  'ari',
  '▁u',
  'av',
  '▁mess',
  'ag',
  '▁descri',
  'pt',
  '▁gcs',
  'middle',
  'war',
  '▁shall',
  '▁hand',
  'l',
  '▁state',
  '▁mess',
  'ag',
  '▁monitor',
  '▁mess',
  'ag',
  '▁mode',
  '▁chang',
  '▁mess',
  'ag',
  '▁rece',
  'iv',
  '▁gcs'],
 ['▁summ',
  'ari',
  '▁spec',
  'ifi',
  '▁takeoff',
  '▁alt',
  'itud',
  '▁descri',
  'pt',
  '▁flight',
  '▁rout',
  '▁requ',
  'ir',
  '▁custom',
  '▁takeoff',
  '▁alt',
  'itud',
  '▁differ',
  '▁system',
  '▁default',
  '▁takeoff',
  '▁alt',
  'itud',
  '▁shall',
  '▁spec',
  'ifi',
  '▁flight',
  '▁rout'],
 ['▁summ',
  'ari',
  '▁u',
  'av',
  '▁flight',
  '▁plan',
  '▁execut',
  '▁descri',
  'pt',
  '▁sing',
  'l',
  '▁u',
  'av',
  'flight',
  '▁plan',
  '▁sched',
  'ul',
  '▁shall',
  '▁execut',
  '▁one',
  '▁flight',
  '▁plan',
  '▁time',
  '▁u',
  'av'],
 ['▁summ',
  'ari',
  '▁display',
  '▁activ',
  '▁u',
  'av',
  '▁descri',
  'pt',
  '▁real',
  '▁time',
  '▁flight',
  '▁shall',
  '▁display',
  '▁name',
  '▁status',
  '▁current',
  '▁activ',
  '▁u',
  'av'],
 ['▁summ',
  'ari',
  '▁follow',
  '▁u',
  'av',
  '▁descri',
  'pt',
  '▁real',
  '▁time',
  '▁flight',
  '▁shall',
  '▁allow',
  '▁user',
  '▁follow',
  '▁one',
  '▁multi',
  'pl',
  '▁u',
  'av',
  '▁map'],
 ['▁summ',
  'ari',
  '▁mod',
  'ifi',
  '▁assign',
  '▁rout',
  '▁descri',
  'pt',
  '▁user',
  '▁may',
  '▁reorder',
  '▁rout',
  '▁remov',
  '▁flight',
  '▁plan',
  '▁assign',
  '▁u',
  'av',
  '▁long',
  '▁flight',
  '▁start',
  '▁execut'],
 ['▁summ',
  'ari',
  '▁assign',
  '▁rout',
  '▁descri',
  'pt',
  '▁rout',
  '▁assign',
  '▁shall',
  '▁provid',
  '▁mean',
  '▁select',
  '▁exist',
  '▁rout',
  '▁assign',
  '▁u',
  'av'],
 ['▁summ',
  'ari',
  '▁u',
  'av',
  '▁oper',
  '▁descri',
  'pt',
  '▁real',
  '▁time',
  '▁flight',
  '▁shall',
  '▁allow',
  '▁user',
  '▁appl',
  'i',
  '▁flight',
  '▁oper',
  '▁one',
  '▁select',
  '▁u',
  'av'],
 ['▁summ',
  'ari',
  '▁display',
  '▁list',
  '▁exist',
  '▁rout',
  '▁descri',
  'pt',
  '▁rout',
  '▁creation',
  '▁load',
  '▁list',
  '▁exist',
  '▁rout',
  '▁shall',
  '▁display'],
 ['▁summ',
  'ari',
  '▁emer',
  'g',
  '▁oper',
  '▁descri',
  'pt',
  '▁real',
  '▁time',
  '▁flight',
  '▁shall',
  '▁allow',
  '▁user',
  '▁perform',
  '▁emer',
  'g',
  '▁oper',
  '▁hover',
  '▁multi',
  'pl',
  '▁u',
  'av',
  '▁send',
  '▁multi',
  'pl',
  '▁u',
  'av',
  '▁home',
  '▁group',
  '▁u',
  'av'],
 ['▁summ',
  'ari',
  '▁middle',
  'war',
  '▁support',
  '▁rout',
  '▁assign',
  '▁u',
  'av',
  '▁descri',
  'pt',
  '▁u',
  'im',
  'iddle',
  'war',
  '▁shall',
  '▁en',
  'abl',
  '▁exist',
  '▁rout',
  '▁assign',
  '▁activ',
  '▁u',
  'av'],
 ['▁summ',
  'ari',
  '▁hover',
  '▁complet',
  '▁flight',
  '▁descri',
  'pt',
  '▁u',
  'av',
  '▁pend',
  '▁flight',
  '▁plan',
  '▁reach',
  '▁final',
  '▁waypoint',
  '▁current',
  '▁flight',
  '▁plan',
  '▁sing',
  'l',
  '▁u',
  'av',
  'flight',
  '▁plan',
  '▁sched',
  'ul',
  '▁shall',
  '▁not',
  'ifi',
  '▁u',
  'av',
  '▁hover',
  '▁place'],
 ['▁summ',
  'ari',
  '▁pre',
  'def',
  'in',
  '▁flight',
  '▁pattern',
  '▁descri',
  'pt',
  '▁mission',
  '▁planner',
  '▁shall',
  '▁man',
  'ag',
  '▁pre',
  'def',
  'in',
  '▁flight',
  '▁pattern'],
 ['▁summ',
  'ari',
  '▁simul',
  '▁land',
  '▁descri',
  'pt',
  '▁given',
  '▁land',
  '▁command',
  '▁intern',
  '▁simul',
  '▁shall',
  '▁move',
  '▁u',
  'av',
  '▁ground',
  '▁alt',
  'itud',
  '▁correspond',
  '▁current',
  '▁long',
  'itud',
  '▁lat',
  'itud'],
 ['▁summ',
  'ari',
  '▁u',
  'av',
  '▁state',
  '▁transit',
  '▁descri',
  'pt',
  '▁request',
  '▁veh',
  'ic',
  'l',
  '▁core',
  '▁shall',
  '▁shall',
  '▁transit',
  '▁u',
  'av',
  '▁state',
  '▁accord',
  '▁allow',
  '▁state',
  '▁transit',
  '▁depict',
  '▁u',
  'av',
  '▁state',
  '▁transit',
  '▁diagram'],
 ['▁summ',
  'ari',
  '▁simul',
  '▁batter',
  'i',
  '▁descri',
  'pt',
  '▁intern',
  '▁simul',
  '▁shall',
  '▁approxim',
  '▁state',
  '▁batter',
  'i'],
 ['▁summ',
  'ari',
  '▁middle',
  'war',
  '▁provid',
  '▁support',
  '▁mod',
  'ifi',
  '▁flight',
  '▁rout',
  '▁descri',
  'pt',
  '▁u',
  'im',
  'iddle',
  'war',
  '▁shall',
  '▁en',
  'abl',
  '▁creation',
  '▁mod',
  'if',
  '▁flight',
  '▁rout'],
 ['▁summ',
  'ari',
  '▁simul',
  '▁goto',
  '▁descri',
  'pt',
  '▁given',
  '▁goto',
  '▁command',
  '▁intern',
  '▁simul',
  '▁shall',
  '▁up',
  'dat',
  '▁loc',
  'at',
  '▁u',
  'av',
  '▁increment',
  '▁simul',
  '▁step',
  '▁size',
  '▁meter',
  '▁move',
  '▁toward',
  '▁target',
  '▁dest',
  'in',
  '▁dest',
  'in',
  '▁reach'],
 ['▁summ',
  'ari',
  '▁simul',
  '▁takeoff',
  '▁descri',
  'pt',
  '▁given',
  '▁takeoff',
  '▁command',
  '▁intern',
  '▁simul',
  '▁shall',
  '▁move',
  '▁u',
  'av',
  '▁takeoff',
  '▁alt',
  'itud',
  '▁correspond',
  '▁current',
  '▁long',
  'itud',
  '▁lat',
  'itud'],
 ['▁summ',
  'ari',
  '▁waypoint',
  '▁definit',
  '▁descri',
  'pt',
  '▁waypoint',
  '▁shall',
  '▁spec',
  'ifi',
  '▁use',
  '▁co',
  'ordin',
  '▁includ',
  '▁long',
  'itud',
  '▁lat',
  'itud',
  '▁alt',
  'itud'],
 ['▁summ',
  'ari',
  '▁flight',
  '▁plan',
  '▁sched',
  'ul',
  '▁descri',
  'pt',
  '▁request',
  '▁sing',
  'l',
  '▁u',
  'av',
  'flight',
  '▁plan',
  '▁sched',
  'ul',
  '▁shall',
  '▁sched',
  'ul',
  '▁rout',
  '▁execut'],
 ['▁summ',
  'ari',
  '▁middle',
  'war',
  '▁forward',
  '▁command',
  '▁client',
  '▁d',
  'ron',
  'olog',
  '▁descri',
  'pt',
  '▁u',
  'im',
  'iddle',
  'war',
  '▁accept',
  '▁command',
  '▁forward',
  '▁d',
  'ron',
  'olog'],
 ['▁summ',
  'ari',
  '▁middle',
  'war',
  '▁list',
  '▁current',
  '▁activ',
  '▁u',
  'av',
  '▁descri',
  'pt',
  '▁u',
  'im',
  'iddle',
  'war',
  '▁shall',
  '▁provid',
  '▁list',
  '▁activ',
  '▁u',
  'av'],
 ['▁summ',
  'ari',
  '▁return',
  '▁home',
  '▁without',
  '▁detour',
  '▁descri',
  'pt',
  '▁return',
  '▁home',
  '▁command',
  '▁iss',
  'u',
  '▁flight',
  '▁man',
  'ag',
  '▁shall',
  '▁return',
  '▁u',
  'av',
  '▁origin',
  '▁launch',
  '▁loc',
  'at',
  '▁without',
  '▁iss',
  'u',
  '▁add',
  'it',
  '▁waypoint',
  '▁rout',
  '▁command'],
 ['▁summ',
  'ari',
  '▁de',
  'activ',
  '▁physic',
  '▁u',
  'av',
  '▁descri',
  'pt',
  '▁u',
  'av',
  '▁de',
  'activ',
  '▁u',
  'av',
  'activ',
  '▁man',
  'ag',
  '▁shall',
  '▁cancel',
  '▁current',
  '▁sched',
  'ul',
  '▁flight',
  '▁plan'],
 ['▁summ',
  'ari',
  '▁cancel',
  '▁mission',
  '▁descri',
  'pt',
  '▁request',
  '▁mission',
  '▁current',
  '▁activ',
  '▁mission',
  '▁planner',
  '▁shall',
  '▁cancel',
  '▁activ',
  '▁mission'],
 ['▁summ',
  'ari',
  '▁autom',
  'at',
  '▁flight',
  '▁plan',
  '▁assign',
  '▁descri',
  'pt',
  '▁sched',
  'ul',
  '▁flight',
  '▁manual',
  '▁assign',
  '▁u',
  'av',
  '▁sing',
  'l',
  '▁u',
  'av',
  'flight',
  '▁plan',
  '▁sched',
  'ul',
  '▁shall',
  '▁assign',
  '▁rout',
  '▁autom',
  'at',
  '▁u',
  'av'],
 ['▁packag',
  '▁edu',
  '▁d',
  'ron',
  'olog',
  '▁servic',
  '▁ext',
  'ens',
  '▁mission',
  'plan',
  '▁import',
  '▁java',
  '▁io',
  'except',
  '▁import',
  '▁java',
  '▁util',
  '▁hash',
  '▁map',
  '▁import',
  '▁java',
  '▁util',
  '▁map',
  '▁import',
  '▁java',
  '▁util',
  '▁map',
  '▁ent',
  'ri',
  '▁import',
  '▁org',
  '▁json',
  '▁json',
  'except',
  '▁import',
  '▁edu',
  '▁d',
  'ron',
  'olog',
  '▁core',
  '▁d',
  'ron',
  'olog',
  '▁constant',
  '▁import',
  '▁edu',
  '▁d',
  'ron',
  'olog',
  '▁core',
  '▁co',
  'ordin',
  '▁l',
  'la',
  '▁co',
  'ordin',
  '▁import',
  '▁edu',
  '▁d',
  'ron',
  'olog',
  '▁core',
  '▁veh',
  'ic',
  'l',
  '▁iu',
  'av',
  'pro',
  'xi',
  '▁import',
  '▁edu',
  '▁d',
  'ron',
  'olog',
  '▁servic',
  '▁core',
  '▁util',
  '▁d',
  'ron',
  'olog',
  '▁servic',
  '▁except',
  '▁import',
  '▁edu',
  '▁d',
  'ron',
  'olog',
  '▁servic',
  '▁ext',
  'ens',
  '▁mission',
  'plan',
  '▁mission',
  '▁execut',
  '▁except',
  '▁import',
  '▁edu',
  '▁d',
  'ron',
  'olog',
  '▁servic',
  '▁ext',
  'ens',
  '▁mission',
  'plan',
  '▁plan',
  '▁i',
  'execut',
  '▁mission',
  '▁plan',
  '▁import',
  '▁edu',
  '▁d',
  'ron',
  'olog',
  '▁servic',
  '▁ext',
  'ens',
  '▁mission',
  'plan',
  '▁plan',
  '▁mission',
  '▁util',
  '▁import',
  '▁edu',
  '▁d',
  'ron',
  'olog',
  '▁servic',
  '▁ext',
  'ens',
  '▁mission',
  'plan',
  '▁plan',
  '▁u',
  'av',
  'miss',
  '▁plan',
  '▁import',
  '▁edu',
  '▁d',
  'ron',
  'olog',
  '▁servic',
  '▁ext',
  'ens',
  '▁mission',
  'plan',
  '▁sync',
  '▁synchron',
  '▁man',
  'ag',
  '▁import',
  '▁edu',
  '▁d',
  'ron',
  'olog',
  '▁servic',
  '▁ext',
  'ens',
  '▁mission',
  'plan',
  '▁task',
  '▁task',
  '▁factor',
  'i',
  '▁import',
  '▁edu',
  '▁d',
  'ron',
  'olog',
  '▁servic',
  '▁instanc',
  '▁drones',
  'et',
  'up',
  '▁drone',
  '▁setup',
  '▁servic',
  '▁import',
  '▁net',
  '▁log',
  '▁i',
  'logg',
  '▁import',
  '▁net',
  '▁log',
  '▁logger',
  '▁provid',
  '▁man',
  'ag',
  '▁mission',
  '▁plan',
  '▁mission',
  '▁plan',
  '▁one',
  '▁code',
  '▁full',
  '▁mission',
  '▁plan',
  '▁code',
  '▁instanc',
  '▁one',
  '▁code',
  '▁u',
  'av',
  'miss',
  '▁plan',
  '▁code',
  '▁instanc',
  '▁u',
  'av',
  '▁mission',
  '▁plan',
  '▁u',
  'av',
  '▁individ',
  'u',
  '▁mission',
  '▁plan',
  '▁compos',
  '▁mission',
  '▁task',
  '▁ent',
  'ir',
  '▁mission',
  '▁plan',
  '▁load',
  '▁thread',
  '▁cre',
  'at',
  '▁check',
  '▁individ',
  'u',
  '▁u',
  'av',
  'miss',
  '▁plan',
  '▁determin',
  '▁start',
  '▁next',
  '▁task',
  '▁author',
  '▁j',
  'ane',
  '▁cl',
  'eland',
  '▁hu',
  'ang',
  '▁deprec',
  '▁public',
  '▁class',
  '▁full',
  '▁mission',
  '▁plan',
  '▁implement',
  '▁i',
  'execut',
  '▁mission',
  '▁plan',
  '▁privat',
  '▁static',
  '▁final',
  '▁i',
  'logg',
  '▁logger',
  '▁logger',
  '▁provid',
  '▁get',
  '▁logger',
  '▁full',
  '▁mission',
  '▁plan',
  '▁class',
  '▁privat',
  '▁map',
  '▁string',
  '▁u',
  'av',
  'miss',
  '▁plan',
  '▁u',
  'av',
  '▁mission',
  '▁plan',
  '▁privat',
  '▁synchron',
  '▁man',
  'ag',
  '▁synch',
  '▁point',
  '▁mgr',
  '▁privat',
  '▁string',
  '▁mission',
  '▁construct',
  '▁co',
  'ordin',
  '▁mission',
  '▁instanc',
  '▁mission',
  '▁consist',
  '▁one',
  '▁u',
  'av',
  '▁set',
  '▁assign',
  '▁task',
  '▁synchron',
  '▁point',
  '▁param',
  '▁mission',
  '▁public',
  '▁full',
  '▁mission',
  '▁plan',
  '▁string',
  '▁mission',
  '▁mission',
  '▁mission',
  '▁u',
  'av',
  '▁mission',
  '▁plan',
  '▁new',
  '▁hash',
  '▁map',
  '▁synch',
  '▁point',
  '▁mgr',
  '▁synchron',
  '▁man',
  'ag',
  '▁get',
  '▁instanc',
  '▁load',
  '▁mission',
  '▁json',
  '▁file',
  '▁current',
  '▁hard',
  '▁code',
  '▁param',
  '▁mission',
  '▁throw',
  '▁mission',
  '▁execut',
  '▁except',
  '▁privat',
  '▁void',
  '▁load',
  '▁mission',
  '▁string',
  '▁mission',
  '▁throw',
  '▁mission',
  '▁execut',
  '▁except',
  '▁json',
  'miss',
  '▁plan',
  '▁reader',
  '▁json',
  '▁reader',
  '▁new',
  '▁json',
  'miss',
  '▁plan',
  '▁reader',
  '▁tri',
  '▁json',
  '▁reader',
  '▁pars',
  '▁mission',
  '▁mission',
  '▁catch',
  '▁io',
  'except',
  '▁json',
  'except',
  '▁throw',
  '▁new',
  '▁mission',
  '▁execut',
  '▁except',
  '▁get',
  '▁mess',
  'ag',
  '▁add',
  '▁add',
  'it',
  '▁u',
  'av',
  '▁mission',
  '▁plan',
  '▁cre',
  'at',
  '▁code',
  '▁u',
  'av',
  'miss',
  '▁task',
  '▁code',
  '▁instanc',
  '▁pass',
  '▁refer',
  '▁code',
  '▁synch',
  '▁point',
  '▁mgr',
  '▁code',
  '▁param',
  '▁u',
  'av',
  '▁u',
  'av',
  '▁throw',
  '▁mission',
  '▁execut',
  '▁except',
  '▁public',
  '▁void',
  '▁add',
  '▁u',
  'av',
  '▁string',
  '▁u',
  'av',
  '▁throw',
  '▁mission',
  '▁execut',
  '▁except',
  '▁u',
  'av',
  'miss',
  '▁plan',
  '▁plan',
  '▁new',
  '▁u',
  'av',
  'miss',
  '▁plan',
  '▁u',
  'av',
  '▁synch',
  '▁point',
  '▁mgr',
  '▁u',
  'av',
  '▁mission',
  '▁plan',
  '▁contain',
  '▁key',
  '▁u',
  'av',
  '▁throw',
  '▁new',
  '▁mission',
  '▁execut',
  '▁except',
  '▁mission',
  '▁plan',
  '▁u',
  'av',
  '▁u',
  'av',
  '▁al',
  'read',
  'i',
  '▁def',
  'in',
  '▁");',
  '▁u',
  'av',
  '▁mission',
  '▁plan',
  '▁put',
  '▁u',
  'av',
  '▁plan',
  '▁public',
  '▁void',
  '▁remov',
  '▁u',
  'av',
  '▁string',
  '▁u',
  'av',
  '▁u',
  'av',
  '▁mission',
  '▁plan',
  '▁remov',
  '▁u',
  'av',
  '▁/**',
  '▁assign',
  '▁task',
  '▁spec',
  'if',
  '▁u',
  'av',
  '▁param',
  '▁u',
  'av',
  '▁u',
  'av',
  '▁ident',
  'ifi',
  '▁param',
  '▁task',
  '▁task',
  '▁perform',
  '▁rout',
  '▁waypoint',
  '▁synchron',
  '▁flight',
  '▁pattern',
  '▁param',
  '▁task',
  '▁task',
  '▁spec',
  'if',
  '▁spec',
  'if',
  '▁waypoint',
  '▁rout',
  '▁name',
  '▁etc',
  '▁throw',
  '▁mission',
  '▁execut',
  '▁except',
  '▁public',

In [45]:
general2vec.dictionary

In [46]:
general2vec.df_all_system.head(1)

,ids,filenames,text,type,conv,bpe8k,bpe32k,bpe128k
0,/Users/loganfecko/Desktop/Summer_Research/trac...,RE-616.txt,[SUMMARY]\nLogging of GCS related events\n[DES...,req,summari log gcs relat event descript activ log...,▁sum m ari ▁log ▁g cs ▁rel at ▁event ▁descri p...,▁sum m ari ▁log ▁g cs ▁rel at ▁event ▁descri p...,▁summ ari ▁log ▁gcs ▁relat ▁event ▁descri pt ▁...

In [47]:
general2vec.df_all_system.shape #data final tensor

(242, 8)

In [48]:
#tst for libest
path_to_ground_truth = '../dvc-data/systems/dronology/mappings/ground_truth.txt'
general2vec.ground_truth_processing(path_to_ground_truth)

[('RE-100.txt', 'PlanPool.java'),
 ('RE-101.txt', 'FlightZoneManager2.java'),
 ('RE-101.txt', 'PlanPoolManager.java'),
 ('RE-103.txt', 'FlightZoneManager2.java'),
 ('RE-114.txt', 'AFMainLayout.java'),
 ('RE-114.txt', 'AFMapComponent.java'),
 ('RE-25.txt', 'AbstractDrone.java'),
 ('RE-25.txt', 'PhysicalDrone.java'),
 ('RE-25.txt', 'PhysicalDroneFleetFactory.java'),
 ('RE-25.txt', 'VirtualDrone.java'),
 ('RE-25.txt', 'VirtualDroneFleetFactory.java'),
 ('RE-28.txt', 'PlanPool.java'),
 ('RE-28.txt', 'PlanPoolManager.java'),
 ('RE-36.txt', 'DroneFleetManager.java'),
 ('RE-36.txt', 'PhysicalDroneFleetFactory.java'),
 ('RE-36.txt', 'VirtualDroneFleetFactory.java'),
 ('RE-424.txt', 'FlightZoneManager2.java'),
 ('RE-501.txt', 'DroneSimulatorServiceInstance.java'),
 ('RE-501.txt', 'DronologyPersistenceUtil.java'),
 ('RE-501.txt', 'FlightRoute.java'),
 ('RE-501.txt', 'FlightRouteInfo.java'),
 ('RE-501.txt', 'FlightRoutePersistenceProvider.java'),
 ('RE-501.txt', 'FlightRouteplanningService.java'),
 ('RE-501.txt', 'FlightRouteplanningServiceInstance.java'),
 ('RE-501.txt', 'FlightRouteplanningServiceRemoteFacade.java'),
 ('RE-501.txt', 'IFlightRoute.java'),
 ('RE-501.txt', 'IFlightRouteplanningServiceInstance.java'),
 ('RE-501.txt', 'Waypoint.java'),
 ('RE-505.txt', 'AbstractFileTransmitServiceInstance.java'),
 ('RE-505.txt', 'FlightRouteplanningServiceInstance.java'),
 ('RE-508.txt', 'FlightRoute.java'),
 ('RE-510.txt', 'LlaCoordinate.java'),
 ('RE-510.txt', 'NVector.java'),
 ('RE-510.txt', 'PVector.java'),
 ('RE-516.txt', 'LlaCoordinate.java'),
 ('RE-516.txt', 'NVector.java'),
 ('RE-516.txt', 'PVector.java'),
 ('RE-541.txt', 'AbstractFlightPattern.java'),
 ('RE-541.txt', 'CoordinatedLandingPattern.java'),
 ('RE-541.txt', 'CoordinatedTakeoffPattern.java'),
 ('RE-541.txt', 'FullMissionPlan.java'),
 ('RE-541.txt', 'IFlightPattern.java'),
 ('RE-541.txt', 'IMissionTask.java'),
 ('RE-541.txt', 'PatternFactory.java'),
 ('RE-541.txt', 'PatternTask.java'),
 ('RE-541.txt', 'SyncConstants.java'),
 ('RE-541.txt', 'TaskList.java'),
 ('RE-545.txt', 'FullMissionPlan.java'),
 ('RE-545.txt', 'MissionController.java'),
 ('RE-547.txt', 'FlightZoneManager2.java'),
 ('RE-549.txt', 'FlightZoneManager2.java'),
 ('RE-549.txt', 'PlanPoolManager.java'),
 ('RE-551.txt', 'FlightZoneManager2.java'),
 ('RE-551.txt', 'PlanPoolManager.java'),
 ('RE-555.txt', 'DroneException.java'),
 ('RE-555.txt', 'DroneFleetManager.java'),
 ('RE-555.txt', 'DroneFlightStateManager.java'),
 ('RE-555.txt', 'DroneInitializationInfo.java'),
 ('RE-555.txt', 'DroneSetupService.java'),
 ('RE-555.txt', 'DroneSetupServiceInstance.java'),
 ('RE-555.txt', 'DroneSetupServiceRemoteFacade.java'),
 ('RE-555.txt', 'DroneSimulatorServiceInstance.java'),
 ('RE-555.txt', 'DronologyServiceRunner.java'),
 ('RE-555.txt', 'DummyLockObject.java'),
 ('RE-555.txt', 'FlightInfo.java'),
 ('RE-555.txt', 'FlightInfoCreator.java'),
 ('RE-555.txt', 'FlightManagerService.java'),
 ('RE-555.txt', 'FlightManagerServiceInstance.java'),
 ('RE-555.txt', 'FlightManagerServiceRemoteFacade.java'),
 ('RE-555.txt', 'FlightPlan.java'),
 ('RE-555.txt', 'FlightPlanFactory.java'),
 ('RE-555.txt', 'FlightZoneManager2.java'),
 ('RE-555.txt', 'IDroneSetupRemoteService.java'),
 ('RE-555.txt', 'IDroneSetupServiceInstance.java'),
 ('RE-555.txt', 'IFlightManagerRemoteService.java'),
 ('RE-555.txt', 'IFlightManagerServiceInstance.java'),
 ('RE-555.txt', 'IFlightPlan.java'),
 ('RE-555.txt', 'IManagedDroneStateChangeListener.java'),
 ('RE-555.txt', 'IPlanStatusChangeListener.java'),
 ('RE-555.txt', 'IStartstrategy.java'),
 ('RE-555.txt', 'IStopStrategy.java'),
 ('RE-555.txt', 'LandingStrategy.java'),
 ('RE-555.txt', 'ManagedHashTableList.java'),
 ('RE-555.txt', 'PhysicalDrone.java'),
 ('RE-555.txt', 'PlanPool.java'),
 ('RE-555.txt', 'PlanPoolManager.java'),
 ('RE-555.txt', 'RemoteInfoFactory.java'),
 ('RE-555.txt', 'SoloDirector.java'),
 ('RE-555.txt', 'VirtualDrone.java'),
 ('RE-555.txt', 'Waypoint.java'),
 ('RE-574.txt', 'PhysicalDrone.java'),
 ('RE-574.txt', 'PhysicalDroneFleetFactory.java'),
 ('RE-576.txt', 'VirtualDrone.java'),
 ('RE-576.txt', 'VirtualDroneFleetFactory.java'),
 ('RE-587.txt', 'DroneFleetManager.java'),
 ('RE-587.txt', 'PlanPoolManager.java'),
 ('RE-589.txt', 'DronologyConstants.java'),
 ('RE-594.txt', 'VirtualDrone.java'),
 ('RE-595.txt', 'FlightSimulator.java'),
 ('RE-595.txt', 'NVECSimulator.java'),
 ('RE-595.txt', 'NvecInterpolator.java'),
 ('RE-595.txt', 'SimpleSimulator.java'),
 ('RE-596.txt', 'VirtualDrone.java'),
 ('RE-597.txt', 'DroneVoltageSimulator.java'),
 ('RE-611.txt', 'FlightPlan.java'),
 ('RE-611.txt', 'ManagedDrone.java'),
 ('RE-611.txt', 'PhysicalDrone.java'),
 ('RE-611.txt', 'PlanPool.java'),
 ('RE-616.txt', 'AbstractDroneCommand.java'),
 ('RE-616.txt', 'DispatchQueueManager.java'),
 ('RE-616.txt', 'DroneFlightStateManager.java'),
 ('RE-616.txt', 'GroundstationConnector.java'),
 ('RE-616.txt', 'PhysicalDrone.java'),
 ('RE-616.txt', 'ReadDispatcher.java'),
 ('RE-616.txt', 'WriteDispatcher.java'),
 ('RE-626.txt', 'DroneSetupService.java'),
 ('RE-626.txt', 'DroneSetupServiceInstance.java'),
 ('RE-626.txt', 'DroneSetupServiceRemoteFacade.java'),
 ('RE-626.txt', 'IDroneSetupRemoteService.java'),
 ('RE-628.txt', 'AbstractFileTransmitServerService.java'),
 ('RE-628.txt', 'FlightRouteplanningService.java'),
 ('RE-630.txt', 'DroneSetupService.java'),
 ('RE-630.txt', 'FlightManagerService.java'),
 ('RE-630.txt', 'FlightManagerServiceInstance.java'),
 ('RE-630.txt', 'FlightManagerServiceRemoteFacade.java'),
 ('RE-630.txt', 'IFlightManagerRemoteService.java'),
 ('RE-630.txt', 'IFlightManagerServiceInstance.java'),
 ('RE-634.txt', 'AbstractFileTransmitServerService.java'),
 ('RE-634.txt', 'FlightRouteplanningService.java'),
 ('RE-634.txt', 'FlightRouteplanningServiceInstance.java'),
 ('RE-634.txt', 'FlightRouteplanningServiceRemoteFacade.java'),
 ('RE-634.txt', 'IFlightRouteplanningServiceInstance.java'),
 ('RE-637.txt', 'FlightManagerService.java'),
 ('RE-639.txt', 'IMissionPlanningRemoteService.java'),
 ('RE-639.txt', 'MissionPlanningService.java'),
 ('RE-639.txt', 'MissionPlanningServiceRemoteFacade.java'),
 ('RE-643.txt', 'AFMapComponent.java'),
 ('RE-646.txt', 'AFAssignRouteComponent.java'),
 ('RE-646.txt', 'AFDragLayout.java'),
 ('RE-649.txt', 'AFAssignRouteComponent.java'),
 ('RE-649.txt', 'AFDragLayout.java'),
 ('RE-649.txt', 'AFInfoBox.java'),
 ('RE-649.txt', 'FlightManagerService.java'),
 ('RE-649.txt', 'FlightManagerServiceInstance.java'),
 ('RE-649.txt', 'FlightManagerServiceRemoteFacade.java'),
 ('RE-649.txt', 'FlightZoneManager2.java'),
 ('RE-649.txt', 'IFlightManagerRemoteService.java'),
 ('RE-649.txt', 'IFlightManagerServiceInstance.java'),
 ('RE-649.txt', 'PlanPool.java'),
 ('RE-649.txt', 'PlanPoolManager.java'),
 ('RE-656.txt', 'AFAssignRouteComponent.java'),
 ('RE-656.txt', 'AFDragLayout.java'),
 ('RE-672.txt', 'MapDrawingUtil.java'),
 ('RE-677.txt', 'DroneSetupService.java'),
 ('RE-681.txt', 'AFControlsComponent.java'),
 ('RE-681.txt', 'AFEmergencyComponent.java'),
 ('RE-681.txt', 'AFInfoBox.java'),
 ('RE-681.txt', 'AFInfoPanel.java'),
 ('RE-681.txt', 'AFMapComponent.java'),
 ('RE-689.txt', 'AFMapComponent.java'),
 ('RE-689.txt', 'MapDrawingUtil.java'),
 ('RE-691.txt', 'AFEmergencyComponent.java'),
 ('RE-691.txt', 'AFInfoBox.java'),
 ('RE-693.txt', 'AFEmergencyComponent.java'),
 ('RE-695.txt', 'AFFollowBar.java'),
 ('RE-695.txt', 'AFMapComponent.java'),
 ('RE-701.txt', 'AbstractDroneCommand.java'),
 ('RE-701.txt', 'AbstractUAVMessage.java'),
 ('RE-701.txt', 'ArtifactIdentifier.java'),
 ('RE-701.txt', 'DispatchQueueManager.java'),
 ('RE-701.txt', 'DroneConnectorService.java'),
 ('RE-701.txt', 'DroneConnectorServiceInstance.java'),
 ('RE-701.txt', 'DroneFlightStateManager.java'),
 ('RE-701.txt', 'DroneMonitoringService.java'),
 ('RE-701.txt', 'DroneMonitoringServiceInstance.java'),
 ('RE-701.txt', 'DronologyMonitoringManager.java'),
 ('RE-701.txt', 'DronologyServiceRunner.java'),
 ('RE-701.txt', 'FlightPlan.java'),
 ('RE-701.txt', 'GroundstationConnector.java'),
 ('RE-701.txt', 'IDroneConnectorServiceInstance.java'),
 ('RE-701.txt', 'IDroneMonitoringServiceInstance.java'),
 ('RE-701.txt', 'IFlightPlan.java'),
 ('RE-701.txt', 'IMonitorableMessage.java'),
 ('RE-701.txt', 'IMonitoringDataHandler.java'),
 ('RE-701.txt', 'IRemoteMonitoringMessageHandler.java'),
 ('RE-701.txt', 'IncommingGroundstationConnectionServer.java'),
 ('RE-701.txt', 'ManagedDrone.java'),
 ('RE-701.txt', 'MessageMarshaller.java'),
 ('RE-701.txt', 'MonitoringConnectionTester.java'),
 ('RE-701.txt', 'MonitoringDispatchThread.java'),
 ('RE-701.txt', 'PhysicalDrone.java'),
 ('RE-701.txt', 'PhysicalDroneFleetFactory.java'),
 ('RE-701.txt', 'PlanPoolManager.java'),
 ('RE-701.txt', 'RemindsConnector.java'),
 ('RE-701.txt', 'RemoteMessageHandler.java'),
 ('RE-701.txt', 'SendToSubscriberCallable.java'),
 ('RE-701.txt', 'SimpleTakeoffFlightPlan.java'),
 ('RE-701.txt', 'StateMessageTypeAdapter.java'),
 ('RE-701.txt', 'UAVAcknowledgeMessage.java'),
 ('RE-701.txt', 'UAVMonitorableMessage.java'),
 ('RE-701.txt', 'UAVPlanChangeMessage.java'),
 ('RE-701.txt', 'UAVStateChangeMessage.java'),
 ('RE-701.txt', 'VirtualDroneFleetFactory.java'),
 ('RE-706.txt', 'ArtifactIdentifier.java'),
 ('RE-706.txt', 'IMonitorableMessage.java'),
 ('RE-706.txt', 'UAVMonitorableMessage.java'),
 ('RE-709.txt', 'ConnectionRequestMessage.java'),
 ('RE-709.txt', 'DispatchQueueManager.java'),
 ('RE-709.txt', 'DronologyServiceRunner.java'),
 ('RE-709.txt', 'GroundstationConnector.java'),
 ('RE-709.txt', 'IncommingGroundstationConnectionServer.java'),
 ('RE-709.txt', 'PhysicalDroneFleetFactory.java'),
 ('RE-709.txt', 'RuntimeDroneTypes.java'),
 ('RE-714.txt', 'AbstractDroneCommand.java'),
 ('RE-714.txt', 'CommandIds.java'),
 ('RE-714.txt', 'ConnectionRequestMessage.java'),
 ('RE-714.txt', 'GoToCommand.java'),
 ('RE-714.txt', 'GroundstationConnector.java'),
 ('RE-714.txt', 'IDroneCommand.java'),
 ('RE-714.txt', 'ReadDispatcher.java'),
 ('RE-714.txt', 'SetGimbalRotationCommand.java'),
 ('RE-714.txt', 'SetGimbalTargetCommand.java'),
 ('RE-714.txt', 'SetGroundSpeedCommand.java'),
 ('RE-714.txt', 'SetMonitoringFrequencyCommand.java'),
 ('RE-714.txt', 'SetStateFrequencyCommand.java'),
 ('RE-714.txt', 'SetVelocityCommand.java'),
 ('RE-714.txt', 'TakeoffCommand.java'),
 ('RE-714.txt', 'UAVHandshakeMessage.java'),
 ('RE-722.txt', 'UAVMessageFactory.java'),
 ('RE-722.txt', 'UAVModeChangeMessage.java'),
 ('RE-722.txt', 'UAVMonitoringMessage.java'),
 ('RE-722.txt', 'UAVStateMessage.java'),
 ('RE-729.txt', 'AbstractDroneCommand.java'),
 ('RE-729.txt', 'CommandIds.java'),
 ('RE-729.txt', 'EmergencyStopCommand.java'),
 ('RE-729.txt', 'GoToCommand.java'),
 ('RE-729.txt', 'IDroneCommand.java'),
 ('RE-729.txt', 'LandCommand.java'),
 ('RE-729.txt', 'SetGroundSpeedCommand.java'),
 ('RE-729.txt', 'SetMonitoringFrequencyCommand.java'),
 ('RE-729.txt', 'SetStateFrequencyCommand.java'),
 ('RE-729.txt', 'SetVelocityCommand.java'),
 ('RE-729.txt', 'TakeoffCommand.java'),
 ('RE-759.txt', 'AFInfoPanel.java'),
 ('RE-759.txt', 'AFMainLayout.java'),
 ('RE-759.txt', 'AFMapViewOperations.java'),
 ('RE-759.txt', 'AFMissionOperations.java'),
 ('RE-759.txt', 'AbstractFlightPattern.java'),
 ('RE-759.txt', 'AbstractMissionTask.java'),
 ('RE-759.txt', 'CollisionInfo.java'),
 ('RE-759.txt', 'CommandIds.java'),
 ('RE-759.txt', 'CoordinatedLandingPattern.java'),
 ('RE-759.txt', 'CoordinatedTakeoffPattern.java'),
 ('RE-759.txt', 'DelayTask.java'),
 ('RE-759.txt', 'DistanceChecker.java'),
 ('RE-759.txt', 'EmergencyStopCommand.java'),
 ('RE-759.txt', 'FlightManagerService.java'),
 ('RE-759.txt', 'FlightManagerServiceInstance.java'),
 ('RE-759.txt', 'FlightManagerServiceRemoteFacade.java'),
 ('RE-759.txt', 'FlightZoneManager2.java'),
 ('RE-759.txt', 'FullMissionPlan.java'),
 ('RE-759.txt', 'IFlightManagerRemoteService.java'),
 ('RE-759.txt', 'IFlightManagerServiceInstance.java'),
 ('RE-759.txt', 'IFlightPattern.java'),
 ('RE-759.txt', 'IMissionPlan.java'),
 ('RE-759.txt', 'IMissionPlanningRemoteService.java'),
 ('RE-759.txt', 'IMissionPlanningServiceInstance.java'),
 ('RE-759.txt', 'IMissionTask.java'),
 ('RE-759.txt', 'IUAVProxy.java'),
 ('RE-759.txt', 'JSONMissionPlanReader.java'),
 ('RE-759.txt', 'LandTask.java'),
 ('RE-759.txt', 'ManagedDrone.java'),
 ('RE-759.txt', 'MissionController.java'),
 ('RE-759.txt', 'MissionExecutionException.java'),
 ('RE-759.txt', 'MissionHandler.java'),
 ('RE-759.txt', 'MissionPlanningService.java'),
 ('RE-759.txt', 'MissionPlanningServiceInstance.java'),
 ('RE-759.txt', 'MissionPlanningServiceRemoteFacade.java'),
 ('RE-759.txt', 'MissionUtil.java'),
 ('RE-759.txt', 'MonitoringConnectionTester.java'),
 ('RE-759.txt', 'PatternFactory.java'),
 ('RE-759.txt', 'PatternTask.java'),
 ('RE-759.txt', 'RemoteManager.java'),
 ('RE-759.txt', 'RouteTask.java'),
 ('RE-759.txt', 'ServiceIds.java'),
 ('RE-759.txt', 'SimpleCheckerMessageHandler.java'),
 ('RE-759.txt', 'SimpleMonitor.java'),
 ('RE-759.txt', 'SyncConstants.java'),
 ('RE-759.txt', 'SyncTask.java'),
 ('RE-759.txt', 'SynchronizationManager.java'),
 ('RE-759.txt', 'SynchronizationPoint.java'),
 ('RE-759.txt', 'SynchronizationState.java'),
 ('RE-759.txt', 'TakeoffTask.java'),
 ('RE-759.txt', 'TaskFactory.java'),
 ('RE-759.txt', 'TaskList.java'),
 ('RE-759.txt', 'UAVMissionPlan.java'),
 ('RE-759.txt', 'UAVMonitorableMessage.java'),
 ('RE-759.txt', 'UAVProxy.java'),
 ('RE-759.txt', 'WaypointTask.java'),
 ('RE-759.txt', 'WriteDispatcher.java'),
 ('RE-766.txt', 'AFMainLayout.java'),
 ('RE-766.txt', 'AFMapComponent.java'),
 ('RE-77.txt', 'AbstractDrone.java'),
 ('RE-77.txt', 'AbstractDroneCommand.java'),
 ('RE-77.txt', 'AbstractPosition.java'),
 ('RE-77.txt', 'CommandIds.java'),
 ('RE-77.txt', 'DroneException.java'),
 ('RE-77.txt', 'DroneFleetManager.java'),
 ('RE-77.txt', 'DroneFlightStateManager.java'),
 ('RE-77.txt', 'DroneInitializationInfo.java'),
 ('RE-77.txt', 'DroneSetupService.java'),
 ('RE-77.txt', 'DroneSetupServiceInstance.java'),
 ('RE-77.txt', 'DroneSetupServiceRemoteFacade.java'),
 ('RE-77.txt', 'DroneSimulatorServiceInstance.java'),
 ('RE-77.txt', 'DronologyConstants.java'),
 ('RE-77.txt', 'DronologyPersistenceUtil.java'),
 ('RE-77.txt', 'DronologyServiceRunner.java'),
 ('RE-77.txt', 'DummyLockObject.java'),
 ('RE-77.txt', 'FileManager.java'),
 ('RE-77.txt', 'FlightInfo.java'),
 ('RE-77.txt', 'FlightInfoCreator.java'),
 ('RE-77.txt', 'FlightManagerService.java'),
 ('RE-77.txt', 'FlightManagerServiceInstance.java'),
 ('RE-77.txt', 'FlightManagerServiceRemoteFacade.java'),
 ('RE-77.txt', 'FlightPlan.java'),
 ('RE-77.txt', 'FlightPlanFactory.java'),
 ('RE-77.txt', 'FlightPlanInfo.java'),
 ('RE-77.txt', 'FlightRoute.java'),
 ('RE-77.txt', 'FlightRouteInfo.java'),
 ('RE-77.txt', 'FlightRouteplanningServiceInstance.java'),
 ('RE-77.txt', 'FlightZoneManager2.java'),
 ('RE-77.txt', 'FlyingFieldDemoScript.java'),
 ('RE-77.txt', 'GoToCommand.java'),
 ('RE-77.txt', 'IDrone.java'),
 ('RE-77.txt', 'IDroneCommand.java'),
 ('RE-77.txt', 'IDroneCommandHandler.java'),
 ('RE-77.txt', 'IDroneSetupRemoteService.java'),
 ('RE-77.txt', 'IDroneSetupServiceInstance.java'),
 ('RE-77.txt', 'IFlightManagerRemoteService.java'),
 ('RE-77.txt', 'IFlightManagerServiceInstance.java'),
 ('RE-77.txt', 'IFlightPlan.java'),
 ('RE-77.txt', 'IFlightRoute.java'),
 ('RE-77.txt', 'IManagedDroneStateChangeListener.java'),
 ('RE-77.txt', 'IMissionPlan.java'),
 ('RE-77.txt', 'IPlanStatusChangeListener.java'),
 ('RE-77.txt', 'IRemoteManager.java'),
 ('RE-77.txt', 'IStartstrategy.java'),
 ('RE-77.txt', 'IStopStrategy.java'),
 ('RE-77.txt', 'IUAVPropertyUpdateNotifier.java'),
 ('RE-77.txt', 'InfoNotification.java'),
 ('RE-77.txt', 'LandingStrategy.java'),
 ('RE-77.txt', 'LlaCoordinate.java'),
 ('RE-77.txt', 'ManagedDrone.java'),
 ('RE-77.txt', 'ManagedHashTableList.java'),
 ('RE-77.txt', 'NvecInterpolator.java'),
 ('RE-77.txt', 'PhysicalDrone.java'),
 ('RE-77.txt', 'PhysicalDroneFleetFactory.java'),
 ('RE-77.txt', 'PlanPool.java'),
 ('RE-77.txt', 'PlanPoolManager.java'),
 ('RE-77.txt', 'RemoteInfoFactory.java'),
 ('RE-77.txt', 'RemoteManager.java'),
 ('RE-77.txt', 'RemoteRMIRemoteObject.java'),
 ('RE-77.txt', 'RuntimeDroneTypes.java'),
 ('RE-77.txt', 'SetGimbalRotationCommand.java'),
 ('RE-77.txt', 'SetGimbalTargetCommand.java'),
 ('RE-77.txt', 'SetGroundSpeedCommand.java'),
 ('RE-77.txt', 'SetMonitoringFrequencyCommand.java'),
 ('RE-77.txt', 'SetStateFrequencyCommand.java'),
 ('RE-77.txt', 'SetVelocityCommand.java'),
 ('RE-77.txt', 'SimulatorFactory.java'),
 ('RE-77.txt', 'SoloDirector.java'),
 ('RE-77.txt', 'TakeoffCommand.java'),
 ('RE-77.txt', 'VirtualDrone.java'),
 ('RE-77.txt', 'WatchServiceRunner.java'),
 ('RE-77.txt', 'Waypoint.java'),
 ('RE-77.txt', 'WorkspaceInitializer.java'),
 ('RE-8.txt', 'AbstractDrone.java'),
 ('RE-8.txt', 'DroneFlightStateManager.java'),
 ('RE-8.txt', 'FlightZoneManager2.java'),
 ('RE-8.txt', 'IMissionPlanningServiceInstance.java'),
 ('RE-8.txt', 'ManagedDrone.java'),
 ('RE-8.txt', 'MissionPlanningService.java'),
 ('RE-8.txt', 'MissionPlanningServiceInstance.java'),
 ('RE-8.txt', 'ModeChangeMessageTypeAdapter.java'),
 ('RE-8.txt', 'PhysicalDrone.java'),
 ('RE-8.txt', 'SoloDirector.java'),
 ('RE-8.txt', 'StatusDispatchThread.java'),
 ('RE-8.txt', 'UAVMessageFactory.java'),
 ('RE-8.txt', 'UAVModeChangeMessage.java'),
 ('RE-80.txt', 'ManagedDrone.java'),
 ('RE-80.txt', 'PhysicalDrone.java'),
 ('RE-80.txt', 'SoloDirector.java'),
 ('RE-80.txt', 'VirtualDrone.java')]

In [49]:
#tst for sacp
general2vec.ground_truth_processing(parameters['path_mappings'], from_mappings = True)

[('RE-100', 'PlanPool'),
 ('RE-101', 'FlightZoneManager2'),
 ('RE-101', 'PlanPoolManager'),
 ('RE-103', 'FlightZoneManager2'),
 ('RE-114', 'AFMainLayout'),
 ('RE-114', 'AFMapComponent'),
 ('RE-25', 'AbstractDrone'),
 ('RE-25', 'PhysicalDrone'),
 ('RE-25', 'PhysicalDroneFleetFactory'),
 ('RE-25', 'VirtualDrone'),
 ('RE-25', 'VirtualDroneFleetFactory'),
 ('RE-28', 'PlanPool'),
 ('RE-28', 'PlanPoolManager'),
 ('RE-36', 'DroneFleetManager'),
 ('RE-36', 'PhysicalDroneFleetFactory'),
 ('RE-36', 'VirtualDroneFleetFactory'),
 ('RE-424', 'FlightZoneManager2'),
 ('RE-501', 'DroneSimulatorServiceInstance'),
 ('RE-501', 'DronologyPersistenceUtil'),
 ('RE-501', 'FlightRoute'),
 ('RE-501', 'FlightRouteInfo'),
 ('RE-501', 'FlightRoutePersistenceProvider'),
 ('RE-501', 'FlightRouteplanningService'),
 ('RE-501', 'FlightRouteplanningServiceInstance'),
 ('RE-501', 'FlightRouteplanningServiceRemoteFacade'),
 ('RE-501', 'IFlightRoute'),
 ('RE-501', 'IFlightRouteplanningServiceInstance'),
 ('RE-501', 'Waypoint'),
 ('RE-505', 'AbstractFileTransmitServiceInstance'),
 ('RE-505', 'FlightRouteplanningServiceInstance'),
 ('RE-508', 'FlightRoute'),
 ('RE-510', 'LlaCoordinate'),
 ('RE-510', 'NVector'),
 ('RE-510', 'PVector'),
 ('RE-516', 'LlaCoordinate'),
 ('RE-516', 'NVector'),
 ('RE-516', 'PVector'),
 ('RE-541', 'AbstractFlightPattern'),
 ('RE-541', 'CoordinatedLandingPattern'),
 ('RE-541', 'CoordinatedTakeoffPattern'),
 ('RE-541', 'FullMissionPlan'),
 ('RE-541', 'IFlightPattern'),
 ('RE-541', 'IMissionTask'),
 ('RE-541', 'PatternFactory'),
 ('RE-541', 'PatternTask'),
 ('RE-541', 'SyncConstants'),
 ('RE-541', 'TaskList'),
 ('RE-545', 'FullMissionPlan'),
 ('RE-545', 'MissionController'),
 ('RE-547', 'FlightZoneManager2'),
 ('RE-549', 'FlightZoneManager2'),
 ('RE-549', 'PlanPoolManager'),
 ('RE-551', 'FlightZoneManager2'),
 ('RE-551', 'PlanPoolManager'),
 ('RE-555', 'DroneException'),
 ('RE-555', 'DroneFleetManager'),
 ('RE-555', 'DroneFlightStateManager'),
 ('RE-555', 'DroneInitializationInfo'),
 ('RE-555', 'DroneSetupService'),
 ('RE-555', 'DroneSetupServiceInstance'),
 ('RE-555', 'DroneSetupServiceRemoteFacade'),
 ('RE-555', 'DroneSimulatorServiceInstance'),
 ('RE-555', 'DronologyServiceRunner'),
 ('RE-555', 'DummyLockObject'),
 ('RE-555', 'FlightInfo'),
 ('RE-555', 'FlightInfoCreator'),
 ('RE-555', 'FlightManagerService'),
 ('RE-555', 'FlightManagerServiceInstance'),
 ('RE-555', 'FlightManagerServiceRemoteFacade'),
 ('RE-555', 'FlightPlan'),
 ('RE-555', 'FlightPlanFactory'),
 ('RE-555', 'FlightZoneManager2'),
 ('RE-555', 'IDroneSetupRemoteService'),
 ('RE-555', 'IDroneSetupServiceInstance'),
 ('RE-555', 'IFlightManagerRemoteService'),
 ('RE-555', 'IFlightManagerServiceInstance'),
 ('RE-555', 'IFlightPlan'),
 ('RE-555', 'IManagedDroneStateChangeListener'),
 ('RE-555', 'IPlanStatusChangeListener'),
 ('RE-555', 'IStartstrategy'),
 ('RE-555', 'IStopStrategy'),
 ('RE-555', 'LandingStrategy'),
 ('RE-555', 'ManagedHashTableList'),
 ('RE-555', 'PhysicalDrone'),
 ('RE-555', 'PlanPool'),
 ('RE-555', 'PlanPoolManager'),
 ('RE-555', 'RemoteInfoFactory'),
 ('RE-555', 'SoloDirector'),
 ('RE-555', 'VirtualDrone'),
 ('RE-555', 'Waypoint'),
 ('RE-574', 'PhysicalDrone'),
 ('RE-574', 'PhysicalDroneFleetFactory'),
 ('RE-576', 'VirtualDrone'),
 ('RE-576', 'VirtualDroneFleetFactory'),
 ('RE-587', 'DroneFleetManager'),
 ('RE-587', 'PlanPoolManager'),
 ('RE-589', 'DronologyConstants'),
 ('RE-594', 'VirtualDrone'),
 ('RE-595', 'FlightSimulator'),
 ('RE-595', 'NVECSimulator'),
 ('RE-595', 'NvecInterpolator'),
 ('RE-595', 'SimpleSimulator'),
 ('RE-596', 'VirtualDrone'),
 ('RE-597', 'DroneVoltageSimulator'),
 ('RE-611', 'FlightPlan'),
 ('RE-611', 'ManagedDrone'),
 ('RE-611', 'PhysicalDrone'),
 ('RE-611', 'PlanPool'),
 ('RE-616', 'AbstractDroneCommand'),
 ('RE-616', 'DispatchQueueManager'),
 ('RE-616', 'DroneFlightStateManager'),
 ('RE-616', 'GroundstationConnector'),
 ('RE-616', 'PhysicalDrone'),
 ('RE-616', 'ReadDispatcher'),
 ('RE-616', 'WriteDispatcher'),
 ('RE-626', 'DroneSetupService'),
 ('RE-626', 'DroneSetupServiceInstance'),
 ('RE-626', 'DroneSetupServiceRemoteFacade'),
 ('RE-626', 'IDroneSetupRemoteService'),
 ('RE-628', 'AbstractFileTransmitServerService'),
 ('RE-628', 'FlightRouteplanningService'),
 ('RE-630', 'DroneSetupService'),
 ('RE-630', 'FlightManagerService'),
 ('RE-630', 'FlightManagerServiceInstance'),
 ('RE-630', 'FlightManagerServiceRemoteFacade'),
 ('RE-630', 'IFlightManagerRemoteService'),
 ('RE-630', 'IFlightManagerServiceInstance'),
 ('RE-634', 'AbstractFileTransmitServerService'),
 ('RE-634', 'FlightRouteplanningService'),
 ('RE-634', 'FlightRouteplanningServiceInstance'),
 ('RE-634', 'FlightRouteplanningServiceRemoteFacade'),
 ('RE-634', 'IFlightRouteplanningServiceInstance'),
 ('RE-637', 'FlightManagerService'),
 ('RE-639', 'IMissionPlanningRemoteService'),
 ('RE-639', 'MissionPlanningService'),
 ('RE-639', 'MissionPlanningServiceRemoteFacade'),
 ('RE-643', 'AFMapComponent'),
 ('RE-646', 'AFAssignRouteComponent'),
 ('RE-646', 'AFDragLayout'),
 ('RE-649', 'AFAssignRouteComponent'),
 ('RE-649', 'AFDragLayout'),
 ('RE-649', 'AFInfoBox'),
 ('RE-649', 'FlightManagerService'),
 ('RE-649', 'FlightManagerServiceInstance'),
 ('RE-649', 'FlightManagerServiceRemoteFacade'),
 ('RE-649', 'FlightZoneManager2'),
 ('RE-649', 'IFlightManagerRemoteService'),
 ('RE-649', 'IFlightManagerServiceInstance'),
 ('RE-649', 'PlanPool'),
 ('RE-649', 'PlanPoolManager'),
 ('RE-656', 'AFAssignRouteComponent'),
 ('RE-656', 'AFDragLayout'),
 ('RE-672', 'MapDrawingUtil'),
 ('RE-677', 'DroneSetupService'),
 ('RE-681', 'AFControlsComponent'),
 ('RE-681', 'AFEmergencyComponent'),
 ('RE-681', 'AFInfoBox'),
 ('RE-681', 'AFInfoPanel'),
 ('RE-681', 'AFMapComponent'),
 ('RE-689', 'AFMapComponent'),
 ('RE-689', 'MapDrawingUtil'),
 ('RE-691', 'AFEmergencyComponent'),
 ('RE-691', 'AFInfoBox'),
 ('RE-693', 'AFEmergencyComponent'),
 ('RE-695', 'AFFollowBar'),
 ('RE-695', 'AFMapComponent'),
 ('RE-701', 'AbstractDroneCommand'),
 ('RE-701', 'AbstractUAVMessage'),
 ('RE-701', 'ArtifactIdentifier'),
 ('RE-701', 'DispatchQueueManager'),
 ('RE-701', 'DroneConnectorService'),
 ('RE-701', 'DroneConnectorServiceInstance'),
 ('RE-701', 'DroneFlightStateManager'),
 ('RE-701', 'DroneMonitoringService'),
 ('RE-701', 'DroneMonitoringServiceInstance'),
 ('RE-701', 'DronologyMonitoringManager'),
 ('RE-701', 'DronologyServiceRunner'),
 ('RE-701', 'FlightPlan'),
 ('RE-701', 'GroundstationConnector'),
 ('RE-701', 'IDroneConnectorServiceInstance'),
 ('RE-701', 'IDroneMonitoringServiceInstance'),
 ('RE-701', 'IFlightPlan'),
 ('RE-701', 'IMonitorableMessage'),
 ('RE-701', 'IMonitoringDataHandler'),
 ('RE-701', 'IRemoteMonitoringMessageHandler'),
 ('RE-701', 'IncommingGroundstationConnectionServer'),
 ('RE-701', 'ManagedDrone'),
 ('RE-701', 'MessageMarshaller'),
 ('RE-701', 'MonitoringConnectionTester'),
 ('RE-701', 'MonitoringDispatchThread'),
 ('RE-701', 'PhysicalDrone'),
 ('RE-701', 'PhysicalDroneFleetFactory'),
 ('RE-701', 'PlanPoolManager'),
 ('RE-701', 'RemindsConnector'),
 ('RE-701', 'RemoteMessageHandler'),
 ('RE-701', 'SendToSubscriberCallable'),
 ('RE-701', 'SimpleTakeoffFlightPlan'),
 ('RE-701', 'StateMessageTypeAdapter'),
 ('RE-701', 'UAVAcknowledgeMessage'),
 ('RE-701', 'UAVMonitorableMessage'),
 ('RE-701', 'UAVPlanChangeMessage'),
 ('RE-701', 'UAVStateChangeMessage'),
 ('RE-701', 'VirtualDroneFleetFactory'),
 ('RE-706', 'ArtifactIdentifier'),
 ('RE-706', 'IMonitorableMessage'),
 ('RE-706', 'UAVMonitorableMessage'),
 ('RE-709', 'ConnectionRequestMessage'),
 ('RE-709', 'DispatchQueueManager'),
 ('RE-709', 'DronologyServiceRunner'),
 ('RE-709', 'GroundstationConnector'),
 ('RE-709', 'IncommingGroundstationConnectionServer'),
 ('RE-709', 'PhysicalDroneFleetFactory'),
 ('RE-709', 'RuntimeDroneTypes'),
 ('RE-714', 'AbstractDroneCommand'),
 ('RE-714', 'CommandIds'),
 ('RE-714', 'ConnectionRequestMessage'),
 ('RE-714', 'GoToCommand'),
 ('RE-714', 'GroundstationConnector'),
 ('RE-714', 'IDroneCommand'),
 ('RE-714', 'ReadDispatcher'),
 ('RE-714', 'SetGimbalRotationCommand'),
 ('RE-714', 'SetGimbalTargetCommand'),
 ('RE-714', 'SetGroundSpeedCommand'),
 ('RE-714', 'SetMonitoringFrequencyCommand'),
 ('RE-714', 'SetStateFrequencyCommand'),
 ('RE-714', 'SetVelocityCommand'),
 ('RE-714', 'TakeoffCommand'),
 ('RE-714', 'UAVHandshakeMessage'),
 ('RE-722', 'UAVMessageFactory'),
 ('RE-722', 'UAVModeChangeMessage'),
 ('RE-722', 'UAVMonitoringMessage'),
 ('RE-722', 'UAVStateMessage'),
 ('RE-729', 'AbstractDroneCommand'),
 ('RE-729', 'CommandIds'),
 ('RE-729', 'EmergencyStopCommand'),
 ('RE-729', 'GoToCommand'),
 ('RE-729', 'IDroneCommand'),
 ('RE-729', 'LandCommand'),
 ('RE-729', 'SetGroundSpeedCommand'),
 ('RE-729', 'SetMonitoringFrequencyCommand'),
 ('RE-729', 'SetStateFrequencyCommand'),
 ('RE-729', 'SetVelocityCommand'),
 ('RE-729', 'TakeoffCommand'),
 ('RE-759', 'AFInfoPanel'),
 ('RE-759', 'AFMainLayout'),
 ('RE-759', 'AFMapViewOperations'),
 ('RE-759', 'AFMissionOperations'),
 ('RE-759', 'AbstractFlightPattern'),
 ('RE-759', 'AbstractMissionTask'),
 ('RE-759', 'CollisionInfo'),
 ('RE-759', 'CommandIds'),
 ('RE-759', 'CoordinatedLandingPattern'),
 ('RE-759', 'CoordinatedTakeoffPattern'),
 ('RE-759', 'DelayTask'),
 ('RE-759', 'DistanceChecker'),
 ('RE-759', 'EmergencyStopCommand'),
 ('RE-759', 'FlightManagerService'),
 ('RE-759', 'FlightManagerServiceInstance'),
 ('RE-759', 'FlightManagerServiceRemoteFacade'),
 ('RE-759', 'FlightZoneManager2'),
 ('RE-759', 'FullMissionPlan'),
 ('RE-759', 'IFlightManagerRemoteService'),
 ('RE-759', 'IFlightManagerServiceInstance'),
 ('RE-759', 'IFlightPattern'),
 ('RE-759', 'IMissionPlan'),
 ('RE-759', 'IMissionPlanningRemoteService'),
 ('RE-759', 'IMissionPlanningServiceInstance'),
 ('RE-759', 'IMissionTask'),
 ('RE-759', 'IUAVProxy'),
 ('RE-759', 'JSONMissionPlanReader'),
 ('RE-759', 'LandTask'),
 ('RE-759', 'ManagedDrone'),
 ('RE-759', 'MissionController'),
 ('RE-759', 'MissionExecutionException'),
 ('RE-759', 'MissionHandler'),
 ('RE-759', 'MissionPlanningService'),
 ('RE-759', 'MissionPlanningServiceInstance'),
 ('RE-759', 'MissionPlanningServiceRemoteFacade'),
 ('RE-759', 'MissionUtil'),
 ('RE-759', 'MonitoringConnectionTester'),
 ('RE-759', 'PatternFactory'),
 ('RE-759', 'PatternTask'),
 ('RE-759', 'RemoteManager'),
 ('RE-759', 'RouteTask'),
 ('RE-759', 'ServiceIds'),
 ('RE-759', 'SimpleCheckerMessageHandler'),
 ('RE-759', 'SimpleMonitor'),
 ('RE-759', 'SyncConstants'),
 ('RE-759', 'SyncTask'),
 ('RE-759', 'SynchronizationManager'),
 ('RE-759', 'SynchronizationPoint'),
 ('RE-759', 'SynchronizationState'),
 ('RE-759', 'TakeoffTask'),
 ('RE-759', 'TaskFactory'),
 ('RE-759', 'TaskList'),
 ('RE-759', 'UAVMissionPlan'),
 ('RE-759', 'UAVMonitorableMessage'),
 ('RE-759', 'UAVProxy'),
 ('RE-759', 'WaypointTask'),
 ('RE-759', 'WriteDispatcher'),
 ('RE-766', 'AFMainLayout'),
 ('RE-766', 'AFMapComponent'),
 ('RE-77', 'AbstractDrone'),
 ('RE-77', 'AbstractDroneCommand'),
 ('RE-77', 'AbstractPosition'),
 ('RE-77', 'CommandIds'),
 ('RE-77', 'DroneException'),
 ('RE-77', 'DroneFleetManager'),
 ('RE-77', 'DroneFlightStateManager'),
 ('RE-77', 'DroneInitializationInfo'),
 ('RE-77', 'DroneSetupService'),
 ('RE-77', 'DroneSetupServiceInstance'),
 ('RE-77', 'DroneSetupServiceRemoteFacade'),
 ('RE-77', 'DroneSimulatorServiceInstance'),
 ('RE-77', 'DronologyConstants'),
 ('RE-77', 'DronologyPersistenceUtil'),
 ('RE-77', 'DronologyServiceRunner'),
 ('RE-77', 'DummyLockObject'),
 ('RE-77', 'FileManager'),
 ('RE-77', 'FlightInfo'),
 ('RE-77', 'FlightInfoCreator'),
 ('RE-77', 'FlightManagerService'),
 ('RE-77', 'FlightManagerServiceInstance'),
 ('RE-77', 'FlightManagerServiceRemoteFacade'),
 ('RE-77', 'FlightPlan'),
 ('RE-77', 'FlightPlanFactory'),
 ('RE-77', 'FlightPlanInfo'),
 ('RE-77', 'FlightRoute'),
 ('RE-77', 'FlightRouteInfo'),
 ('RE-77', 'FlightRouteplanningServiceInstance'),
 ('RE-77', 'FlightZoneManager2'),
 ('RE-77', 'FlyingFieldDemoScript'),
 ('RE-77', 'GoToCommand'),
 ('RE-77', 'IDrone'),
 ('RE-77', 'IDroneCommand'),
 ('RE-77', 'IDroneCommandHandler'),
 ('RE-77', 'IDroneSetupRemoteService'),
 ('RE-77', 'IDroneSetupServiceInstance'),
 ('RE-77', 'IFlightManagerRemoteService'),
 ('RE-77', 'IFlightManagerServiceInstance'),
 ('RE-77', 'IFlightPlan'),
 ('RE-77', 'IFlightRoute'),
 ('RE-77', 'IManagedDroneStateChangeListener'),
 ('RE-77', 'IMissionPlan'),
 ('RE-77', 'IPlanStatusChangeListener'),
 ('RE-77', 'IRemoteManager'),
 ('RE-77', 'IStartstrategy'),
 ('RE-77', 'IStopStrategy'),
 ('RE-77', 'IUAVPropertyUpdateNotifier'),
 ('RE-77', 'InfoNotification'),
 ('RE-77', 'LandingStrategy'),
 ('RE-77', 'LlaCoordinate'),
 ('RE-77', 'ManagedDrone'),
 ('RE-77', 'ManagedHashTableList'),
 ('RE-77', 'NvecInterpolator'),
 ('RE-77', 'PhysicalDrone'),
 ('RE-77', 'PhysicalDroneFleetFactory'),
 ('RE-77', 'PlanPool'),
 ('RE-77', 'PlanPoolManager'),
 ('RE-77', 'RemoteInfoFactory'),
 ('RE-77', 'RemoteManager'),
 ('RE-77', 'RemoteRMIRemoteObject'),
 ('RE-77', 'RuntimeDroneTypes'),
 ('RE-77', 'SetGimbalRotationCommand'),
 ('RE-77', 'SetGimbalTargetCommand'),
 ('RE-77', 'SetGroundSpeedCommand'),
 ('RE-77', 'SetMonitoringFrequencyCommand'),
 ('RE-77', 'SetStateFrequencyCommand'),
 ('RE-77', 'SetVelocityCommand'),
 ('RE-77', 'SimulatorFactory'),
 ('RE-77', 'SoloDirector'),
 ('RE-77', 'TakeoffCommand'),
 ('RE-77', 'VirtualDrone'),
 ('RE-77', 'WatchServiceRunner'),
 ('RE-77', 'Waypoint'),
 ('RE-77', 'WorkspaceInitializer'),
 ('RE-8', 'AbstractDrone'),
 ('RE-8', 'DroneFlightStateManager'),
 ('RE-8', 'FlightZoneManager2'),
 ('RE-8', 'IMissionPlanningServiceInstance'),
 ('RE-8', 'ManagedDrone'),
 ('RE-8', 'MissionPlanningService'),
 ('RE-8', 'MissionPlanningServiceInstance'),
 ('RE-8', 'ModeChangeMessageTypeAdapter'),
 ('RE-8', 'PhysicalDrone'),
 ('RE-8', 'SoloDirector'),
 ('RE-8', 'StatusDispatchThread'),
 ('RE-8', 'UAVMessageFactory'),
 ('RE-8', 'UAVModeChangeMessage'),
 ('RE-80', 'ManagedDrone'),
 ('RE-80', 'PhysicalDrone'),
 ('RE-80', 'SoloDirector'),
 ('RE-80', 'VirtualDrone')]

In [50]:
import math
import dit

# Artifacts Similarity with Doc2Vec

Try to reproduce the same empirical evaluation like here: [link](https://arxiv.org/pdf/1507.07998.pdf). Pay attention to:
- Accuracy vs. Dimensionality (we can replace accuracy for false positive rate or true positive rate)
- Visualize paragraph vectors using t-sne
- Computing Cosine Distance and Similarity. More about similarity [link](https://www.kdnuggets.com/2017/08/comparing-distance-measurements-python-scipy.html)

In [51]:
#path_to_trained_model": 'test_data/models/pv/conv/[doc2vec-Py-Java-PVDBOW-500-20E-1592609630.689167].model',
#"path_to_trained_model": 'test_data/models/pv/conv/[doc2vec-Py-Java-Wiki-PVDBOW-500-20E[15]-1592941134.367976].model',
path_to_trained_model = '../dvc-data/systems/dronology/2vec_models/bpe128k/doc2vec/[doc2vec-py-java-PVDBOW-500-20E-128k-c-1751384704.291919].model'

In [52]:

print("Columns:", df_all_system.columns.tolist())
print("Unique type values:", df_all_system['type'].unique())

Columns: ['ids', 'filenames', 'text', 'type', 'conv', 'bpe8k', 'bpe32k', 'bpe128k']
Unique type values: ['req' 'code']

In [53]:
def doc2vec_params():
    return {
        "vectorizationType": VectorizationType.doc2vec,
        "linkType": LinkType.req2src,
        "system": 'dronology',
        "source_type": 'req',
        "target_type": 'code',
        "path_to_trained_model": path_to_trained_model,
        #"source_path": '/tf/main/benchmarking/traceability/testbeds/nltk/[libest-pre-req].csv',
        #"target_path": '/tf/main/benchmarking/traceability/testbeds/nltk/[libest-pre-tc].csv',
        "system_path_config": {
            "system_path": "../dvc-data/systems/dronology/corpus/dronology_conv_with_bpe_fixed.csv",
            "names": ["ids","filenames","text","type", "bpe128k"],
            "sep": "~",
            "prep": Preprocessing.conv
        },
        "saving_path": '../dvc-data/systems/dronology/experiment4.1.5/results/',
        "names": ['Source','Target','Linked?']
    }

In [54]:
doc2vec_params = doc2vec_params()
doc2vec_params

{'vectorizationType': <VectorizationType.doc2vec: 2>,
 'linkType': <LinkType.req2src: 2>,
 'system': 'dronology',
 'source_type': 'req',
 'target_type': 'code',
 'path_to_trained_model': '../dvc-data/systems/dronology/2vec_models/bpe128k/doc2vec/[doc2vec-py-java-PVDBOW-500-20E-128k-c-1751384704.291919].model',
 'system_path_config': {'system_path': '../dvc-data/systems/dronology/corpus/dronology_conv_with_bpe_fixed.csv',
  'names': ['ids', 'filenames', 'text', 'type', 'bpe128k'],
  'sep': '~',
  'prep': <Preprocessing.conv: 1>},
 'saving_path': '../dvc-data/systems/dronology/experiment4.1.5/results/',
 'names': ['Source', 'Target', 'Linked?']}

In [55]:
#Export
class Doc2VecSeqVect(BasicSequenceVectorization):
    
    def __init__(self, params):
        super().__init__(params)
        self.new_model = gensim.models.Doc2Vec.load( params['path_to_trained_model'] )
        self.new_model.init_sims(replace=True)  # Normalizes the vectors in the word2vec class.
        self.df_inferred_src = None
        self.df_inferred_trg = None
        
        self.dict_distance_dispatcher = {
            DistanceMetric.COS: self.cos_scipy,
            SimilarityMetric.Pearson: self.pearson_abs_scipy,
            DistanceMetric.EUC: self.euclidean_scipy,
            DistanceMetric.MAN: self.manhattan_scipy
        }
    
    def distance(self, metric_list, link):
        '''Iterate on the metrics'''
        ν_inferredSource = (
            self.df_inferred_src
                .loc[self.df_inferred_src['ids'].str.contains(link[0]), 'inf-doc2vec']
                .iloc[0]
        )
        w_inferredTarget = (
    self.df_inferred_trg
        .loc[self.df_inferred_trg['ids'].str.contains(link[1]), 'inf-doc2vec']
        .iloc[0]
)
        
        dist = [ self.dict_distance_dispatcher[metric](ν_inferredSource,w_inferredTarget) for metric in metric_list]
        logging.info("Computed distances or similarities "+ str(link) + str(dist))    
        return functools.reduce(lambda a,b : a+b, dist) #Always return a list
    
    def computeDistanceMetric(self, links, metric_list):
        '''It is computed the cosine similarity'''
        
        metric_labels = [ self.dict_labels[metric] for metric in metric_list] #tracking of the labels
        distSim = [[link[0], link[1], self.distance( metric_list, link )] for link in links] #Return the link with metrics
        distSim = [[elem[0], elem[1]] + elem[2] for elem in distSim] #Return the link with metrics
        
        return distSim, functools.reduce(lambda a,b : a+b, metric_labels)

    
    def InferDoc2Vec(self, steps=200):
        '''Activate Inference on Target and Source Corpus'''
        self.df_inferred_src = self.df_source.copy()
        self.df_inferred_trg = self.df_target.copy()
        
        self.df_inferred_src['inf-doc2vec'] =  [self.new_model.infer_vector(artifact.split(),epochs=steps) for artifact in self.df_inferred_src['text'].values]
        self.df_inferred_trg['inf-doc2vec'] =  [self.new_model.infer_vector(artifact.split(),epochs=steps) for artifact in self.df_inferred_trg['text'].values]
        
        logging.info("Infer Doc2Vec on Source and Target Complete")

### Testing Doc2Vec SequenceVectorization

In [188]:
doc2vec = Doc2VecSeqVect(params = doc2vec_params)

2025-07-04 15:57:26,439 : INFO : adding document #0 to Dictionary<0 unique tokens: []>
2025-07-04 15:57:26,460 : INFO : built Dictionary<1652 unique tokens: ['ag', 'ari', 'iv', 'pt', '▁activ']...> from 242 documents (total 78439 corpus positions)
2025-07-04 15:57:26,461 : INFO : Dictionary lifecycle event {'msg': "built Dictionary<1652 unique tokens: ['ag', 'ari', 'iv', 'pt', '▁activ']...> from 242 documents (total 78439 corpus positions)", 'datetime': '2025-07-04T15:57:26.461437', 'gensim': '4.3.3', 'python': '3.9.23 | packaged by conda-forge | (main, Jun  4 2025, 18:02:02) \n[Clang 18.1.8 ]', 'platform': 'macOS-15.5-arm64-arm-64bit', 'event': 'created'}
2025-07-04 15:57:26,461 : INFO : conventional preprocessing documents and dictionary
2025-07-04 15:57:26,464 : INFO : loading Doc2Vec object from ../dvc-data/systems/dronology/2vec_models/bpe128k/doc2vec/[doc2vec-py-java-PVDBOW-500-20E-128k-c-1751384704.291919].model

FileNotFoundError: [Errno 2] No such file or directory: '../dvc-data/systems/dronology/2vec_models/bpe128k/doc2vec/[doc2vec-py-java-PVDBOW-500-20E-128k-c-1751384704.291919].model'

In [189]:
#[step1]Apply Doc2Vec Inference
doc2vec.InferDoc2Vec(steps=200)

NameError: name 'doc2vec' is not defined

In [190]:
doc2vec.df_inferred_src.head(2)

NameError: name 'doc2vec' is not defined

In [191]:
#test_inferDoc2Vec_trg = inferDoc2Vec(df_target)
#test_inferDoc2Vec_trg.head()
doc2vec.df_inferred_trg.head(2)

NameError: name 'doc2vec' is not defined

In [192]:
doc2vec.df_inferred_src .reset_index(drop=True, inplace=True)
doc2vec.df_inferred_trg .reset_index(drop=True, inplace=True)

(doc2vec.df_inferred_trg['inf-doc2vec'][0], doc2vec.df_inferred_trg['inf-doc2vec'][0])

NameError: name 'doc2vec' is not defined

In [193]:
#NOTE: Used .py file to compute, notebook was crashing
#[step 2]NonGroundTruth Computation
#metric_l = [DistanceMetric.EUC,DistanceMetric.COS,DistanceMetric.MAN]# , SimilarityMetric.Pearson]
#doc2vec.ComputeDistanceArtifacts( sampling=False, samples = 50, metric_list = metric_l )
#doc2vec.df_nonground_link.head()

In [ ]:
#[step 3]Saving Non-GroundTruth Links
#doc2vec.SaveLinks()

In [56]:
#export
def LoadLinks(timestamp, params, grtruth=False, sep=' ' ):
    
    path= params['saving_path'] + '['+ params['system'] + '-' + str(params['vectorizationType']) + '-' + str(params['linkType']) + '-' + str(grtruth) + '-{}].csv'.format(timestamp)
    
    logging.info("Loading computed links from... "+ path)

    return pd.read_csv(path, header=0, index_col=0, sep=sep)

In [58]:
big = pd.read_csv('../dvc-data/systems/dronology/experiment4.1.3/results/dronology_doc2vec_all_with_labels_20250704132648.csv')

# 2) Split into ground vs non-ground
df_ground   = big[ big['Linked?'] == 1 ].copy()
df_nonground= big[ big['Linked?'] == 0 ].copy()

# 3) Write out two CSVs
out_dir = '../dvc-data/systems/dronology/experiment4.1.3/results/'
base    = 'dronology-VectorizationType.doc2vec-LinkType.req2src'

ts = '20250704132648'  # same timestamp as your big CSV
fn1 = f'{base}-True-{ts}.csv'
fn2 = f'{base}-False-{ts}.csv'

df_ground.to_csv(os.path.join(out_dir, fn1), index=False)
df_nonground.to_csv(os.path.join(out_dir, fn2), index=False)

print('Wrote:')
print('  Ground-truth links:', fn1, '(', len(df_ground), 'rows )')
print('  Non-ground links :', fn2, '(', len(df_nonground), 'rows )')

Wrote:
  Ground-truth links: dronology-VectorizationType.doc2vec-LinkType.req2src-True-20250704132648.csv ( 393 rows )
  Non-ground links : dronology-VectorizationType.doc2vec-LinkType.req2src-False-20250704132648.csv ( 10279 rows )

In [98]:
#Loading Non-GroundTruth Links (change the timestamp with the assigned in the previous step)
df_nonglinks_doc2vec = LoadLinks(timestamp=20250623132856, params=doc2vec_params, sep = ',')
df_nonglinks_doc2vec.head()

2025-07-02 07:58:18,490 : INFO : Loading computed links from... ../dvc-data/systems/dronology/experiment4.1.1/results/[dronology-VectorizationType.doc2vec-LinkType.req2src-False-20250623132856].csv

FileNotFoundError: [Errno 2] No such file or directory: '../dvc-data/systems/dronology/experiment4.1.1/results/[dronology-VectorizationType.doc2vec-LinkType.req2src-False-20250623132856].csv'

In [99]:
#[step 4]GroundTruthMatching Testing
path_to_ground_truth = '../dvc-data/systems/dronolgy/mappings/ground_truth.txt'
doc2vec.MatchWithGroundTruth(path_to_ground_truth)
doc2vec.df_ground_link

NameError: name 'doc2vec' is not defined

In [100]:
#[step 5]Saving GroundTruth Links
doc2vec.SaveLinks(grtruth = True)

NameError: name 'doc2vec' is not defined

In [101]:
#Loading Non-GroundTruth Links (change the timestamp with the assigned in the previous step)
df_glinks_doc2vec = LoadLinks(timestamp=20250623132856, params=doc2vec_params, grtruth = True, sep = ',')
df_glinks_doc2vec.head()

2025-07-02 08:02:23,104 : INFO : Loading computed links from... ../dvc-data/systems/dronology/experiment4.1.1/results/[dronology-VectorizationType.doc2vec-LinkType.req2src-True-20250623132856].csv

,Target,EUC_dist,EUC_sim,COS_dist,COS_sim,MAN_dist,MAN_sim,Linked?
Source,,,,,,,,
/Users/loganfecko/Desktop/Summer_Research/traceXplainer/dvc-data/systems/dronology/corpus/req/RE-616.txt,/Users/loganfecko/Desktop/Summer_Research/trac...,72.137848,0.013673,0.802002,0.197998,1298.8182,0.000769,1
/Users/loganfecko/Desktop/Summer_Research/traceXplainer/dvc-data/systems/dronology/corpus/req/RE-616.txt,/Users/loganfecko/Desktop/Summer_Research/trac...,51.365795,0.019096,0.809980,0.190020,941.0077,0.001062,1
/Users/loganfecko/Desktop/Summer_Research/traceXplainer/dvc-data/systems/dronology/corpus/req/RE-616.txt,/Users/loganfecko/Desktop/Summer_Research/trac...,65.371864,0.015067,0.808522,0.191478,1174.2109,0.000851,1
/Users/loganfecko/Desktop/Summer_Research/traceXplainer/dvc-data/systems/dronology/corpus/req/RE-616.txt,/Users/loganfecko/Desktop/Summer_Research/trac...,80.934586,0.012205,0.770840,0.229160,1460.6865,0.000684,1
/Users/loganfecko/Desktop/Summer_Research/traceXplainer/dvc-data/systems/dronology/corpus/req/RE-616.txt,/Users/loganfecko/Desktop/Summer_Research/trac...,85.800568,0.011521,0.814711,0.185289,1503.1764,0.000665,1

# Approach Evaluation and Interpretation (doc2vec)

In [111]:
#supervisedEvalDoc2vec = SupervisedVectorEvaluation(doc2vec, similarity=SimilarityMetric.EUC_sim)
#supervisedEvalDoc2vec = SupervisedVectorEvaluation(doc2vec, similarity=SimilarityMetric.COS_sim)
supervisedEvalDoc2vec = SupervisedVectorEvaluation(doc2vec, similarity=SimilarityMetric.MAN_sim)

NameError: name 'SupervisedVectorEvaluation' is not defined

In [ ]:
supervisedEvalDoc2vec.y_test

In [ ]:
supervisedEvalDoc2vec.y_score

In [ ]:
supervisedEvalDoc2vec.Compute_precision_recall_gain()

In [ ]:
supervisedEvalDoc2vec.Compute_avg_precision()

In [ ]:
supervisedEvalDoc2vec.Compute_roc_curve()

## Compute distribution of similarities doc2vec

In [ ]:
#Basic Statistics
filter_doc2vec = doc2vec.df_ground_link
filter_doc2vec.describe()

In [ ]:
lag_plot(filter_doc2vec[[SimilarityMetric.EUC_sim]])

In [ ]:
lag_plot(filter_doc2vec[DistanceMetric.EUC])

In [ ]:
filter_doc2vec.hist(column=[SimilarityMetric.EUC_sim,DistanceMetric.EUC],color='k',bins=50,figsize=[10,5],alpha=0.5)

In [ ]:
#Separate distance from similarity analysis here
errors = filter_doc2vec[[SimilarityMetric.EUC_sim,DistanceMetric.EUC]].std()
print(errors)
filter_doc2vec[[SimilarityMetric.EUC_sim,DistanceMetric.EUC]].plot.kde()

In [ ]:
filter_doc2vec.hist(by='Linked?',column=SimilarityMetric.EUC_sim,figsize=[10, 5],bins=80)

In [ ]:
filter_doc2vec.hist(by='Linked?',column=DistanceMetric.EUC,figsize=[10, 5],bins=80)

In [ ]:
#separate the distance from the similarity plot
boxplot = filter_doc2vec.boxplot(by='Linked?',column=[SimilarityMetric.EUC_sim,DistanceMetric.EUC],figsize=[10, 5])

In [ ]:
boxplot = filter_doc2vec.boxplot(by='Linked?',column=[SimilarityMetric.EUC_sim],figsize=[10, 5])

## Combining Doc2vec and Word2vec
Please check this post for futher detatils [link](https://stats.stackexchange.com/questions/217614/intepreting-doc2vec-cosine-similarity-between-doc-vectors-and-word-vectors)

In [ ]:
! nbdev_build_docs #<-------- [Activate when stable]

In [ ]:
! nbdev_build_lib

In [ ]:
from nbdev.export import notebook2script
notebook2script()

In [ ]:
#! pip install -e .